// Code generated by thriftgo (0.4.2). DO NOT EDIT.

package driver

import (
	"context"
	"fmt"
	"lxh_cx/kitex_gen/lxh_cx/base"
)

type DriverRegisterReq struct {
	IdCardFileId         string `thrift:"idCardFileId,1" frugal:"1,default,string" json:"idCardFileId"`
	DriverLicenseFileId  string `thrift:"driverLicenseFileId,2" frugal:"2,default,string" json:"driverLicenseFileId"`
	DrivingLicenseFileId string `thrift:"drivingLicenseFileId,3" frugal:"3,default,string" json:"drivingLicenseFileId"`
	AvatorFileId         string `thrift:"avatorFileId,4" frugal:"4,default,string" json:"avatorFileId"`
	DriverId             int32  `thrift:"DriverId,5" frugal:"5,default,i32" json:"DriverId"`
}

func NewDriverRegisterReq() *DriverRegisterReq {
	return &DriverRegisterReq{}
}

func (p *DriverRegisterReq) InitDefault() {
}

func (p *DriverRegisterReq) GetIdCardFileId() (v string) {
	return p.IdCardFileId
}

func (p *DriverRegisterReq) GetDriverLicenseFileId() (v string) {
	return p.DriverLicenseFileId
}

func (p *DriverRegisterReq) GetDrivingLicenseFileId() (v string) {
	return p.DrivingLicenseFileId
}

func (p *DriverRegisterReq) GetAvatorFileId() (v string) {
	return p.AvatorFileId
}

func (p *DriverRegisterReq) GetDriverId() (v int32) {
	return p.DriverId
}
func (p *DriverRegisterReq) SetIdCardFileId(val string) {
	p.IdCardFileId = val
}
func (p *DriverRegisterReq) SetDriverLicenseFileId(val string) {
	p.DriverLicenseFileId = val
}
func (p *DriverRegisterReq) SetDrivingLicenseFileId(val string) {
	p.DrivingLicenseFileId = val
}
func (p *DriverRegisterReq) SetAvatorFileId(val string) {
	p.AvatorFileId = val
}
func (p *DriverRegisterReq) SetDriverId(val int32) {
	p.DriverId = val
}

func (p *DriverRegisterReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DriverRegisterReq(%+v)", *p)
}

var fieldIDToName_DriverRegisterReq = map[int16]string{
	1: "idCardFileId",
	2: "driverLicenseFileId",
	3: "drivingLicenseFileId",
	4: "avatorFileId",
	5: "DriverId",
}

type DriverRegisterResp struct {
	BaseResp *base.BaseResp `thrift:"baseResp,1" frugal:"1,default,base.BaseResp" json:"baseResp"`
}

func NewDriverRegisterResp() *DriverRegisterResp {
	return &DriverRegisterResp{}
}

func (p *DriverRegisterResp) InitDefault() {
}

var DriverRegisterResp_BaseResp_DEFAULT *base.BaseResp

func (p *DriverRegisterResp) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return DriverRegisterResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *DriverRegisterResp) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}

func (p *DriverRegisterResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *DriverRegisterResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DriverRegisterResp(%+v)", *p)
}

var fieldIDToName_DriverRegisterResp = map[int16]string{
	1: "baseResp",
}

type DriverAddReq struct {
	IdCardFileId         string `thrift:"idCardFileId,1" frugal:"1,default,string" json:"idCardFileId"`
	DriverLicenseFileId  string `thrift:"driverLicenseFileId,2" frugal:"2,default,string" json:"driverLicenseFileId"`
	DrivingLicenseFileId string `thrift:"drivingLicenseFileId,3" frugal:"3,default,string" json:"drivingLicenseFileId"`
	AvatorFileId         string `thrift:"avatorFileId,4" frugal:"4,default,string" json:"avatorFileId"`
	DriverId             int32  `thrift:"DriverId,5" frugal:"5,default,i32" json:"DriverId"`
	PassengerId          int32  `thrift:"passengerId,6" frugal:"6,default,i32" json:"passengerId"`
}

func NewDriverAddReq() *DriverAddReq {
	return &DriverAddReq{}
}

func (p *DriverAddReq) InitDefault() {
}

func (p *DriverAddReq) GetIdCardFileId() (v string) {
	return p.IdCardFileId
}

func (p *DriverAddReq) GetDriverLicenseFileId() (v string) {
	return p.DriverLicenseFileId
}

func (p *DriverAddReq) GetDrivingLicenseFileId() (v string) {
	return p.DrivingLicenseFileId
}

func (p *DriverAddReq) GetAvatorFileId() (v string) {
	return p.AvatorFileId
}

func (p *DriverAddReq) GetDriverId() (v int32) {
	return p.DriverId
}

func (p *DriverAddReq) GetPassengerId() (v int32) {
	return p.PassengerId
}
func (p *DriverAddReq) SetIdCardFileId(val string) {
	p.IdCardFileId = val
}
func (p *DriverAddReq) SetDriverLicenseFileId(val string) {
	p.DriverLicenseFileId = val
}
func (p *DriverAddReq) SetDrivingLicenseFileId(val string) {
	p.DrivingLicenseFileId = val
}
func (p *DriverAddReq) SetAvatorFileId(val string) {
	p.AvatorFileId = val
}
func (p *DriverAddReq) SetDriverId(val int32) {
	p.DriverId = val
}
func (p *DriverAddReq) SetPassengerId(val int32) {
	p.PassengerId = val
}

func (p *DriverAddReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DriverAddReq(%+v)", *p)
}

var fieldIDToName_DriverAddReq = map[int16]string{
	1: "idCardFileId",
	2: "driverLicenseFileId",
	3: "drivingLicenseFileId",
	4: "avatorFileId",
	5: "DriverId",
	6: "passengerId",
}

type DriverAddResp struct {
	BaseResp *base.BaseResp `thrift:"baseResp,1" frugal:"1,default,base.BaseResp" json:"baseResp"`
}

func NewDriverAddResp() *DriverAddResp {
	return &DriverAddResp{}
}

func (p *DriverAddResp) InitDefault() {
}

var DriverAddResp_BaseResp_DEFAULT *base.BaseResp

func (p *DriverAddResp) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return DriverAddResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *DriverAddResp) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}

func (p *DriverAddResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *DriverAddResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DriverAddResp(%+v)", *p)
}

var fieldIDToName_DriverAddResp = map[int16]string{
	1: "baseResp",
}

type DriverOverOrderReq struct {
	OrderId int32 `thrift:"orderId,1" frugal:"1,default,i32" json:"orderId"`
}

func NewDriverOverOrderReq() *DriverOverOrderReq {
	return &DriverOverOrderReq{}
}

func (p *DriverOverOrderReq) InitDefault() {
}

func (p *DriverOverOrderReq) GetOrderId() (v int32) {
	return p.OrderId
}
func (p *DriverOverOrderReq) SetOrderId(val int32) {
	p.OrderId = val
}

func (p *DriverOverOrderReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DriverOverOrderReq(%+v)", *p)
}

var fieldIDToName_DriverOverOrderReq = map[int16]string{
	1: "orderId",
}

type DriverOverOrderResp struct {
	BaseResp *base.BaseResp `thrift:"baseResp,1" frugal:"1,default,base.BaseResp" json:"baseResp"`
}

func NewDriverOverOrderResp() *DriverOverOrderResp {
	return &DriverOverOrderResp{}
}

func (p *DriverOverOrderResp) InitDefault() {
}

var DriverOverOrderResp_BaseResp_DEFAULT *base.BaseResp

func (p *DriverOverOrderResp) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return DriverOverOrderResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *DriverOverOrderResp) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}

func (p *DriverOverOrderResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *DriverOverOrderResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DriverOverOrderResp(%+v)", *p)
}

var fieldIDToName_DriverOverOrderResp = map[int16]string{
	1: "baseResp",
}

type DriverCancelOrderReq struct {
	DriverId      int32  `thrift:"driverId,1" frugal:"1,default,i32" json:"driverId"`
	ConfirmPerson int32  `thrift:"confirmPerson,2" frugal:"2,default,i32" json:"confirmPerson"`
	ConfirmReason string `thrift:"confirmReason,3" frugal:"3,default,string" json:"confirmReason"`
	ConfirmRemark string `thrift:"confirmRemark,4" frugal:"4,default,string" json:"confirmRemark"`
	OrderId       int32  `thrift:"orderId,5" frugal:"5,default,i32" json:"orderId"`
}

func NewDriverCancelOrderReq() *DriverCancelOrderReq {
	return &DriverCancelOrderReq{}
}

func (p *DriverCancelOrderReq) InitDefault() {
}

func (p *DriverCancelOrderReq) GetDriverId() (v int32) {
	return p.DriverId
}

func (p *DriverCancelOrderReq) GetConfirmPerson() (v int32) {
	return p.ConfirmPerson
}

func (p *DriverCancelOrderReq) GetConfirmReason() (v string) {
	return p.ConfirmReason
}

func (p *DriverCancelOrderReq) GetConfirmRemark() (v string) {
	return p.ConfirmRemark
}

func (p *DriverCancelOrderReq) GetOrderId() (v int32) {
	return p.OrderId
}
func (p *DriverCancelOrderReq) SetDriverId(val int32) {
	p.DriverId = val
}
func (p *DriverCancelOrderReq) SetConfirmPerson(val int32) {
	p.ConfirmPerson = val
}
func (p *DriverCancelOrderReq) SetConfirmReason(val string) {
	p.ConfirmReason = val
}
func (p *DriverCancelOrderReq) SetConfirmRemark(val string) {
	p.ConfirmRemark = val
}
func (p *DriverCancelOrderReq) SetOrderId(val int32) {
	p.OrderId = val
}

func (p *DriverCancelOrderReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DriverCancelOrderReq(%+v)", *p)
}

var fieldIDToName_DriverCancelOrderReq = map[int16]string{
	1: "driverId",
	2: "confirmPerson",
	3: "confirmReason",
	4: "confirmRemark",
	5: "orderId",
}

type DriverCancelOrderResp struct {
	BaseResp *base.BaseResp `thrift:"baseResp,1" frugal:"1,default,base.BaseResp" json:"baseResp"`
}

func NewDriverCancelOrderResp() *DriverCancelOrderResp {
	return &DriverCancelOrderResp{}
}

func (p *DriverCancelOrderResp) InitDefault() {
}

var DriverCancelOrderResp_BaseResp_DEFAULT *base.BaseResp

func (p *DriverCancelOrderResp) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return DriverCancelOrderResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *DriverCancelOrderResp) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}

func (p *DriverCancelOrderResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *DriverCancelOrderResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DriverCancelOrderResp(%+v)", *p)
}

var fieldIDToName_DriverCancelOrderResp = map[int16]string{
	1: "baseResp",
}

type DriverInfoListReq struct {
	DriverId int32 `thrift:"driverId,1" frugal:"1,default,i32" json:"driverId"`
}

func NewDriverInfoListReq() *DriverInfoListReq {
	return &DriverInfoListReq{}
}

func (p *DriverInfoListReq) InitDefault() {
}

func (p *DriverInfoListReq) GetDriverId() (v int32) {
	return p.DriverId
}
func (p *DriverInfoListReq) SetDriverId(val int32) {
	p.DriverId = val
}

func (p *DriverInfoListReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DriverInfoListReq(%+v)", *p)
}

var fieldIDToName_DriverInfoListReq = map[int16]string{
	1: "driverId",
}

type DriverInfoListResp struct {
	BaseResp   *base.BaseResp `thrift:"baseResp,1" frugal:"1,default,base.BaseResp" json:"baseResp"`
	DriverInfo *DriverInfo    `thrift:"driverInfo,2" frugal:"2,default,DriverInfo" json:"driverInfo"`
}

func NewDriverInfoListResp() *DriverInfoListResp {
	return &DriverInfoListResp{}
}

func (p *DriverInfoListResp) InitDefault() {
}

var DriverInfoListResp_BaseResp_DEFAULT *base.BaseResp

func (p *DriverInfoListResp) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return DriverInfoListResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}

var DriverInfoListResp_DriverInfo_DEFAULT *DriverInfo

func (p *DriverInfoListResp) GetDriverInfo() (v *DriverInfo) {
	if !p.IsSetDriverInfo() {
		return DriverInfoListResp_DriverInfo_DEFAULT
	}
	return p.DriverInfo
}
func (p *DriverInfoListResp) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}
func (p *DriverInfoListResp) SetDriverInfo(val *DriverInfo) {
	p.DriverInfo = val
}

func (p *DriverInfoListResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *DriverInfoListResp) IsSetDriverInfo() bool {
	return p.DriverInfo != nil
}

func (p *DriverInfoListResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DriverInfoListResp(%+v)", *p)
}

var fieldIDToName_DriverInfoListResp = map[int16]string{
	1: "baseResp",
	2: "driverInfo",
}

type DriverInfo struct {
	Name        string  `thrift:"name,1" frugal:"1,default,string" json:"name"`
	NickName    string  `thrift:"nickName,2" frugal:"2,default,string" json:"nickName"`
	AllAcount   float64 `thrift:"allAcount,3" frugal:"3,default,double" json:"allAcount"`
	CarAge      string  `thrift:"carAge,4" frugal:"4,default,string" json:"carAge"`
	HandlerFile string  `thrift:"handlerFile,5" frugal:"5,default,string" json:"handlerFile"`
}

func NewDriverInfo() *DriverInfo {
	return &DriverInfo{}
}

func (p *DriverInfo) InitDefault() {
}

func (p *DriverInfo) GetName() (v string) {
	return p.Name
}

func (p *DriverInfo) GetNickName() (v string) {
	return p.NickName
}

func (p *DriverInfo) GetAllAcount() (v float64) {
	return p.AllAcount
}

func (p *DriverInfo) GetCarAge() (v string) {
	return p.CarAge
}

func (p *DriverInfo) GetHandlerFile() (v string) {
	return p.HandlerFile
}
func (p *DriverInfo) SetName(val string) {
	p.Name = val
}
func (p *DriverInfo) SetNickName(val string) {
	p.NickName = val
}
func (p *DriverInfo) SetAllAcount(val float64) {
	p.AllAcount = val
}
func (p *DriverInfo) SetCarAge(val string) {
	p.CarAge = val
}
func (p *DriverInfo) SetHandlerFile(val string) {
	p.HandlerFile = val
}

func (p *DriverInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DriverInfo(%+v)", *p)
}

var fieldIDToName_DriverInfo = map[int16]string{
	1: "name",
	2: "nickName",
	3: "allAcount",
	4: "carAge",
	5: "handlerFile",
}

type DriverService interface {
	DriverRegister(ctx context.Context, req *DriverRegisterReq) (r *DriverRegisterResp, err error)

	DriverAdd(ctx context.Context, req *DriverAddReq) (r *DriverAddResp, err error)

	DriverOverOrder(ctx context.Context, req *DriverOverOrderReq) (r *DriverOverOrderResp, err error)

	DriverCancelOrder(ctx context.Context, req *DriverCancelOrderReq) (r *DriverCancelOrderResp, err error)

	DriverInfoList(ctx context.Context, req *DriverInfoListReq) (r *DriverInfoListResp, err error)
}

type DriverServiceDriverRegisterArgs struct {
	Req *DriverRegisterReq `thrift:"req,1" frugal:"1,default,DriverRegisterReq" json:"req"`
}

func NewDriverServiceDriverRegisterArgs() *DriverServiceDriverRegisterArgs {
	return &DriverServiceDriverRegisterArgs{}
}

func (p *DriverServiceDriverRegisterArgs) InitDefault() {
}

var DriverServiceDriverRegisterArgs_Req_DEFAULT *DriverRegisterReq

func (p *DriverServiceDriverRegisterArgs) GetReq() (v *DriverRegisterReq) {
	if !p.IsSetReq() {
		return DriverServiceDriverRegisterArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *DriverServiceDriverRegisterArgs) SetReq(val *DriverRegisterReq) {
	p.Req = val
}

func (p *DriverServiceDriverRegisterArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *DriverServiceDriverRegisterArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DriverServiceDriverRegisterArgs(%+v)", *p)
}

var fieldIDToName_DriverServiceDriverRegisterArgs = map[int16]string{
	1: "req",
}

type DriverServiceDriverRegisterResult struct {
	Success *DriverRegisterResp `thrift:"success,0,optional" frugal:"0,optional,DriverRegisterResp" json:"success,omitempty"`
}

func NewDriverServiceDriverRegisterResult() *DriverServiceDriverRegisterResult {
	return &DriverServiceDriverRegisterResult{}
}

func (p *DriverServiceDriverRegisterResult) InitDefault() {
}

var DriverServiceDriverRegisterResult_Success_DEFAULT *DriverRegisterResp

func (p *DriverServiceDriverRegisterResult) GetSuccess() (v *DriverRegisterResp) {
	if !p.IsSetSuccess() {
		return DriverServiceDriverRegisterResult_Success_DEFAULT
	}
	return p.Success
}
func (p *DriverServiceDriverRegisterResult) SetSuccess(x interface{}) {
	p.Success = x.(*DriverRegisterResp)
}

func (p *DriverServiceDriverRegisterResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *DriverServiceDriverRegisterResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DriverServiceDriverRegisterResult(%+v)", *p)
}

var fieldIDToName_DriverServiceDriverRegisterResult = map[int16]string{
	0: "success",
}

type DriverServiceDriverAddArgs struct {
	Req *DriverAddReq `thrift:"req,1" frugal:"1,default,DriverAddReq" json:"req"`
}

func NewDriverServiceDriverAddArgs() *DriverServiceDriverAddArgs {
	return &DriverServiceDriverAddArgs{}
}

func (p *DriverServiceDriverAddArgs) InitDefault() {
}

var DriverServiceDriverAddArgs_Req_DEFAULT *DriverAddReq

func (p *DriverServiceDriverAddArgs) GetReq() (v *DriverAddReq) {
	if !p.IsSetReq() {
		return DriverServiceDriverAddArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *DriverServiceDriverAddArgs) SetReq(val *DriverAddReq) {
	p.Req = val
}

func (p *DriverServiceDriverAddArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *DriverServiceDriverAddArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DriverServiceDriverAddArgs(%+v)", *p)
}

var fieldIDToName_DriverServiceDriverAddArgs = map[int16]string{
	1: "req",
}

type DriverServiceDriverAddResult struct {
	Success *DriverAddResp `thrift:"success,0,optional" frugal:"0,optional,DriverAddResp" json:"success,omitempty"`
}

func NewDriverServiceDriverAddResult() *DriverServiceDriverAddResult {
	return &DriverServiceDriverAddResult{}
}

func (p *DriverServiceDriverAddResult) InitDefault() {
}

var DriverServiceDriverAddResult_Success_DEFAULT *DriverAddResp

func (p *DriverServiceDriverAddResult) GetSuccess() (v *DriverAddResp) {
	if !p.IsSetSuccess() {
		return DriverServiceDriverAddResult_Success_DEFAULT
	}
	return p.Success
}
func (p *DriverServiceDriverAddResult) SetSuccess(x interface{}) {
	p.Success = x.(*DriverAddResp)
}

func (p *DriverServiceDriverAddResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *DriverServiceDriverAddResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DriverServiceDriverAddResult(%+v)", *p)
}

var fieldIDToName_DriverServiceDriverAddResult = map[int16]string{
	0: "success",
}

type DriverServiceDriverOverOrderArgs struct {
	Req *DriverOverOrderReq `thrift:"req,1" frugal:"1,default,DriverOverOrderReq" json:"req"`
}

func NewDriverServiceDriverOverOrderArgs() *DriverServiceDriverOverOrderArgs {
	return &DriverServiceDriverOverOrderArgs{}
}

func (p *DriverServiceDriverOverOrderArgs) InitDefault() {
}

var DriverServiceDriverOverOrderArgs_Req_DEFAULT *DriverOverOrderReq

func (p *DriverServiceDriverOverOrderArgs) GetReq() (v *DriverOverOrderReq) {
	if !p.IsSetReq() {
		return DriverServiceDriverOverOrderArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *DriverServiceDriverOverOrderArgs) SetReq(val *DriverOverOrderReq) {
	p.Req = val
}

func (p *DriverServiceDriverOverOrderArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *DriverServiceDriverOverOrderArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DriverServiceDriverOverOrderArgs(%+v)", *p)
}

var fieldIDToName_DriverServiceDriverOverOrderArgs = map[int16]string{
	1: "req",
}

type DriverServiceDriverOverOrderResult struct {
	Success *DriverOverOrderResp `thrift:"success,0,optional" frugal:"0,optional,DriverOverOrderResp" json:"success,omitempty"`
}

func NewDriverServiceDriverOverOrderResult() *DriverServiceDriverOverOrderResult {
	return &DriverServiceDriverOverOrderResult{}
}

func (p *DriverServiceDriverOverOrderResult) InitDefault() {
}

var DriverServiceDriverOverOrderResult_Success_DEFAULT *DriverOverOrderResp

func (p *DriverServiceDriverOverOrderResult) GetSuccess() (v *DriverOverOrderResp) {
	if !p.IsSetSuccess() {
		return DriverServiceDriverOverOrderResult_Success_DEFAULT
	}
	return p.Success
}
func (p *DriverServiceDriverOverOrderResult) SetSuccess(x interface{}) {
	p.Success = x.(*DriverOverOrderResp)
}

func (p *DriverServiceDriverOverOrderResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *DriverServiceDriverOverOrderResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DriverServiceDriverOverOrderResult(%+v)", *p)
}

var fieldIDToName_DriverServiceDriverOverOrderResult = map[int16]string{
	0: "success",
}

type DriverServiceDriverCancelOrderArgs struct {
	Req *DriverCancelOrderReq `thrift:"req,1" frugal:"1,default,DriverCancelOrderReq" json:"req"`
}

func NewDriverServiceDriverCancelOrderArgs() *DriverServiceDriverCancelOrderArgs {
	return &DriverServiceDriverCancelOrderArgs{}
}

func (p *DriverServiceDriverCancelOrderArgs) InitDefault() {
}

var DriverServiceDriverCancelOrderArgs_Req_DEFAULT *DriverCancelOrderReq

func (p *DriverServiceDriverCancelOrderArgs) GetReq() (v *DriverCancelOrderReq) {
	if !p.IsSetReq() {
		return DriverServiceDriverCancelOrderArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *DriverServiceDriverCancelOrderArgs) SetReq(val *DriverCancelOrderReq) {
	p.Req = val
}

func (p *DriverServiceDriverCancelOrderArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *DriverServiceDriverCancelOrderArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DriverServiceDriverCancelOrderArgs(%+v)", *p)
}

var fieldIDToName_DriverServiceDriverCancelOrderArgs = map[int16]string{
	1: "req",
}

type DriverServiceDriverCancelOrderResult struct {
	Success *DriverCancelOrderResp `thrift:"success,0,optional" frugal:"0,optional,DriverCancelOrderResp" json:"success,omitempty"`
}

func NewDriverServiceDriverCancelOrderResult() *DriverServiceDriverCancelOrderResult {
	return &DriverServiceDriverCancelOrderResult{}
}

func (p *DriverServiceDriverCancelOrderResult) InitDefault() {
}

var DriverServiceDriverCancelOrderResult_Success_DEFAULT *DriverCancelOrderResp

func (p *DriverServiceDriverCancelOrderResult) GetSuccess() (v *DriverCancelOrderResp) {
	if !p.IsSetSuccess() {
		return DriverServiceDriverCancelOrderResult_Success_DEFAULT
	}
	return p.Success
}
func (p *DriverServiceDriverCancelOrderResult) SetSuccess(x interface{}) {
	p.Success = x.(*DriverCancelOrderResp)
}

func (p *DriverServiceDriverCancelOrderResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *DriverServiceDriverCancelOrderResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DriverServiceDriverCancelOrderResult(%+v)", *p)
}

var fieldIDToName_DriverServiceDriverCancelOrderResult = map[int16]string{
	0: "success",
}

type DriverServiceDriverInfoListArgs struct {
	Req *DriverInfoListReq `thrift:"req,1" frugal:"1,default,DriverInfoListReq" json:"req"`
}

func NewDriverServiceDriverInfoListArgs() *DriverServiceDriverInfoListArgs {
	return &DriverServiceDriverInfoListArgs{}
}

func (p *DriverServiceDriverInfoListArgs) InitDefault() {
}

var DriverServiceDriverInfoListArgs_Req_DEFAULT *DriverInfoListReq

func (p *DriverServiceDriverInfoListArgs) GetReq() (v *DriverInfoListReq) {
	if !p.IsSetReq() {
		return DriverServiceDriverInfoListArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *DriverServiceDriverInfoListArgs) SetReq(val *DriverInfoListReq) {
	p.Req = val
}

func (p *DriverServiceDriverInfoListArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *DriverServiceDriverInfoListArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DriverServiceDriverInfoListArgs(%+v)", *p)
}

var fieldIDToName_DriverServiceDriverInfoListArgs = map[int16]string{
	1: "req",
}

type DriverServiceDriverInfoListResult struct {
	Success *DriverInfoListResp `thrift:"success,0,optional" frugal:"0,optional,DriverInfoListResp" json:"success,omitempty"`
}

func NewDriverServiceDriverInfoListResult() *DriverServiceDriverInfoListResult {
	return &DriverServiceDriverInfoListResult{}
}

func (p *DriverServiceDriverInfoListResult) InitDefault() {
}

var DriverServiceDriverInfoListResult_Success_DEFAULT *DriverInfoListResp

func (p *DriverServiceDriverInfoListResult) GetSuccess() (v *DriverInfoListResp) {
	if !p.IsSetSuccess() {
		return DriverServiceDriverInfoListResult_Success_DEFAULT
	}
	return p.Success
}
func (p *DriverServiceDriverInfoListResult) SetSuccess(x interface{}) {
	p.Success = x.(*DriverInfoListResp)
}

func (p *DriverServiceDriverInfoListResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *DriverServiceDriverInfoListResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DriverServiceDriverInfoListResult(%+v)", *p)
}

var fieldIDToName_DriverServiceDriverInfoListResult = map[int16]string{
	0: "success",
}
