// Code generated by Kitex v0.14.1. DO NOT EDIT.

package userserver

import (
	user "Didi/kitex_gen/Didi/user"
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	SendSms(ctx context.Context, req *user.SendSmsReq, callOptions ...callopt.Option) (r *user.SendSmsResp, err error)
	LoginUser(ctx context.Context, req *user.LoginUserReq, callOptions ...callopt.Option) (r *user.LoginUserResp, err error)
	RealName(ctx context.Context, req *user.RealNameReq, callOptions ...callopt.Option) (r *user.RealNameResp, err error)
	TakeACar(ctx context.Context, req *user.TakeACarReq, callOptions ...callopt.Option) (r *user.TakeACarResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kUserServerClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kUserServerClient struct {
	*kClient
}

func (p *kUserServerClient) SendSms(ctx context.Context, req *user.SendSmsReq, callOptions ...callopt.Option) (r *user.SendSmsResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SendSms(ctx, req)
}

func (p *kUserServerClient) LoginUser(ctx context.Context, req *user.LoginUserReq, callOptions ...callopt.Option) (r *user.LoginUserResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.LoginUser(ctx, req)
}

func (p *kUserServerClient) RealName(ctx context.Context, req *user.RealNameReq, callOptions ...callopt.Option) (r *user.RealNameResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.RealName(ctx, req)
}

func (p *kUserServerClient) TakeACar(ctx context.Context, req *user.TakeACarReq, callOptions ...callopt.Option) (r *user.TakeACarResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.TakeACar(ctx, req)
}
