// Code generated by Kitex v0.14.1. DO NOT EDIT.

package driverservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	driver0 "lxh_cx/kitex_gen/lxh_cx/driver"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	DriverRegister(ctx context.Context, req *driver0.DriverRegisterReq, callOptions ...callopt.Option) (r *driver0.DriverRegisterResp, err error)
	DriverAdd(ctx context.Context, req *driver0.DriverAddReq, callOptions ...callopt.Option) (r *driver0.DriverAddResp, err error)
	DriverOverOrder(ctx context.Context, req *driver0.DriverOverOrderReq, callOptions ...callopt.Option) (r *driver0.DriverOverOrderResp, err error)
	DriverCancelOrder(ctx context.Context, req *driver0.DriverCancelOrderReq, callOptions ...callopt.Option) (r *driver0.DriverCancelOrderResp, err error)
	DriverInfoList(ctx context.Context, req *driver0.DriverInfoListReq, callOptions ...callopt.Option) (r *driver0.DriverInfoListResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kDriverServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kDriverServiceClient struct {
	*kClient
}

func (p *kDriverServiceClient) DriverRegister(ctx context.Context, req *driver0.DriverRegisterReq, callOptions ...callopt.Option) (r *driver0.DriverRegisterResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DriverRegister(ctx, req)
}

func (p *kDriverServiceClient) DriverAdd(ctx context.Context, req *driver0.DriverAddReq, callOptions ...callopt.Option) (r *driver0.DriverAddResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DriverAdd(ctx, req)
}

func (p *kDriverServiceClient) DriverOverOrder(ctx context.Context, req *driver0.DriverOverOrderReq, callOptions ...callopt.Option) (r *driver0.DriverOverOrderResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DriverOverOrder(ctx, req)
}

func (p *kDriverServiceClient) DriverCancelOrder(ctx context.Context, req *driver0.DriverCancelOrderReq, callOptions ...callopt.Option) (r *driver0.DriverCancelOrderResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DriverCancelOrder(ctx, req)
}

func (p *kDriverServiceClient) DriverInfoList(ctx context.Context, req *driver0.DriverInfoListReq, callOptions ...callopt.Option) (r *driver0.DriverInfoListResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DriverInfoList(ctx, req)
}
