System:
  Host: 127.0.0.1
  Port: 8080
  Name: Didi
MiNio:
  Endpoint: 14.103.243.15:9000
  AccessKeyId: 	minio_DMGEXP
  AccessKeySecret: minio_xZyCX5
  BucketName: test
  UseSsl: false
  BasePath: ""
  BucketUrl: "http://14.103.243.15:9000/test"
UserClient:
  Host: 127.0.0.1
  Port: 50051
DriverClient:
  Host: 127.0.0.1
  Port: 50052