// Code generated by Kitex v0.14.1. DO NOT EDIT.

package userserver

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	user "kitex_main/kitex_gen/Ride_hailing_platform/user"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"SendSms": kitex.NewMethodInfo(
		sendSmsHandler,
		newUserServerSendSmsArgs,
		newUserServerSendSmsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Login": kitex.NewMethodInfo(
		loginHandler,
		newUserServerLoginArgs,
		newUserServerLoginResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"CallBack": kitex.NewMethodInfo(
		callBackHandler,
		newUserServerCallBackArgs,
		newUserServerCallBackResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"InfoUser": kitex.NewMethodInfo(
		infoUserHandler,
		newUserServerInfoUserArgs,
		newUserServerInfoUserResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	userServerServiceInfo                = NewServiceInfo()
	userServerServiceInfoForClient       = NewServiceInfoForClient()
	userServerServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return userServerServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return userServerServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return userServerServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "UserServer"
	handlerType := (*user.UserServer)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "user",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.14.1",
		Extra:           extra,
	}
	return svcInfo
}

func sendSmsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServerSendSmsArgs)
	realResult := result.(*user.UserServerSendSmsResult)
	success, err := handler.(user.UserServer).SendSms(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServerSendSmsArgs() interface{} {
	return user.NewUserServerSendSmsArgs()
}

func newUserServerSendSmsResult() interface{} {
	return user.NewUserServerSendSmsResult()
}

func loginHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServerLoginArgs)
	realResult := result.(*user.UserServerLoginResult)
	success, err := handler.(user.UserServer).Login(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServerLoginArgs() interface{} {
	return user.NewUserServerLoginArgs()
}

func newUserServerLoginResult() interface{} {
	return user.NewUserServerLoginResult()
}

func callBackHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServerCallBackArgs)
	realResult := result.(*user.UserServerCallBackResult)
	success, err := handler.(user.UserServer).CallBack(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServerCallBackArgs() interface{} {
	return user.NewUserServerCallBackArgs()
}

func newUserServerCallBackResult() interface{} {
	return user.NewUserServerCallBackResult()
}

func infoUserHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServerInfoUserArgs)
	realResult := result.(*user.UserServerInfoUserResult)
	success, err := handler.(user.UserServer).InfoUser(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServerInfoUserArgs() interface{} {
	return user.NewUserServerInfoUserArgs()
}

func newUserServerInfoUserResult() interface{} {
	return user.NewUserServerInfoUserResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) SendSms(ctx context.Context, req *user.SendSmsReq) (r *user.SendSmsResp, err error) {
	var _args user.UserServerSendSmsArgs
	_args.Req = req
	var _result user.UserServerSendSmsResult
	if err = p.c.Call(ctx, "SendSms", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Login(ctx context.Context, req *user.LoginReq) (r *user.LoginResp, err error) {
	var _args user.UserServerLoginArgs
	_args.Req = req
	var _result user.UserServerLoginResult
	if err = p.c.Call(ctx, "Login", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CallBack(ctx context.Context, req *user.CallBackReq) (r *user.CallBackResp, err error) {
	var _args user.UserServerCallBackArgs
	_args.Req = req
	var _result user.UserServerCallBackResult
	if err = p.c.Call(ctx, "CallBack", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) InfoUser(ctx context.Context, req *user.InfoUserReq) (r *user.InfoUserResp, err error) {
	var _args user.UserServerInfoUserArgs
	_args.Req = req
	var _result user.UserServerInfoUserResult
	if err = p.c.Call(ctx, "InfoUser", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
