// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	_ "lxh_cx/init"
	"lxh_cx/router"
)

func main() {

	h := server.Default(server.WithHostPorts(":8899"))
	router.LoadRouter(h)
	h.Spin()
}
