// Code generated by Kitex v0.14.1. DO NOT EDIT.

package trips

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	ride "kitex_main/kitex_gen/Ride_hailing_platform/ride"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	CreateTrips(ctx context.Context, req *ride.CreateTripsReq, callOptions ...callopt.Option) (r *ride.CreateTripsResp, err error)
	UpdatedTrips(ctx context.Context, req *ride.UpdatedTripsReq, callOptions ...callopt.Option) (r *ride.UpdatedTripsResp, err error)
	CreatedOrder(ctx context.Context, req *ride.CreatedOrderReq, callOptions ...callopt.Option) (r *ride.CreatedOrderResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kTripsClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kTripsClient struct {
	*kClient
}

func (p *kTripsClient) CreateTrips(ctx context.Context, req *ride.CreateTripsReq, callOptions ...callopt.Option) (r *ride.CreateTripsResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateTrips(ctx, req)
}

func (p *kTripsClient) UpdatedTrips(ctx context.Context, req *ride.UpdatedTripsReq, callOptions ...callopt.Option) (r *ride.UpdatedTripsResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdatedTrips(ctx, req)
}

func (p *kTripsClient) CreatedOrder(ctx context.Context, req *ride.CreatedOrderReq, callOptions ...callopt.Option) (r *ride.CreatedOrderResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreatedOrder(ctx, req)
}
