// Code generated by Kitex v0.14.1. DO NOT EDIT.

package trips

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	ride "kitex_main/kitex_gen/Ride_hailing_platform/ride"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"CreateTrips": kitex.NewMethodInfo(
		createTripsHandler,
		newTripsCreateTripsArgs,
		newTripsCreateTripsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"UpdatedTrips": kitex.NewMethodInfo(
		updatedTripsHandler,
		newTripsUpdatedTripsArgs,
		newTripsUpdatedTripsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"CreatedOrder": kitex.NewMethodInfo(
		createdOrderHandler,
		newTripsCreatedOrderArgs,
		newTripsCreatedOrderResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	tripsServiceInfo                = NewServiceInfo()
	tripsServiceInfoForClient       = NewServiceInfoForClient()
	tripsServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return tripsServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return tripsServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return tripsServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "Trips"
	handlerType := (*ride.Trips)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "ride",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.14.1",
		Extra:           extra,
	}
	return svcInfo
}

func createTripsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*ride.TripsCreateTripsArgs)
	realResult := result.(*ride.TripsCreateTripsResult)
	success, err := handler.(ride.Trips).CreateTrips(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newTripsCreateTripsArgs() interface{} {
	return ride.NewTripsCreateTripsArgs()
}

func newTripsCreateTripsResult() interface{} {
	return ride.NewTripsCreateTripsResult()
}

func updatedTripsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*ride.TripsUpdatedTripsArgs)
	realResult := result.(*ride.TripsUpdatedTripsResult)
	success, err := handler.(ride.Trips).UpdatedTrips(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newTripsUpdatedTripsArgs() interface{} {
	return ride.NewTripsUpdatedTripsArgs()
}

func newTripsUpdatedTripsResult() interface{} {
	return ride.NewTripsUpdatedTripsResult()
}

func createdOrderHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*ride.TripsCreatedOrderArgs)
	realResult := result.(*ride.TripsCreatedOrderResult)
	success, err := handler.(ride.Trips).CreatedOrder(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newTripsCreatedOrderArgs() interface{} {
	return ride.NewTripsCreatedOrderArgs()
}

func newTripsCreatedOrderResult() interface{} {
	return ride.NewTripsCreatedOrderResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) CreateTrips(ctx context.Context, req *ride.CreateTripsReq) (r *ride.CreateTripsResp, err error) {
	var _args ride.TripsCreateTripsArgs
	_args.Req = req
	var _result ride.TripsCreateTripsResult
	if err = p.c.Call(ctx, "CreateTrips", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpdatedTrips(ctx context.Context, req *ride.UpdatedTripsReq) (r *ride.UpdatedTripsResp, err error) {
	var _args ride.TripsUpdatedTripsArgs
	_args.Req = req
	var _result ride.TripsUpdatedTripsResult
	if err = p.c.Call(ctx, "UpdatedTrips", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CreatedOrder(ctx context.Context, req *ride.CreatedOrderReq) (r *ride.CreatedOrderResp, err error) {
	var _args ride.TripsCreatedOrderArgs
	_args.Req = req
	var _result ride.TripsCreatedOrderResult
	if err = p.c.Call(ctx, "CreatedOrder", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
