// Code generated by Kitex v0.14.1. DO NOT EDIT.

package passengersserver

import (
	passengers "Ride_hailing_platform/kitex_gen/passengers"
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	SendSms(ctx context.Context, req *passengers.SendSmsReq, callOptions ...callopt.Option) (r *passengers.SendSmsResp, err error)
	Register(ctx context.Context, req *passengers.RegisterReq, callOptions ...callopt.Option) (r *passengers.RegisterResp, err error)
	Login(ctx context.Context, req *passengers.LoginReq, callOptions ...callopt.Option) (r *passengers.LoginResp, err error)
	GetLocation(ctx context.Context, req *passengers.LocationReq, callOptions ...callopt.Option) (r *passengers.LocationResp, err error)
	GetTripInfo(ctx context.Context, req *passengers.TripReq, callOptions ...callopt.Option) (r *passengers.TripResp, err error)
	GetPricing(ctx context.Context, req *passengers.PricingReq, callOptions ...callopt.Option) (r *passengers.PricingResp, err error)
	PlaceOrder(ctx context.Context, req *passengers.OrderReq, callOptions ...callopt.Option) (r *passengers.OrderResp, err error)
	RoutePlan(ctx context.Context, req *passengers.RoutePlanReq, callOptions ...callopt.Option) (r *passengers.RoutePlanResp, err error)
	WechatLogin(ctx context.Context, req *passengers.WechatLoginReq, callOptions ...callopt.Option) (r *passengers.WechatLoginResp, err error)
	BindWechat(ctx context.Context, req *passengers.BindWechatReq, callOptions ...callopt.Option) (r *passengers.BindWechatResp, err error)
	UnbindWechat(ctx context.Context, req *passengers.UnbindWechatReq, callOptions ...callopt.Option) (r *passengers.UnbindWechatResp, err error)
	GetUserInfo(ctx context.Context, req *passengers.GetUserInfoReq, callOptions ...callopt.Option) (r *passengers.GetUserInfoResp, err error)
	UpdateUserInfo(ctx context.Context, req *passengers.UpdateUserInfoReq, callOptions ...callopt.Option) (r *passengers.UpdateUserInfoResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kPassengersServerClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kPassengersServerClient struct {
	*kClient
}

func (p *kPassengersServerClient) SendSms(ctx context.Context, req *passengers.SendSmsReq, callOptions ...callopt.Option) (r *passengers.SendSmsResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SendSms(ctx, req)
}

func (p *kPassengersServerClient) Register(ctx context.Context, req *passengers.RegisterReq, callOptions ...callopt.Option) (r *passengers.RegisterResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Register(ctx, req)
}

func (p *kPassengersServerClient) Login(ctx context.Context, req *passengers.LoginReq, callOptions ...callopt.Option) (r *passengers.LoginResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Login(ctx, req)
}

func (p *kPassengersServerClient) GetLocation(ctx context.Context, req *passengers.LocationReq, callOptions ...callopt.Option) (r *passengers.LocationResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetLocation(ctx, req)
}

func (p *kPassengersServerClient) GetTripInfo(ctx context.Context, req *passengers.TripReq, callOptions ...callopt.Option) (r *passengers.TripResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetTripInfo(ctx, req)
}

func (p *kPassengersServerClient) GetPricing(ctx context.Context, req *passengers.PricingReq, callOptions ...callopt.Option) (r *passengers.PricingResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetPricing(ctx, req)
}

func (p *kPassengersServerClient) PlaceOrder(ctx context.Context, req *passengers.OrderReq, callOptions ...callopt.Option) (r *passengers.OrderResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.PlaceOrder(ctx, req)
}

func (p *kPassengersServerClient) RoutePlan(ctx context.Context, req *passengers.RoutePlanReq, callOptions ...callopt.Option) (r *passengers.RoutePlanResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.RoutePlan(ctx, req)
}

func (p *kPassengersServerClient) WechatLogin(ctx context.Context, req *passengers.WechatLoginReq, callOptions ...callopt.Option) (r *passengers.WechatLoginResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.WechatLogin(ctx, req)
}

func (p *kPassengersServerClient) BindWechat(ctx context.Context, req *passengers.BindWechatReq, callOptions ...callopt.Option) (r *passengers.BindWechatResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.BindWechat(ctx, req)
}

func (p *kPassengersServerClient) UnbindWechat(ctx context.Context, req *passengers.UnbindWechatReq, callOptions ...callopt.Option) (r *passengers.UnbindWechatResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UnbindWechat(ctx, req)
}

func (p *kPassengersServerClient) GetUserInfo(ctx context.Context, req *passengers.GetUserInfoReq, callOptions ...callopt.Option) (r *passengers.GetUserInfoResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetUserInfo(ctx, req)
}

func (p *kPassengersServerClient) UpdateUserInfo(ctx context.Context, req *passengers.UpdateUserInfoReq, callOptions ...callopt.Option) (r *passengers.UpdateUserInfoResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateUserInfo(ctx, req)
}
