// Code generated by Kitex v0.14.1. DO NOT EDIT.

package passengersserver

import (
	passengers "Ride_hailing_platform/kitex_gen/passengers"
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"SendSms": kitex.NewMethodInfo(
		sendSmsHandler,
		newPassengersServerSendSmsArgs,
		newPassengersServerSendSmsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Register": kitex.NewMethodInfo(
		registerHandler,
		newPassengersServerRegisterArgs,
		newPassengersServerRegisterResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Login": kitex.NewMethodInfo(
		loginHandler,
		newPassengersServerLoginArgs,
		newPassengersServerLoginResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetLocation": kitex.NewMethodInfo(
		getLocationHandler,
		newPassengersServerGetLocationArgs,
		newPassengersServerGetLocationResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetTripInfo": kitex.NewMethodInfo(
		getTripInfoHandler,
		newPassengersServerGetTripInfoArgs,
		newPassengersServerGetTripInfoResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetPricing": kitex.NewMethodInfo(
		getPricingHandler,
		newPassengersServerGetPricingArgs,
		newPassengersServerGetPricingResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"PlaceOrder": kitex.NewMethodInfo(
		placeOrderHandler,
		newPassengersServerPlaceOrderArgs,
		newPassengersServerPlaceOrderResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"RoutePlan": kitex.NewMethodInfo(
		routePlanHandler,
		newPassengersServerRoutePlanArgs,
		newPassengersServerRoutePlanResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"WechatLogin": kitex.NewMethodInfo(
		wechatLoginHandler,
		newPassengersServerWechatLoginArgs,
		newPassengersServerWechatLoginResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"BindWechat": kitex.NewMethodInfo(
		bindWechatHandler,
		newPassengersServerBindWechatArgs,
		newPassengersServerBindWechatResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"UnbindWechat": kitex.NewMethodInfo(
		unbindWechatHandler,
		newPassengersServerUnbindWechatArgs,
		newPassengersServerUnbindWechatResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetUserInfo": kitex.NewMethodInfo(
		getUserInfoHandler,
		newPassengersServerGetUserInfoArgs,
		newPassengersServerGetUserInfoResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"UpdateUserInfo": kitex.NewMethodInfo(
		updateUserInfoHandler,
		newPassengersServerUpdateUserInfoArgs,
		newPassengersServerUpdateUserInfoResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	passengersServerServiceInfo                = NewServiceInfo()
	passengersServerServiceInfoForClient       = NewServiceInfoForClient()
	passengersServerServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return passengersServerServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return passengersServerServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return passengersServerServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "PassengersServer"
	handlerType := (*passengers.PassengersServer)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "passengers",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.14.1",
		Extra:           extra,
	}
	return svcInfo
}

func sendSmsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*passengers.PassengersServerSendSmsArgs)
	realResult := result.(*passengers.PassengersServerSendSmsResult)
	success, err := handler.(passengers.PassengersServer).SendSms(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newPassengersServerSendSmsArgs() interface{} {
	return passengers.NewPassengersServerSendSmsArgs()
}

func newPassengersServerSendSmsResult() interface{} {
	return passengers.NewPassengersServerSendSmsResult()
}

func registerHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*passengers.PassengersServerRegisterArgs)
	realResult := result.(*passengers.PassengersServerRegisterResult)
	success, err := handler.(passengers.PassengersServer).Register(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newPassengersServerRegisterArgs() interface{} {
	return passengers.NewPassengersServerRegisterArgs()
}

func newPassengersServerRegisterResult() interface{} {
	return passengers.NewPassengersServerRegisterResult()
}

func loginHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*passengers.PassengersServerLoginArgs)
	realResult := result.(*passengers.PassengersServerLoginResult)
	success, err := handler.(passengers.PassengersServer).Login(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newPassengersServerLoginArgs() interface{} {
	return passengers.NewPassengersServerLoginArgs()
}

func newPassengersServerLoginResult() interface{} {
	return passengers.NewPassengersServerLoginResult()
}

func getLocationHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*passengers.PassengersServerGetLocationArgs)
	realResult := result.(*passengers.PassengersServerGetLocationResult)
	success, err := handler.(passengers.PassengersServer).GetLocation(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newPassengersServerGetLocationArgs() interface{} {
	return passengers.NewPassengersServerGetLocationArgs()
}

func newPassengersServerGetLocationResult() interface{} {
	return passengers.NewPassengersServerGetLocationResult()
}

func getTripInfoHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*passengers.PassengersServerGetTripInfoArgs)
	realResult := result.(*passengers.PassengersServerGetTripInfoResult)
	success, err := handler.(passengers.PassengersServer).GetTripInfo(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newPassengersServerGetTripInfoArgs() interface{} {
	return passengers.NewPassengersServerGetTripInfoArgs()
}

func newPassengersServerGetTripInfoResult() interface{} {
	return passengers.NewPassengersServerGetTripInfoResult()
}

func getPricingHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*passengers.PassengersServerGetPricingArgs)
	realResult := result.(*passengers.PassengersServerGetPricingResult)
	success, err := handler.(passengers.PassengersServer).GetPricing(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newPassengersServerGetPricingArgs() interface{} {
	return passengers.NewPassengersServerGetPricingArgs()
}

func newPassengersServerGetPricingResult() interface{} {
	return passengers.NewPassengersServerGetPricingResult()
}

func placeOrderHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*passengers.PassengersServerPlaceOrderArgs)
	realResult := result.(*passengers.PassengersServerPlaceOrderResult)
	success, err := handler.(passengers.PassengersServer).PlaceOrder(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newPassengersServerPlaceOrderArgs() interface{} {
	return passengers.NewPassengersServerPlaceOrderArgs()
}

func newPassengersServerPlaceOrderResult() interface{} {
	return passengers.NewPassengersServerPlaceOrderResult()
}

func routePlanHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*passengers.PassengersServerRoutePlanArgs)
	realResult := result.(*passengers.PassengersServerRoutePlanResult)
	success, err := handler.(passengers.PassengersServer).RoutePlan(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newPassengersServerRoutePlanArgs() interface{} {
	return passengers.NewPassengersServerRoutePlanArgs()
}

func newPassengersServerRoutePlanResult() interface{} {
	return passengers.NewPassengersServerRoutePlanResult()
}

func wechatLoginHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*passengers.PassengersServerWechatLoginArgs)
	realResult := result.(*passengers.PassengersServerWechatLoginResult)
	success, err := handler.(passengers.PassengersServer).WechatLogin(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newPassengersServerWechatLoginArgs() interface{} {
	return passengers.NewPassengersServerWechatLoginArgs()
}

func newPassengersServerWechatLoginResult() interface{} {
	return passengers.NewPassengersServerWechatLoginResult()
}

func bindWechatHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*passengers.PassengersServerBindWechatArgs)
	realResult := result.(*passengers.PassengersServerBindWechatResult)
	success, err := handler.(passengers.PassengersServer).BindWechat(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newPassengersServerBindWechatArgs() interface{} {
	return passengers.NewPassengersServerBindWechatArgs()
}

func newPassengersServerBindWechatResult() interface{} {
	return passengers.NewPassengersServerBindWechatResult()
}

func unbindWechatHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*passengers.PassengersServerUnbindWechatArgs)
	realResult := result.(*passengers.PassengersServerUnbindWechatResult)
	success, err := handler.(passengers.PassengersServer).UnbindWechat(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newPassengersServerUnbindWechatArgs() interface{} {
	return passengers.NewPassengersServerUnbindWechatArgs()
}

func newPassengersServerUnbindWechatResult() interface{} {
	return passengers.NewPassengersServerUnbindWechatResult()
}

func getUserInfoHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*passengers.PassengersServerGetUserInfoArgs)
	realResult := result.(*passengers.PassengersServerGetUserInfoResult)
	success, err := handler.(passengers.PassengersServer).GetUserInfo(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newPassengersServerGetUserInfoArgs() interface{} {
	return passengers.NewPassengersServerGetUserInfoArgs()
}

func newPassengersServerGetUserInfoResult() interface{} {
	return passengers.NewPassengersServerGetUserInfoResult()
}

func updateUserInfoHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*passengers.PassengersServerUpdateUserInfoArgs)
	realResult := result.(*passengers.PassengersServerUpdateUserInfoResult)
	success, err := handler.(passengers.PassengersServer).UpdateUserInfo(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newPassengersServerUpdateUserInfoArgs() interface{} {
	return passengers.NewPassengersServerUpdateUserInfoArgs()
}

func newPassengersServerUpdateUserInfoResult() interface{} {
	return passengers.NewPassengersServerUpdateUserInfoResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) SendSms(ctx context.Context, req *passengers.SendSmsReq) (r *passengers.SendSmsResp, err error) {
	var _args passengers.PassengersServerSendSmsArgs
	_args.Req = req
	var _result passengers.PassengersServerSendSmsResult
	if err = p.c.Call(ctx, "SendSms", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Register(ctx context.Context, req *passengers.RegisterReq) (r *passengers.RegisterResp, err error) {
	var _args passengers.PassengersServerRegisterArgs
	_args.Req = req
	var _result passengers.PassengersServerRegisterResult
	if err = p.c.Call(ctx, "Register", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Login(ctx context.Context, req *passengers.LoginReq) (r *passengers.LoginResp, err error) {
	var _args passengers.PassengersServerLoginArgs
	_args.Req = req
	var _result passengers.PassengersServerLoginResult
	if err = p.c.Call(ctx, "Login", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetLocation(ctx context.Context, req *passengers.LocationReq) (r *passengers.LocationResp, err error) {
	var _args passengers.PassengersServerGetLocationArgs
	_args.Req = req
	var _result passengers.PassengersServerGetLocationResult
	if err = p.c.Call(ctx, "GetLocation", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetTripInfo(ctx context.Context, req *passengers.TripReq) (r *passengers.TripResp, err error) {
	var _args passengers.PassengersServerGetTripInfoArgs
	_args.Req = req
	var _result passengers.PassengersServerGetTripInfoResult
	if err = p.c.Call(ctx, "GetTripInfo", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetPricing(ctx context.Context, req *passengers.PricingReq) (r *passengers.PricingResp, err error) {
	var _args passengers.PassengersServerGetPricingArgs
	_args.Req = req
	var _result passengers.PassengersServerGetPricingResult
	if err = p.c.Call(ctx, "GetPricing", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) PlaceOrder(ctx context.Context, req *passengers.OrderReq) (r *passengers.OrderResp, err error) {
	var _args passengers.PassengersServerPlaceOrderArgs
	_args.Req = req
	var _result passengers.PassengersServerPlaceOrderResult
	if err = p.c.Call(ctx, "PlaceOrder", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) RoutePlan(ctx context.Context, req *passengers.RoutePlanReq) (r *passengers.RoutePlanResp, err error) {
	var _args passengers.PassengersServerRoutePlanArgs
	_args.Req = req
	var _result passengers.PassengersServerRoutePlanResult
	if err = p.c.Call(ctx, "RoutePlan", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) WechatLogin(ctx context.Context, req *passengers.WechatLoginReq) (r *passengers.WechatLoginResp, err error) {
	var _args passengers.PassengersServerWechatLoginArgs
	_args.Req = req
	var _result passengers.PassengersServerWechatLoginResult
	if err = p.c.Call(ctx, "WechatLogin", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) BindWechat(ctx context.Context, req *passengers.BindWechatReq) (r *passengers.BindWechatResp, err error) {
	var _args passengers.PassengersServerBindWechatArgs
	_args.Req = req
	var _result passengers.PassengersServerBindWechatResult
	if err = p.c.Call(ctx, "BindWechat", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UnbindWechat(ctx context.Context, req *passengers.UnbindWechatReq) (r *passengers.UnbindWechatResp, err error) {
	var _args passengers.PassengersServerUnbindWechatArgs
	_args.Req = req
	var _result passengers.PassengersServerUnbindWechatResult
	if err = p.c.Call(ctx, "UnbindWechat", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetUserInfo(ctx context.Context, req *passengers.GetUserInfoReq) (r *passengers.GetUserInfoResp, err error) {
	var _args passengers.PassengersServerGetUserInfoArgs
	_args.Req = req
	var _result passengers.PassengersServerGetUserInfoResult
	if err = p.c.Call(ctx, "GetUserInfo", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpdateUserInfo(ctx context.Context, req *passengers.UpdateUserInfoReq) (r *passengers.UpdateUserInfoResp, err error) {
	var _args passengers.PassengersServerUpdateUserInfoArgs
	_args.Req = req
	var _result passengers.PassengersServerUpdateUserInfoResult
	if err = p.c.Call(ctx, "UpdateUserInfo", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
