// Code generated by Kitex v0.14.1. DO NOT EDIT.

package driverservice

import (
	driver0 "cart/kitex_gen/cart/driver"
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	DriverPetition(ctx context.Context, req *driver0.DriverPetitionReq, callOptions ...callopt.Option) (r *driver0.DriverPetitionResp, err error)
	CheckStatus(ctx context.Context, req *driver0.CheckStatusReq, callOptions ...callopt.Option) (r *driver0.CheckStatusResp, err error)
	DriverLogin(ctx context.Context, req *driver0.DriverLoginReq, callOptions ...callopt.Option) (r *driver0.DriverLoginResp, err error)
	GetDriverInfo(ctx context.Context, req *driver0.GetDriverInfoReq, callOptions ...callopt.Option) (r *driver0.GetDriverInfoResp, err error)
	UpdateDriverInfo(ctx context.Context, req *driver0.UpdateDriverInfoReq, callOptions ...callopt.Option) (r *driver0.UpdateDriverInfoResp, err error)
	ChangeStatus(ctx context.Context, req *driver0.ChangeStatusReq, callOptions ...callopt.Option) (r *driver0.ChangeStatusResp, err error)
	GetPendingOrders(ctx context.Context, req *driver0.GetPendingOrdersReq, callOptions ...callopt.Option) (r *driver0.GetPendingOrdersResp, err error)
	AcceptOrder(ctx context.Context, req *driver0.AcceptOrderReq, callOptions ...callopt.Option) (r *driver0.AcceptOrderResp, err error)
	StartTrip(ctx context.Context, req *driver0.StartTripReq, callOptions ...callopt.Option) (r *driver0.StartTripResp, err error)
	CompleteOrder(ctx context.Context, req *driver0.CompleteOrderReq, callOptions ...callopt.Option) (r *driver0.CompleteOrderResp, err error)
	CancelOrder(ctx context.Context, req *driver0.CancelOrderReq, callOptions ...callopt.Option) (r *driver0.CancelOrderResp, err error)
	GetIncome(ctx context.Context, req *driver0.GetIncomeReq, callOptions ...callopt.Option) (r *driver0.GetIncomeResp, err error)
	UpdateLocation(ctx context.Context, req *driver0.UpdateLocationReq, callOptions ...callopt.Option) (r *driver0.UpdateLocationResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kDriverServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kDriverServiceClient struct {
	*kClient
}

func (p *kDriverServiceClient) DriverPetition(ctx context.Context, req *driver0.DriverPetitionReq, callOptions ...callopt.Option) (r *driver0.DriverPetitionResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DriverPetition(ctx, req)
}

func (p *kDriverServiceClient) CheckStatus(ctx context.Context, req *driver0.CheckStatusReq, callOptions ...callopt.Option) (r *driver0.CheckStatusResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CheckStatus(ctx, req)
}

func (p *kDriverServiceClient) DriverLogin(ctx context.Context, req *driver0.DriverLoginReq, callOptions ...callopt.Option) (r *driver0.DriverLoginResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DriverLogin(ctx, req)
}

func (p *kDriverServiceClient) GetDriverInfo(ctx context.Context, req *driver0.GetDriverInfoReq, callOptions ...callopt.Option) (r *driver0.GetDriverInfoResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetDriverInfo(ctx, req)
}

func (p *kDriverServiceClient) UpdateDriverInfo(ctx context.Context, req *driver0.UpdateDriverInfoReq, callOptions ...callopt.Option) (r *driver0.UpdateDriverInfoResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateDriverInfo(ctx, req)
}

func (p *kDriverServiceClient) ChangeStatus(ctx context.Context, req *driver0.ChangeStatusReq, callOptions ...callopt.Option) (r *driver0.ChangeStatusResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ChangeStatus(ctx, req)
}

func (p *kDriverServiceClient) GetPendingOrders(ctx context.Context, req *driver0.GetPendingOrdersReq, callOptions ...callopt.Option) (r *driver0.GetPendingOrdersResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetPendingOrders(ctx, req)
}

func (p *kDriverServiceClient) AcceptOrder(ctx context.Context, req *driver0.AcceptOrderReq, callOptions ...callopt.Option) (r *driver0.AcceptOrderResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.AcceptOrder(ctx, req)
}

func (p *kDriverServiceClient) StartTrip(ctx context.Context, req *driver0.StartTripReq, callOptions ...callopt.Option) (r *driver0.StartTripResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.StartTrip(ctx, req)
}

func (p *kDriverServiceClient) CompleteOrder(ctx context.Context, req *driver0.CompleteOrderReq, callOptions ...callopt.Option) (r *driver0.CompleteOrderResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CompleteOrder(ctx, req)
}

func (p *kDriverServiceClient) CancelOrder(ctx context.Context, req *driver0.CancelOrderReq, callOptions ...callopt.Option) (r *driver0.CancelOrderResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CancelOrder(ctx, req)
}

func (p *kDriverServiceClient) GetIncome(ctx context.Context, req *driver0.GetIncomeReq, callOptions ...callopt.Option) (r *driver0.GetIncomeResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetIncome(ctx, req)
}

func (p *kDriverServiceClient) UpdateLocation(ctx context.Context, req *driver0.UpdateLocationReq, callOptions ...callopt.Option) (r *driver0.UpdateLocationResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateLocation(ctx, req)
}
