// Code generated by Kitex v0.14.1. DO NOT EDIT.

package driverservice

import (
	driver "cart/kitex_gen/cart/driver"
	driver0 "cart/kitex_gen/cart/driver"
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"DriverPetition": kitex.NewMethodInfo(
		driverPetitionHandler,
		newDriverServiceDriverPetitionArgs,
		newDriverServiceDriverPetitionResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"CheckStatus": kitex.NewMethodInfo(
		checkStatusHandler,
		newDriverServiceCheckStatusArgs,
		newDriverServiceCheckStatusResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"DriverLogin": kitex.NewMethodInfo(
		driverLoginHandler,
		newDriverServiceDriverLoginArgs,
		newDriverServiceDriverLoginResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetDriverInfo": kitex.NewMethodInfo(
		getDriverInfoHandler,
		newDriverServiceGetDriverInfoArgs,
		newDriverServiceGetDriverInfoResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"UpdateDriverInfo": kitex.NewMethodInfo(
		updateDriverInfoHandler,
		newDriverServiceUpdateDriverInfoArgs,
		newDriverServiceUpdateDriverInfoResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ChangeStatus": kitex.NewMethodInfo(
		changeStatusHandler,
		newDriverServiceChangeStatusArgs,
		newDriverServiceChangeStatusResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetPendingOrders": kitex.NewMethodInfo(
		getPendingOrdersHandler,
		newDriverServiceGetPendingOrdersArgs,
		newDriverServiceGetPendingOrdersResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"AcceptOrder": kitex.NewMethodInfo(
		acceptOrderHandler,
		newDriverServiceAcceptOrderArgs,
		newDriverServiceAcceptOrderResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"StartTrip": kitex.NewMethodInfo(
		startTripHandler,
		newDriverServiceStartTripArgs,
		newDriverServiceStartTripResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"CompleteOrder": kitex.NewMethodInfo(
		completeOrderHandler,
		newDriverServiceCompleteOrderArgs,
		newDriverServiceCompleteOrderResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"CancelOrder": kitex.NewMethodInfo(
		cancelOrderHandler,
		newDriverServiceCancelOrderArgs,
		newDriverServiceCancelOrderResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetIncome": kitex.NewMethodInfo(
		getIncomeHandler,
		newDriverServiceGetIncomeArgs,
		newDriverServiceGetIncomeResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"UpdateLocation": kitex.NewMethodInfo(
		updateLocationHandler,
		newDriverServiceUpdateLocationArgs,
		newDriverServiceUpdateLocationResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	driverServiceServiceInfo                = NewServiceInfo()
	driverServiceServiceInfoForClient       = NewServiceInfoForClient()
	driverServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return driverServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return driverServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return driverServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "DriverService"
	handlerType := (*driver.DriverService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "driver",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.14.1",
		Extra:           extra,
	}
	return svcInfo
}

func driverPetitionHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*driver.DriverServiceDriverPetitionArgs)
	realResult := result.(*driver.DriverServiceDriverPetitionResult)
	success, err := handler.(driver.DriverService).DriverPetition(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newDriverServiceDriverPetitionArgs() interface{} {
	return driver.NewDriverServiceDriverPetitionArgs()
}

func newDriverServiceDriverPetitionResult() interface{} {
	return driver.NewDriverServiceDriverPetitionResult()
}

func checkStatusHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*driver.DriverServiceCheckStatusArgs)
	realResult := result.(*driver.DriverServiceCheckStatusResult)
	success, err := handler.(driver.DriverService).CheckStatus(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newDriverServiceCheckStatusArgs() interface{} {
	return driver.NewDriverServiceCheckStatusArgs()
}

func newDriverServiceCheckStatusResult() interface{} {
	return driver.NewDriverServiceCheckStatusResult()
}

func driverLoginHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*driver.DriverServiceDriverLoginArgs)
	realResult := result.(*driver.DriverServiceDriverLoginResult)
	success, err := handler.(driver.DriverService).DriverLogin(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newDriverServiceDriverLoginArgs() interface{} {
	return driver.NewDriverServiceDriverLoginArgs()
}

func newDriverServiceDriverLoginResult() interface{} {
	return driver.NewDriverServiceDriverLoginResult()
}

func getDriverInfoHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*driver.DriverServiceGetDriverInfoArgs)
	realResult := result.(*driver.DriverServiceGetDriverInfoResult)
	success, err := handler.(driver.DriverService).GetDriverInfo(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newDriverServiceGetDriverInfoArgs() interface{} {
	return driver.NewDriverServiceGetDriverInfoArgs()
}

func newDriverServiceGetDriverInfoResult() interface{} {
	return driver.NewDriverServiceGetDriverInfoResult()
}

func updateDriverInfoHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*driver.DriverServiceUpdateDriverInfoArgs)
	realResult := result.(*driver.DriverServiceUpdateDriverInfoResult)
	success, err := handler.(driver.DriverService).UpdateDriverInfo(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newDriverServiceUpdateDriverInfoArgs() interface{} {
	return driver.NewDriverServiceUpdateDriverInfoArgs()
}

func newDriverServiceUpdateDriverInfoResult() interface{} {
	return driver.NewDriverServiceUpdateDriverInfoResult()
}

func changeStatusHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*driver.DriverServiceChangeStatusArgs)
	realResult := result.(*driver.DriverServiceChangeStatusResult)
	success, err := handler.(driver.DriverService).ChangeStatus(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newDriverServiceChangeStatusArgs() interface{} {
	return driver.NewDriverServiceChangeStatusArgs()
}

func newDriverServiceChangeStatusResult() interface{} {
	return driver.NewDriverServiceChangeStatusResult()
}

func getPendingOrdersHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*driver.DriverServiceGetPendingOrdersArgs)
	realResult := result.(*driver.DriverServiceGetPendingOrdersResult)
	success, err := handler.(driver.DriverService).GetPendingOrders(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newDriverServiceGetPendingOrdersArgs() interface{} {
	return driver.NewDriverServiceGetPendingOrdersArgs()
}

func newDriverServiceGetPendingOrdersResult() interface{} {
	return driver.NewDriverServiceGetPendingOrdersResult()
}

func acceptOrderHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*driver.DriverServiceAcceptOrderArgs)
	realResult := result.(*driver.DriverServiceAcceptOrderResult)
	success, err := handler.(driver.DriverService).AcceptOrder(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newDriverServiceAcceptOrderArgs() interface{} {
	return driver.NewDriverServiceAcceptOrderArgs()
}

func newDriverServiceAcceptOrderResult() interface{} {
	return driver.NewDriverServiceAcceptOrderResult()
}

func startTripHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*driver.DriverServiceStartTripArgs)
	realResult := result.(*driver.DriverServiceStartTripResult)
	success, err := handler.(driver.DriverService).StartTrip(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newDriverServiceStartTripArgs() interface{} {
	return driver.NewDriverServiceStartTripArgs()
}

func newDriverServiceStartTripResult() interface{} {
	return driver.NewDriverServiceStartTripResult()
}

func completeOrderHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*driver.DriverServiceCompleteOrderArgs)
	realResult := result.(*driver.DriverServiceCompleteOrderResult)
	success, err := handler.(driver.DriverService).CompleteOrder(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newDriverServiceCompleteOrderArgs() interface{} {
	return driver.NewDriverServiceCompleteOrderArgs()
}

func newDriverServiceCompleteOrderResult() interface{} {
	return driver.NewDriverServiceCompleteOrderResult()
}

func cancelOrderHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*driver.DriverServiceCancelOrderArgs)
	realResult := result.(*driver.DriverServiceCancelOrderResult)
	success, err := handler.(driver.DriverService).CancelOrder(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newDriverServiceCancelOrderArgs() interface{} {
	return driver.NewDriverServiceCancelOrderArgs()
}

func newDriverServiceCancelOrderResult() interface{} {
	return driver.NewDriverServiceCancelOrderResult()
}

func getIncomeHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*driver.DriverServiceGetIncomeArgs)
	realResult := result.(*driver.DriverServiceGetIncomeResult)
	success, err := handler.(driver.DriverService).GetIncome(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newDriverServiceGetIncomeArgs() interface{} {
	return driver.NewDriverServiceGetIncomeArgs()
}

func newDriverServiceGetIncomeResult() interface{} {
	return driver.NewDriverServiceGetIncomeResult()
}

func updateLocationHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*driver.DriverServiceUpdateLocationArgs)
	realResult := result.(*driver.DriverServiceUpdateLocationResult)
	success, err := handler.(driver.DriverService).UpdateLocation(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newDriverServiceUpdateLocationArgs() interface{} {
	return driver.NewDriverServiceUpdateLocationArgs()
}

func newDriverServiceUpdateLocationResult() interface{} {
	return driver.NewDriverServiceUpdateLocationResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) DriverPetition(ctx context.Context, req *driver0.DriverPetitionReq) (r *driver0.DriverPetitionResp, err error) {
	var _args driver.DriverServiceDriverPetitionArgs
	_args.Req = req
	var _result driver.DriverServiceDriverPetitionResult
	if err = p.c.Call(ctx, "DriverPetition", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CheckStatus(ctx context.Context, req *driver0.CheckStatusReq) (r *driver0.CheckStatusResp, err error) {
	var _args driver.DriverServiceCheckStatusArgs
	_args.Req = req
	var _result driver.DriverServiceCheckStatusResult
	if err = p.c.Call(ctx, "CheckStatus", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DriverLogin(ctx context.Context, req *driver0.DriverLoginReq) (r *driver0.DriverLoginResp, err error) {
	var _args driver.DriverServiceDriverLoginArgs
	_args.Req = req
	var _result driver.DriverServiceDriverLoginResult
	if err = p.c.Call(ctx, "DriverLogin", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetDriverInfo(ctx context.Context, req *driver0.GetDriverInfoReq) (r *driver0.GetDriverInfoResp, err error) {
	var _args driver.DriverServiceGetDriverInfoArgs
	_args.Req = req
	var _result driver.DriverServiceGetDriverInfoResult
	if err = p.c.Call(ctx, "GetDriverInfo", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpdateDriverInfo(ctx context.Context, req *driver0.UpdateDriverInfoReq) (r *driver0.UpdateDriverInfoResp, err error) {
	var _args driver.DriverServiceUpdateDriverInfoArgs
	_args.Req = req
	var _result driver.DriverServiceUpdateDriverInfoResult
	if err = p.c.Call(ctx, "UpdateDriverInfo", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ChangeStatus(ctx context.Context, req *driver0.ChangeStatusReq) (r *driver0.ChangeStatusResp, err error) {
	var _args driver.DriverServiceChangeStatusArgs
	_args.Req = req
	var _result driver.DriverServiceChangeStatusResult
	if err = p.c.Call(ctx, "ChangeStatus", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetPendingOrders(ctx context.Context, req *driver0.GetPendingOrdersReq) (r *driver0.GetPendingOrdersResp, err error) {
	var _args driver.DriverServiceGetPendingOrdersArgs
	_args.Req = req
	var _result driver.DriverServiceGetPendingOrdersResult
	if err = p.c.Call(ctx, "GetPendingOrders", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) AcceptOrder(ctx context.Context, req *driver0.AcceptOrderReq) (r *driver0.AcceptOrderResp, err error) {
	var _args driver.DriverServiceAcceptOrderArgs
	_args.Req = req
	var _result driver.DriverServiceAcceptOrderResult
	if err = p.c.Call(ctx, "AcceptOrder", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) StartTrip(ctx context.Context, req *driver0.StartTripReq) (r *driver0.StartTripResp, err error) {
	var _args driver.DriverServiceStartTripArgs
	_args.Req = req
	var _result driver.DriverServiceStartTripResult
	if err = p.c.Call(ctx, "StartTrip", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CompleteOrder(ctx context.Context, req *driver0.CompleteOrderReq) (r *driver0.CompleteOrderResp, err error) {
	var _args driver.DriverServiceCompleteOrderArgs
	_args.Req = req
	var _result driver.DriverServiceCompleteOrderResult
	if err = p.c.Call(ctx, "CompleteOrder", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CancelOrder(ctx context.Context, req *driver0.CancelOrderReq) (r *driver0.CancelOrderResp, err error) {
	var _args driver.DriverServiceCancelOrderArgs
	_args.Req = req
	var _result driver.DriverServiceCancelOrderResult
	if err = p.c.Call(ctx, "CancelOrder", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetIncome(ctx context.Context, req *driver0.GetIncomeReq) (r *driver0.GetIncomeResp, err error) {
	var _args driver.DriverServiceGetIncomeArgs
	_args.Req = req
	var _result driver.DriverServiceGetIncomeResult
	if err = p.c.Call(ctx, "GetIncome", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpdateLocation(ctx context.Context, req *driver0.UpdateLocationReq) (r *driver0.UpdateLocationResp, err error) {
	var _args driver.DriverServiceUpdateLocationArgs
	_args.Req = req
	var _result driver.DriverServiceUpdateLocationResult
	if err = p.c.Call(ctx, "UpdateLocation", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
