// Code generated by Kitex v0.14.1. DO NOT EDIT.

package home

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	home "kitex_main/kitex_gen/Ride_hailing_platform/home"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	CreateHistoricalSearch(ctx context.Context, req *home.CreateHistoricalSearchReq, callOptions ...callopt.Option) (r *home.CreateHistoricalSearchResp, err error)
	HistoricalSearchList(ctx context.Context, req *home.HistoricalSearchListReq, callOptions ...callopt.Option) (r *home.HistoricalSearchListResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kHomeClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kHomeClient struct {
	*kClient
}

func (p *kHomeClient) CreateHistoricalSearch(ctx context.Context, req *home.CreateHistoricalSearchReq, callOptions ...callopt.Option) (r *home.CreateHistoricalSearchResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateHistoricalSearch(ctx, req)
}

func (p *kHomeClient) HistoricalSearchList(ctx context.Context, req *home.HistoricalSearchListReq, callOptions ...callopt.Option) (r *home.HistoricalSearchListResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.HistoricalSearchList(ctx, req)
}
