// Code generated by Kitex v0.14.1. DO NOT EDIT.
package home

import (
	server "github.com/cloudwego/kitex/server"
	home "kitex_main/kitex_gen/Ride_hailing_platform/home"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler home.Home, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)
	options = append(options, server.WithCompatibleMiddlewareForUnary())

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}

func RegisterService(svr server.Server, handler home.Home, opts ...server.RegisterOption) error {
	return svr.RegisterService(serviceInfo(), handler, opts...)
}
