// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	"kitex_main/gateway/biz/router"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	//r.GET("/ping", handler.Ping)
	router.SetUserRouter(r)
	router.SetHomeRouter(r)
	router.SetRideRouter(r)
	// your code ...
}
