// Code generated by Kitex v0.14.1. DO NOT EDIT.

package driverserver

import (
	driver "Ride_hailing_platform/kitex_gen/driver"
	driver0 "Ride_hailing_platform/kitex_gen/driver"
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"SendSms": kitex.NewMethodInfo(
		sendSmsHandler,
		newDriverServerSendSmsArgs,
		newDriverServerSendSmsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Register": kitex.NewMethodInfo(
		registerHandler,
		newDriverServerRegisterArgs,
		newDriverServerRegisterResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetDriverInfo": kitex.NewMethodInfo(
		getDriverInfoHandler,
		newDriverServerGetDriverInfoArgs,
		newDriverServerGetDriverInfoResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"UpdateDriverStatus": kitex.NewMethodInfo(
		updateDriverStatusHandler,
		newDriverServerUpdateDriverStatusArgs,
		newDriverServerUpdateDriverStatusResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetAwaitOrder": kitex.NewMethodInfo(
		getAwaitOrderHandler,
		newDriverServerGetAwaitOrderArgs,
		newDriverServerGetAwaitOrderResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"AccessOrder": kitex.NewMethodInfo(
		accessOrderHandler,
		newDriverServerAccessOrderArgs,
		newDriverServerAccessOrderResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"RejectionOrder": kitex.NewMethodInfo(
		rejectionOrderHandler,
		newDriverServerRejectionOrderArgs,
		newDriverServerRejectionOrderResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ArriveLocation": kitex.NewMethodInfo(
		arriveLocationHandler,
		newDriverServerArriveLocationArgs,
		newDriverServerArriveLocationResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"StartTrip": kitex.NewMethodInfo(
		startTripHandler,
		newDriverServerStartTripArgs,
		newDriverServerStartTripResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"EndTrip": kitex.NewMethodInfo(
		endTripHandler,
		newDriverServerEndTripArgs,
		newDriverServerEndTripResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	driverServerServiceInfo                = NewServiceInfo()
	driverServerServiceInfoForClient       = NewServiceInfoForClient()
	driverServerServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return driverServerServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return driverServerServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return driverServerServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "DriverServer"
	handlerType := (*driver.DriverServer)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "driver",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.14.1",
		Extra:           extra,
	}
	return svcInfo
}

func sendSmsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*driver.DriverServerSendSmsArgs)
	realResult := result.(*driver.DriverServerSendSmsResult)
	success, err := handler.(driver.DriverServer).SendSms(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newDriverServerSendSmsArgs() interface{} {
	return driver.NewDriverServerSendSmsArgs()
}

func newDriverServerSendSmsResult() interface{} {
	return driver.NewDriverServerSendSmsResult()
}

func registerHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*driver.DriverServerRegisterArgs)
	realResult := result.(*driver.DriverServerRegisterResult)
	success, err := handler.(driver.DriverServer).Register(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newDriverServerRegisterArgs() interface{} {
	return driver.NewDriverServerRegisterArgs()
}

func newDriverServerRegisterResult() interface{} {
	return driver.NewDriverServerRegisterResult()
}

func getDriverInfoHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*driver.DriverServerGetDriverInfoArgs)
	realResult := result.(*driver.DriverServerGetDriverInfoResult)
	success, err := handler.(driver.DriverServer).GetDriverInfo(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newDriverServerGetDriverInfoArgs() interface{} {
	return driver.NewDriverServerGetDriverInfoArgs()
}

func newDriverServerGetDriverInfoResult() interface{} {
	return driver.NewDriverServerGetDriverInfoResult()
}

func updateDriverStatusHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*driver.DriverServerUpdateDriverStatusArgs)
	realResult := result.(*driver.DriverServerUpdateDriverStatusResult)
	success, err := handler.(driver.DriverServer).UpdateDriverStatus(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newDriverServerUpdateDriverStatusArgs() interface{} {
	return driver.NewDriverServerUpdateDriverStatusArgs()
}

func newDriverServerUpdateDriverStatusResult() interface{} {
	return driver.NewDriverServerUpdateDriverStatusResult()
}

func getAwaitOrderHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*driver.DriverServerGetAwaitOrderArgs)
	realResult := result.(*driver.DriverServerGetAwaitOrderResult)
	success, err := handler.(driver.DriverServer).GetAwaitOrder(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newDriverServerGetAwaitOrderArgs() interface{} {
	return driver.NewDriverServerGetAwaitOrderArgs()
}

func newDriverServerGetAwaitOrderResult() interface{} {
	return driver.NewDriverServerGetAwaitOrderResult()
}

func accessOrderHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*driver.DriverServerAccessOrderArgs)
	realResult := result.(*driver.DriverServerAccessOrderResult)
	success, err := handler.(driver.DriverServer).AccessOrder(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newDriverServerAccessOrderArgs() interface{} {
	return driver.NewDriverServerAccessOrderArgs()
}

func newDriverServerAccessOrderResult() interface{} {
	return driver.NewDriverServerAccessOrderResult()
}

func rejectionOrderHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*driver.DriverServerRejectionOrderArgs)
	realResult := result.(*driver.DriverServerRejectionOrderResult)
	success, err := handler.(driver.DriverServer).RejectionOrder(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newDriverServerRejectionOrderArgs() interface{} {
	return driver.NewDriverServerRejectionOrderArgs()
}

func newDriverServerRejectionOrderResult() interface{} {
	return driver.NewDriverServerRejectionOrderResult()
}

func arriveLocationHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*driver.DriverServerArriveLocationArgs)
	realResult := result.(*driver.DriverServerArriveLocationResult)
	success, err := handler.(driver.DriverServer).ArriveLocation(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newDriverServerArriveLocationArgs() interface{} {
	return driver.NewDriverServerArriveLocationArgs()
}

func newDriverServerArriveLocationResult() interface{} {
	return driver.NewDriverServerArriveLocationResult()
}

func startTripHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*driver.DriverServerStartTripArgs)
	realResult := result.(*driver.DriverServerStartTripResult)
	success, err := handler.(driver.DriverServer).StartTrip(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newDriverServerStartTripArgs() interface{} {
	return driver.NewDriverServerStartTripArgs()
}

func newDriverServerStartTripResult() interface{} {
	return driver.NewDriverServerStartTripResult()
}

func endTripHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*driver.DriverServerEndTripArgs)
	realResult := result.(*driver.DriverServerEndTripResult)
	success, err := handler.(driver.DriverServer).EndTrip(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newDriverServerEndTripArgs() interface{} {
	return driver.NewDriverServerEndTripArgs()
}

func newDriverServerEndTripResult() interface{} {
	return driver.NewDriverServerEndTripResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) SendSms(ctx context.Context, req *driver0.SendSmsDriverReq) (r *driver0.SendSmsDriverResp, err error) {
	var _args driver.DriverServerSendSmsArgs
	_args.Req = req
	var _result driver.DriverServerSendSmsResult
	if err = p.c.Call(ctx, "SendSms", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Register(ctx context.Context, req *driver0.DriverRegisterReq) (r *driver0.DriverRegisterResp, err error) {
	var _args driver.DriverServerRegisterArgs
	_args.Req = req
	var _result driver.DriverServerRegisterResult
	if err = p.c.Call(ctx, "Register", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetDriverInfo(ctx context.Context, req *driver0.GetDriverInfoReq) (r *driver0.GetDriverInfoResp, err error) {
	var _args driver.DriverServerGetDriverInfoArgs
	_args.Req = req
	var _result driver.DriverServerGetDriverInfoResult
	if err = p.c.Call(ctx, "GetDriverInfo", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpdateDriverStatus(ctx context.Context, req *driver0.UpdateDriverStatusReq) (r *driver0.UpdateDriverStatusResp, err error) {
	var _args driver.DriverServerUpdateDriverStatusArgs
	_args.Req = req
	var _result driver.DriverServerUpdateDriverStatusResult
	if err = p.c.Call(ctx, "UpdateDriverStatus", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetAwaitOrder(ctx context.Context, req *driver0.GetAwaitOrderReq) (r *driver0.GetAwaitOrderResp, err error) {
	var _args driver.DriverServerGetAwaitOrderArgs
	_args.Req = req
	var _result driver.DriverServerGetAwaitOrderResult
	if err = p.c.Call(ctx, "GetAwaitOrder", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) AccessOrder(ctx context.Context, req *driver0.AccessOrderReq) (r *driver0.AccessOrderResp, err error) {
	var _args driver.DriverServerAccessOrderArgs
	_args.Req = req
	var _result driver.DriverServerAccessOrderResult
	if err = p.c.Call(ctx, "AccessOrder", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) RejectionOrder(ctx context.Context, req *driver0.RejectionOrderReq) (r *driver0.RejectionOrderResp, err error) {
	var _args driver.DriverServerRejectionOrderArgs
	_args.Req = req
	var _result driver.DriverServerRejectionOrderResult
	if err = p.c.Call(ctx, "RejectionOrder", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ArriveLocation(ctx context.Context, req *driver0.ArriveLocationReq) (r *driver0.ArriveLocationResp, err error) {
	var _args driver.DriverServerArriveLocationArgs
	_args.Req = req
	var _result driver.DriverServerArriveLocationResult
	if err = p.c.Call(ctx, "ArriveLocation", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) StartTrip(ctx context.Context, req *driver0.StartTripReq) (r *driver0.StartTripResp, err error) {
	var _args driver.DriverServerStartTripArgs
	_args.Req = req
	var _result driver.DriverServerStartTripResult
	if err = p.c.Call(ctx, "StartTrip", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) EndTrip(ctx context.Context, req *driver0.EndTripReq) (r *driver0.EndTripResp, err error) {
	var _args driver.DriverServerEndTripArgs
	_args.Req = req
	var _result driver.DriverServerEndTripResult
	if err = p.c.Call(ctx, "EndTrip", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
