// Code generated by thriftgo (0.4.2). DO NOT EDIT.

package passengers

import (
	"context"
	"fmt"
)

type Passengers struct {
	Id       int32  `thrift:"Id,1" frugal:"1,default,i32" json:"Id"`
	Name     string `thrift:"Name,2" frugal:"2,default,string" json:"Name"`
	NickName string `thrift:"NickName,3" frugal:"3,default,string" json:"NickName"`
	FileId   int32  `thrift:"FileId,4" frugal:"4,default,i32" json:"FileId"`
	Mobile   string `thrift:"Mobile,5" frugal:"5,default,string" json:"Mobile"`
	Age      int32  `thrift:"Age,6" frugal:"6,default,i32" json:"Age"`
	Sex      string `thrift:"Sex,7" frugal:"7,default,string" json:"Sex"`
	Mileage  string `thrift:"Mileage,8" frugal:"8,default,string" json:"Mileage"`
}

func NewPassengers() *Passengers {
	return &Passengers{}
}

func (p *Passengers) InitDefault() {
}

func (p *Passengers) GetId() (v int32) {
	return p.Id
}

func (p *Passengers) GetName() (v string) {
	return p.Name
}

func (p *Passengers) GetNickName() (v string) {
	return p.NickName
}

func (p *Passengers) GetFileId() (v int32) {
	return p.FileId
}

func (p *Passengers) GetMobile() (v string) {
	return p.Mobile
}

func (p *Passengers) GetAge() (v int32) {
	return p.Age
}

func (p *Passengers) GetSex() (v string) {
	return p.Sex
}

func (p *Passengers) GetMileage() (v string) {
	return p.Mileage
}
func (p *Passengers) SetId(val int32) {
	p.Id = val
}
func (p *Passengers) SetName(val string) {
	p.Name = val
}
func (p *Passengers) SetNickName(val string) {
	p.NickName = val
}
func (p *Passengers) SetFileId(val int32) {
	p.FileId = val
}
func (p *Passengers) SetMobile(val string) {
	p.Mobile = val
}
func (p *Passengers) SetAge(val int32) {
	p.Age = val
}
func (p *Passengers) SetSex(val string) {
	p.Sex = val
}
func (p *Passengers) SetMileage(val string) {
	p.Mileage = val
}

func (p *Passengers) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Passengers(%+v)", *p)
}

var fieldIDToName_Passengers = map[int16]string{
	1: "Id",
	2: "Name",
	3: "NickName",
	4: "FileId",
	5: "Mobile",
	6: "Age",
	7: "Sex",
	8: "Mileage",
}

type SendSmsReq struct {
	Mobile string `thrift:"Mobile,1" frugal:"1,default,string" json:"Mobile"`
	Source string `thrift:"Source,2" frugal:"2,default,string" json:"Source"`
}

func NewSendSmsReq() *SendSmsReq {
	return &SendSmsReq{}
}

func (p *SendSmsReq) InitDefault() {
}

func (p *SendSmsReq) GetMobile() (v string) {
	return p.Mobile
}

func (p *SendSmsReq) GetSource() (v string) {
	return p.Source
}
func (p *SendSmsReq) SetMobile(val string) {
	p.Mobile = val
}
func (p *SendSmsReq) SetSource(val string) {
	p.Source = val
}

func (p *SendSmsReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SendSmsReq(%+v)", *p)
}

var fieldIDToName_SendSmsReq = map[int16]string{
	1: "Mobile",
	2: "Source",
}

type SendSmsResp struct {
	Message string `thrift:"Message,1" frugal:"1,default,string" json:"Message"`
	Code    int64  `thrift:"Code,2" frugal:"2,default,i64" json:"Code"`
}

func NewSendSmsResp() *SendSmsResp {
	return &SendSmsResp{}
}

func (p *SendSmsResp) InitDefault() {
}

func (p *SendSmsResp) GetMessage() (v string) {
	return p.Message
}

func (p *SendSmsResp) GetCode() (v int64) {
	return p.Code
}
func (p *SendSmsResp) SetMessage(val string) {
	p.Message = val
}
func (p *SendSmsResp) SetCode(val int64) {
	p.Code = val
}

func (p *SendSmsResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SendSmsResp(%+v)", *p)
}

var fieldIDToName_SendSmsResp = map[int16]string{
	1: "Message",
	2: "Code",
}

type RegisterReq struct {
	Mobile     string      `thrift:"Mobile,1" frugal:"1,default,string" json:"Mobile"`
	SmsCode    string      `thrift:"SmsCode,2" frugal:"2,default,string" json:"SmsCode"`
	Passengers *Passengers `thrift:"passengers,3" frugal:"3,default,Passengers" json:"passengers"`
}

func NewRegisterReq() *RegisterReq {
	return &RegisterReq{}
}

func (p *RegisterReq) InitDefault() {
}

func (p *RegisterReq) GetMobile() (v string) {
	return p.Mobile
}

func (p *RegisterReq) GetSmsCode() (v string) {
	return p.SmsCode
}

var RegisterReq_Passengers_DEFAULT *Passengers

func (p *RegisterReq) GetPassengers() (v *Passengers) {
	if !p.IsSetPassengers() {
		return RegisterReq_Passengers_DEFAULT
	}
	return p.Passengers
}
func (p *RegisterReq) SetMobile(val string) {
	p.Mobile = val
}
func (p *RegisterReq) SetSmsCode(val string) {
	p.SmsCode = val
}
func (p *RegisterReq) SetPassengers(val *Passengers) {
	p.Passengers = val
}

func (p *RegisterReq) IsSetPassengers() bool {
	return p.Passengers != nil
}

func (p *RegisterReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RegisterReq(%+v)", *p)
}

var fieldIDToName_RegisterReq = map[int16]string{
	1: "Mobile",
	2: "SmsCode",
	3: "passengers",
}

type RegisterResp struct {
	Message    string      `thrift:"Message,1" frugal:"1,default,string" json:"Message"`
	Code       int64       `thrift:"Code,2" frugal:"2,default,i64" json:"Code"`
	Passengers *Passengers `thrift:"passengers,3" frugal:"3,default,Passengers" json:"passengers"`
}

func NewRegisterResp() *RegisterResp {
	return &RegisterResp{}
}

func (p *RegisterResp) InitDefault() {
}

func (p *RegisterResp) GetMessage() (v string) {
	return p.Message
}

func (p *RegisterResp) GetCode() (v int64) {
	return p.Code
}

var RegisterResp_Passengers_DEFAULT *Passengers

func (p *RegisterResp) GetPassengers() (v *Passengers) {
	if !p.IsSetPassengers() {
		return RegisterResp_Passengers_DEFAULT
	}
	return p.Passengers
}
func (p *RegisterResp) SetMessage(val string) {
	p.Message = val
}
func (p *RegisterResp) SetCode(val int64) {
	p.Code = val
}
func (p *RegisterResp) SetPassengers(val *Passengers) {
	p.Passengers = val
}

func (p *RegisterResp) IsSetPassengers() bool {
	return p.Passengers != nil
}

func (p *RegisterResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RegisterResp(%+v)", *p)
}

var fieldIDToName_RegisterResp = map[int16]string{
	1: "Message",
	2: "Code",
	3: "passengers",
}

type LoginReq struct {
	Mobile  string `thrift:"Mobile,1" frugal:"1,default,string" json:"Mobile"`
	SmsCode string `thrift:"SmsCode,2" frugal:"2,default,string" json:"SmsCode"`
}

func NewLoginReq() *LoginReq {
	return &LoginReq{}
}

func (p *LoginReq) InitDefault() {
}

func (p *LoginReq) GetMobile() (v string) {
	return p.Mobile
}

func (p *LoginReq) GetSmsCode() (v string) {
	return p.SmsCode
}
func (p *LoginReq) SetMobile(val string) {
	p.Mobile = val
}
func (p *LoginReq) SetSmsCode(val string) {
	p.SmsCode = val
}

func (p *LoginReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LoginReq(%+v)", *p)
}

var fieldIDToName_LoginReq = map[int16]string{
	1: "Mobile",
	2: "SmsCode",
}

type LoginResp struct {
	Message    string      `thrift:"Message,1" frugal:"1,default,string" json:"Message"`
	Code       int64       `thrift:"Code,2" frugal:"2,default,i64" json:"Code"`
	Passengers *Passengers `thrift:"passengers,3" frugal:"3,default,Passengers" json:"passengers"`
	Token      string      `thrift:"Token,4" frugal:"4,default,string" json:"Token"`
}

func NewLoginResp() *LoginResp {
	return &LoginResp{}
}

func (p *LoginResp) InitDefault() {
}

func (p *LoginResp) GetMessage() (v string) {
	return p.Message
}

func (p *LoginResp) GetCode() (v int64) {
	return p.Code
}

var LoginResp_Passengers_DEFAULT *Passengers

func (p *LoginResp) GetPassengers() (v *Passengers) {
	if !p.IsSetPassengers() {
		return LoginResp_Passengers_DEFAULT
	}
	return p.Passengers
}

func (p *LoginResp) GetToken() (v string) {
	return p.Token
}
func (p *LoginResp) SetMessage(val string) {
	p.Message = val
}
func (p *LoginResp) SetCode(val int64) {
	p.Code = val
}
func (p *LoginResp) SetPassengers(val *Passengers) {
	p.Passengers = val
}
func (p *LoginResp) SetToken(val string) {
	p.Token = val
}

func (p *LoginResp) IsSetPassengers() bool {
	return p.Passengers != nil
}

func (p *LoginResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LoginResp(%+v)", *p)
}

var fieldIDToName_LoginResp = map[int16]string{
	1: "Message",
	2: "Code",
	3: "passengers",
	4: "Token",
}

type LocationReq struct {
	PassengerID string `thrift:"PassengerID,1" frugal:"1,default,string" json:"PassengerID"`
}

func NewLocationReq() *LocationReq {
	return &LocationReq{}
}

func (p *LocationReq) InitDefault() {
}

func (p *LocationReq) GetPassengerID() (v string) {
	return p.PassengerID
}
func (p *LocationReq) SetPassengerID(val string) {
	p.PassengerID = val
}

func (p *LocationReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LocationReq(%+v)", *p)
}

var fieldIDToName_LocationReq = map[int16]string{
	1: "PassengerID",
}

type LocationResp struct {
	Message string  `thrift:"Message,1" frugal:"1,default,string" json:"Message"`
	Code    int16   `thrift:"Code,2" frugal:"2,default,i16" json:"Code"`
	Lat     float64 `thrift:"Lat,3" frugal:"3,default,double" json:"Lat"`
	Lng     float64 `thrift:"Lng,4" frugal:"4,default,double" json:"Lng"`
}

func NewLocationResp() *LocationResp {
	return &LocationResp{}
}

func (p *LocationResp) InitDefault() {
}

func (p *LocationResp) GetMessage() (v string) {
	return p.Message
}

func (p *LocationResp) GetCode() (v int16) {
	return p.Code
}

func (p *LocationResp) GetLat() (v float64) {
	return p.Lat
}

func (p *LocationResp) GetLng() (v float64) {
	return p.Lng
}
func (p *LocationResp) SetMessage(val string) {
	p.Message = val
}
func (p *LocationResp) SetCode(val int16) {
	p.Code = val
}
func (p *LocationResp) SetLat(val float64) {
	p.Lat = val
}
func (p *LocationResp) SetLng(val float64) {
	p.Lng = val
}

func (p *LocationResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LocationResp(%+v)", *p)
}

var fieldIDToName_LocationResp = map[int16]string{
	1: "Message",
	2: "Code",
	3: "Lat",
	4: "Lng",
}

type TripReq struct {
	PassengerID string `thrift:"PassengerID,1" frugal:"1,default,string" json:"PassengerID"`
}

func NewTripReq() *TripReq {
	return &TripReq{}
}

func (p *TripReq) InitDefault() {
}

func (p *TripReq) GetPassengerID() (v string) {
	return p.PassengerID
}
func (p *TripReq) SetPassengerID(val string) {
	p.PassengerID = val
}

func (p *TripReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TripReq(%+v)", *p)
}

var fieldIDToName_TripReq = map[int16]string{
	1: "PassengerID",
}

type TripResp struct {
	Message               string   `thrift:"Message,1" frugal:"1,default,string" json:"Message"`
	Code                  int16    `thrift:"Code,2" frugal:"2,default,i16" json:"Code"`
	HistoryTrips          []string `thrift:"HistoryTrips,3" frugal:"3,default,list<string>" json:"HistoryTrips"`
	RecommendDestinations []string `thrift:"RecommendDestinations,4" frugal:"4,default,list<string>" json:"RecommendDestinations"`
}

func NewTripResp() *TripResp {
	return &TripResp{}
}

func (p *TripResp) InitDefault() {
}

func (p *TripResp) GetMessage() (v string) {
	return p.Message
}

func (p *TripResp) GetCode() (v int16) {
	return p.Code
}

func (p *TripResp) GetHistoryTrips() (v []string) {
	return p.HistoryTrips
}

func (p *TripResp) GetRecommendDestinations() (v []string) {
	return p.RecommendDestinations
}
func (p *TripResp) SetMessage(val string) {
	p.Message = val
}
func (p *TripResp) SetCode(val int16) {
	p.Code = val
}
func (p *TripResp) SetHistoryTrips(val []string) {
	p.HistoryTrips = val
}
func (p *TripResp) SetRecommendDestinations(val []string) {
	p.RecommendDestinations = val
}

func (p *TripResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TripResp(%+v)", *p)
}

var fieldIDToName_TripResp = map[int16]string{
	1: "Message",
	2: "Code",
	3: "HistoryTrips",
	4: "RecommendDestinations",
}

type PricingReq struct {
	StartLocation string `thrift:"StartLocation,1" frugal:"1,default,string" json:"StartLocation"`
	EndLocation   string `thrift:"EndLocation,2" frugal:"2,default,string" json:"EndLocation"`
	CarType       string `thrift:"CarType,3" frugal:"3,default,string" json:"CarType"`
}

func NewPricingReq() *PricingReq {
	return &PricingReq{}
}

func (p *PricingReq) InitDefault() {
}

func (p *PricingReq) GetStartLocation() (v string) {
	return p.StartLocation
}

func (p *PricingReq) GetEndLocation() (v string) {
	return p.EndLocation
}

func (p *PricingReq) GetCarType() (v string) {
	return p.CarType
}
func (p *PricingReq) SetStartLocation(val string) {
	p.StartLocation = val
}
func (p *PricingReq) SetEndLocation(val string) {
	p.EndLocation = val
}
func (p *PricingReq) SetCarType(val string) {
	p.CarType = val
}

func (p *PricingReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PricingReq(%+v)", *p)
}

var fieldIDToName_PricingReq = map[int16]string{
	1: "StartLocation",
	2: "EndLocation",
	3: "CarType",
}

type PricingResp struct {
	Message string  `thrift:"Message,1" frugal:"1,default,string" json:"Message"`
	Code    int16   `thrift:"Code,2" frugal:"2,default,i16" json:"Code"`
	Price   float64 `thrift:"Price,3" frugal:"3,default,double" json:"Price"`
}

func NewPricingResp() *PricingResp {
	return &PricingResp{}
}

func (p *PricingResp) InitDefault() {
}

func (p *PricingResp) GetMessage() (v string) {
	return p.Message
}

func (p *PricingResp) GetCode() (v int16) {
	return p.Code
}

func (p *PricingResp) GetPrice() (v float64) {
	return p.Price
}
func (p *PricingResp) SetMessage(val string) {
	p.Message = val
}
func (p *PricingResp) SetCode(val int16) {
	p.Code = val
}
func (p *PricingResp) SetPrice(val float64) {
	p.Price = val
}

func (p *PricingResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PricingResp(%+v)", *p)
}

var fieldIDToName_PricingResp = map[int16]string{
	1: "Message",
	2: "Code",
	3: "Price",
}

type OrderReq struct {
	PassengerID   string `thrift:"PassengerID,1" frugal:"1,default,string" json:"PassengerID"`
	StartLocation string `thrift:"StartLocation,2" frugal:"2,default,string" json:"StartLocation"`
	EndLocation   string `thrift:"EndLocation,3" frugal:"3,default,string" json:"EndLocation"`
	CarType       string `thrift:"CarType,4" frugal:"4,default,string" json:"CarType"`
	OrderType     int8   `thrift:"OrderType,5" frugal:"5,default,i8" json:"OrderType"`
}

func NewOrderReq() *OrderReq {
	return &OrderReq{}
}

func (p *OrderReq) InitDefault() {
}

func (p *OrderReq) GetPassengerID() (v string) {
	return p.PassengerID
}

func (p *OrderReq) GetStartLocation() (v string) {
	return p.StartLocation
}

func (p *OrderReq) GetEndLocation() (v string) {
	return p.EndLocation
}

func (p *OrderReq) GetCarType() (v string) {
	return p.CarType
}

func (p *OrderReq) GetOrderType() (v int8) {
	return p.OrderType
}
func (p *OrderReq) SetPassengerID(val string) {
	p.PassengerID = val
}
func (p *OrderReq) SetStartLocation(val string) {
	p.StartLocation = val
}
func (p *OrderReq) SetEndLocation(val string) {
	p.EndLocation = val
}
func (p *OrderReq) SetCarType(val string) {
	p.CarType = val
}
func (p *OrderReq) SetOrderType(val int8) {
	p.OrderType = val
}

func (p *OrderReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderReq(%+v)", *p)
}

var fieldIDToName_OrderReq = map[int16]string{
	1: "PassengerID",
	2: "StartLocation",
	3: "EndLocation",
	4: "CarType",
	5: "OrderType",
}

type OrderResp struct {
	Message string `thrift:"Message,1" frugal:"1,default,string" json:"Message"`
	Code    int16  `thrift:"Code,2" frugal:"2,default,i16" json:"Code"`
	OrderID string `thrift:"OrderID,3" frugal:"3,default,string" json:"OrderID"`
}

func NewOrderResp() *OrderResp {
	return &OrderResp{}
}

func (p *OrderResp) InitDefault() {
}

func (p *OrderResp) GetMessage() (v string) {
	return p.Message
}

func (p *OrderResp) GetCode() (v int16) {
	return p.Code
}

func (p *OrderResp) GetOrderID() (v string) {
	return p.OrderID
}
func (p *OrderResp) SetMessage(val string) {
	p.Message = val
}
func (p *OrderResp) SetCode(val int16) {
	p.Code = val
}
func (p *OrderResp) SetOrderID(val string) {
	p.OrderID = val
}

func (p *OrderResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderResp(%+v)", *p)
}

var fieldIDToName_OrderResp = map[int16]string{
	1: "Message",
	2: "Code",
	3: "OrderID",
}

type RoutePlanReq struct {
	StartLat float64 `thrift:"StartLat,1" frugal:"1,default,double" json:"StartLat"`
	StartLng float64 `thrift:"StartLng,2" frugal:"2,default,double" json:"StartLng"`
	EndLat   float64 `thrift:"EndLat,3" frugal:"3,default,double" json:"EndLat"`
	EndLng   float64 `thrift:"EndLng,4" frugal:"4,default,double" json:"EndLng"`
	CarType  string  `thrift:"CarType,5" frugal:"5,default,string" json:"CarType"`
}

func NewRoutePlanReq() *RoutePlanReq {
	return &RoutePlanReq{}
}

func (p *RoutePlanReq) InitDefault() {
}

func (p *RoutePlanReq) GetStartLat() (v float64) {
	return p.StartLat
}

func (p *RoutePlanReq) GetStartLng() (v float64) {
	return p.StartLng
}

func (p *RoutePlanReq) GetEndLat() (v float64) {
	return p.EndLat
}

func (p *RoutePlanReq) GetEndLng() (v float64) {
	return p.EndLng
}

func (p *RoutePlanReq) GetCarType() (v string) {
	return p.CarType
}
func (p *RoutePlanReq) SetStartLat(val float64) {
	p.StartLat = val
}
func (p *RoutePlanReq) SetStartLng(val float64) {
	p.StartLng = val
}
func (p *RoutePlanReq) SetEndLat(val float64) {
	p.EndLat = val
}
func (p *RoutePlanReq) SetEndLng(val float64) {
	p.EndLng = val
}
func (p *RoutePlanReq) SetCarType(val string) {
	p.CarType = val
}

func (p *RoutePlanReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RoutePlanReq(%+v)", *p)
}

var fieldIDToName_RoutePlanReq = map[int16]string{
	1: "StartLat",
	2: "StartLng",
	3: "EndLat",
	4: "EndLng",
	5: "CarType",
}

type RoutePlanResp struct {
	Message  string  `thrift:"Message,1" frugal:"1,default,string" json:"Message"`
	Code     int16   `thrift:"Code,2" frugal:"2,default,i16" json:"Code"`
	Distance int32   `thrift:"Distance,3" frugal:"3,default,i32" json:"Distance"`
	Duration int32   `thrift:"Duration,4" frugal:"4,default,i32" json:"Duration"`
	Price    float64 `thrift:"Price,5" frugal:"5,default,double" json:"Price"`
}

func NewRoutePlanResp() *RoutePlanResp {
	return &RoutePlanResp{}
}

func (p *RoutePlanResp) InitDefault() {
}

func (p *RoutePlanResp) GetMessage() (v string) {
	return p.Message
}

func (p *RoutePlanResp) GetCode() (v int16) {
	return p.Code
}

func (p *RoutePlanResp) GetDistance() (v int32) {
	return p.Distance
}

func (p *RoutePlanResp) GetDuration() (v int32) {
	return p.Duration
}

func (p *RoutePlanResp) GetPrice() (v float64) {
	return p.Price
}
func (p *RoutePlanResp) SetMessage(val string) {
	p.Message = val
}
func (p *RoutePlanResp) SetCode(val int16) {
	p.Code = val
}
func (p *RoutePlanResp) SetDistance(val int32) {
	p.Distance = val
}
func (p *RoutePlanResp) SetDuration(val int32) {
	p.Duration = val
}
func (p *RoutePlanResp) SetPrice(val float64) {
	p.Price = val
}

func (p *RoutePlanResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RoutePlanResp(%+v)", *p)
}

var fieldIDToName_RoutePlanResp = map[int16]string{
	1: "Message",
	2: "Code",
	3: "Distance",
	4: "Duration",
	5: "Price",
}

type WechatLoginReq struct {
	OpenID   int32  `thrift:"OpenID,1" frugal:"1,default,i32" json:"OpenID"`
	UnionID  int32  `thrift:"UnionID,2" frugal:"2,default,i32" json:"UnionID"`
	Nickname string `thrift:"Nickname,3" frugal:"3,default,string" json:"Nickname"`
	Avatar   string `thrift:"Avatar,4" frugal:"4,default,string" json:"Avatar"`
}

func NewWechatLoginReq() *WechatLoginReq {
	return &WechatLoginReq{}
}

func (p *WechatLoginReq) InitDefault() {
}

func (p *WechatLoginReq) GetOpenID() (v int32) {
	return p.OpenID
}

func (p *WechatLoginReq) GetUnionID() (v int32) {
	return p.UnionID
}

func (p *WechatLoginReq) GetNickname() (v string) {
	return p.Nickname
}

func (p *WechatLoginReq) GetAvatar() (v string) {
	return p.Avatar
}
func (p *WechatLoginReq) SetOpenID(val int32) {
	p.OpenID = val
}
func (p *WechatLoginReq) SetUnionID(val int32) {
	p.UnionID = val
}
func (p *WechatLoginReq) SetNickname(val string) {
	p.Nickname = val
}
func (p *WechatLoginReq) SetAvatar(val string) {
	p.Avatar = val
}

func (p *WechatLoginReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("WechatLoginReq(%+v)", *p)
}

var fieldIDToName_WechatLoginReq = map[int16]string{
	1: "OpenID",
	2: "UnionID",
	3: "Nickname",
	4: "Avatar",
}

type WechatLoginResp struct {
	Message    string      `thrift:"Message,1" frugal:"1,default,string" json:"Message"`
	Code       int64       `thrift:"Code,2" frugal:"2,default,i64" json:"Code"`
	Passengers *Passengers `thrift:"passengers,3" frugal:"3,default,Passengers" json:"passengers"`
	Token      string      `thrift:"Token,4" frugal:"4,default,string" json:"Token"`
}

func NewWechatLoginResp() *WechatLoginResp {
	return &WechatLoginResp{}
}

func (p *WechatLoginResp) InitDefault() {
}

func (p *WechatLoginResp) GetMessage() (v string) {
	return p.Message
}

func (p *WechatLoginResp) GetCode() (v int64) {
	return p.Code
}

var WechatLoginResp_Passengers_DEFAULT *Passengers

func (p *WechatLoginResp) GetPassengers() (v *Passengers) {
	if !p.IsSetPassengers() {
		return WechatLoginResp_Passengers_DEFAULT
	}
	return p.Passengers
}

func (p *WechatLoginResp) GetToken() (v string) {
	return p.Token
}
func (p *WechatLoginResp) SetMessage(val string) {
	p.Message = val
}
func (p *WechatLoginResp) SetCode(val int64) {
	p.Code = val
}
func (p *WechatLoginResp) SetPassengers(val *Passengers) {
	p.Passengers = val
}
func (p *WechatLoginResp) SetToken(val string) {
	p.Token = val
}

func (p *WechatLoginResp) IsSetPassengers() bool {
	return p.Passengers != nil
}

func (p *WechatLoginResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("WechatLoginResp(%+v)", *p)
}

var fieldIDToName_WechatLoginResp = map[int16]string{
	1: "Message",
	2: "Code",
	3: "passengers",
	4: "Token",
}

type BindWechatReq struct {
	UserID   int32  `thrift:"UserID,1" frugal:"1,default,i32" json:"UserID"`
	OpenID   int32  `thrift:"OpenID,2" frugal:"2,default,i32" json:"OpenID"`
	UnionID  int32  `thrift:"UnionID,3" frugal:"3,default,i32" json:"UnionID"`
	Nickname string `thrift:"Nickname,4" frugal:"4,default,string" json:"Nickname"`
	Avatar   string `thrift:"Avatar,5" frugal:"5,default,string" json:"Avatar"`
}

func NewBindWechatReq() *BindWechatReq {
	return &BindWechatReq{}
}

func (p *BindWechatReq) InitDefault() {
}

func (p *BindWechatReq) GetUserID() (v int32) {
	return p.UserID
}

func (p *BindWechatReq) GetOpenID() (v int32) {
	return p.OpenID
}

func (p *BindWechatReq) GetUnionID() (v int32) {
	return p.UnionID
}

func (p *BindWechatReq) GetNickname() (v string) {
	return p.Nickname
}

func (p *BindWechatReq) GetAvatar() (v string) {
	return p.Avatar
}
func (p *BindWechatReq) SetUserID(val int32) {
	p.UserID = val
}
func (p *BindWechatReq) SetOpenID(val int32) {
	p.OpenID = val
}
func (p *BindWechatReq) SetUnionID(val int32) {
	p.UnionID = val
}
func (p *BindWechatReq) SetNickname(val string) {
	p.Nickname = val
}
func (p *BindWechatReq) SetAvatar(val string) {
	p.Avatar = val
}

func (p *BindWechatReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BindWechatReq(%+v)", *p)
}

var fieldIDToName_BindWechatReq = map[int16]string{
	1: "UserID",
	2: "OpenID",
	3: "UnionID",
	4: "Nickname",
	5: "Avatar",
}

type BindWechatResp struct {
	Message    string      `thrift:"Message,1" frugal:"1,default,string" json:"Message"`
	Code       int64       `thrift:"Code,2" frugal:"2,default,i64" json:"Code"`
	Passengers *Passengers `thrift:"passengers,3" frugal:"3,default,Passengers" json:"passengers"`
}

func NewBindWechatResp() *BindWechatResp {
	return &BindWechatResp{}
}

func (p *BindWechatResp) InitDefault() {
}

func (p *BindWechatResp) GetMessage() (v string) {
	return p.Message
}

func (p *BindWechatResp) GetCode() (v int64) {
	return p.Code
}

var BindWechatResp_Passengers_DEFAULT *Passengers

func (p *BindWechatResp) GetPassengers() (v *Passengers) {
	if !p.IsSetPassengers() {
		return BindWechatResp_Passengers_DEFAULT
	}
	return p.Passengers
}
func (p *BindWechatResp) SetMessage(val string) {
	p.Message = val
}
func (p *BindWechatResp) SetCode(val int64) {
	p.Code = val
}
func (p *BindWechatResp) SetPassengers(val *Passengers) {
	p.Passengers = val
}

func (p *BindWechatResp) IsSetPassengers() bool {
	return p.Passengers != nil
}

func (p *BindWechatResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BindWechatResp(%+v)", *p)
}

var fieldIDToName_BindWechatResp = map[int16]string{
	1: "Message",
	2: "Code",
	3: "passengers",
}

type UnbindWechatReq struct {
	UserID int32 `thrift:"UserID,1" frugal:"1,default,i32" json:"UserID"`
}

func NewUnbindWechatReq() *UnbindWechatReq {
	return &UnbindWechatReq{}
}

func (p *UnbindWechatReq) InitDefault() {
}

func (p *UnbindWechatReq) GetUserID() (v int32) {
	return p.UserID
}
func (p *UnbindWechatReq) SetUserID(val int32) {
	p.UserID = val
}

func (p *UnbindWechatReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UnbindWechatReq(%+v)", *p)
}

var fieldIDToName_UnbindWechatReq = map[int16]string{
	1: "UserID",
}

type UnbindWechatResp struct {
	Message string `thrift:"Message,1" frugal:"1,default,string" json:"Message"`
	Code    int64  `thrift:"Code,2" frugal:"2,default,i64" json:"Code"`
}

func NewUnbindWechatResp() *UnbindWechatResp {
	return &UnbindWechatResp{}
}

func (p *UnbindWechatResp) InitDefault() {
}

func (p *UnbindWechatResp) GetMessage() (v string) {
	return p.Message
}

func (p *UnbindWechatResp) GetCode() (v int64) {
	return p.Code
}
func (p *UnbindWechatResp) SetMessage(val string) {
	p.Message = val
}
func (p *UnbindWechatResp) SetCode(val int64) {
	p.Code = val
}

func (p *UnbindWechatResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UnbindWechatResp(%+v)", *p)
}

var fieldIDToName_UnbindWechatResp = map[int16]string{
	1: "Message",
	2: "Code",
}

type GetUserInfoReq struct {
	UserID int32 `thrift:"UserID,1" frugal:"1,default,i32" json:"UserID"`
}

func NewGetUserInfoReq() *GetUserInfoReq {
	return &GetUserInfoReq{}
}

func (p *GetUserInfoReq) InitDefault() {
}

func (p *GetUserInfoReq) GetUserID() (v int32) {
	return p.UserID
}
func (p *GetUserInfoReq) SetUserID(val int32) {
	p.UserID = val
}

func (p *GetUserInfoReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetUserInfoReq(%+v)", *p)
}

var fieldIDToName_GetUserInfoReq = map[int16]string{
	1: "UserID",
}

type GetUserInfoResp struct {
	Message    string      `thrift:"Message,1" frugal:"1,default,string" json:"Message"`
	Code       int64       `thrift:"Code,2" frugal:"2,default,i64" json:"Code"`
	Passengers *Passengers `thrift:"passengers,3" frugal:"3,default,Passengers" json:"passengers"`
}

func NewGetUserInfoResp() *GetUserInfoResp {
	return &GetUserInfoResp{}
}

func (p *GetUserInfoResp) InitDefault() {
}

func (p *GetUserInfoResp) GetMessage() (v string) {
	return p.Message
}

func (p *GetUserInfoResp) GetCode() (v int64) {
	return p.Code
}

var GetUserInfoResp_Passengers_DEFAULT *Passengers

func (p *GetUserInfoResp) GetPassengers() (v *Passengers) {
	if !p.IsSetPassengers() {
		return GetUserInfoResp_Passengers_DEFAULT
	}
	return p.Passengers
}
func (p *GetUserInfoResp) SetMessage(val string) {
	p.Message = val
}
func (p *GetUserInfoResp) SetCode(val int64) {
	p.Code = val
}
func (p *GetUserInfoResp) SetPassengers(val *Passengers) {
	p.Passengers = val
}

func (p *GetUserInfoResp) IsSetPassengers() bool {
	return p.Passengers != nil
}

func (p *GetUserInfoResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetUserInfoResp(%+v)", *p)
}

var fieldIDToName_GetUserInfoResp = map[int16]string{
	1: "Message",
	2: "Code",
	3: "passengers",
}

type UpdateUserInfoReq struct {
	UserID     int32       `thrift:"UserID,1" frugal:"1,default,i32" json:"UserID"`
	Passengers *Passengers `thrift:"passengers,2" frugal:"2,default,Passengers" json:"passengers"`
}

func NewUpdateUserInfoReq() *UpdateUserInfoReq {
	return &UpdateUserInfoReq{}
}

func (p *UpdateUserInfoReq) InitDefault() {
}

func (p *UpdateUserInfoReq) GetUserID() (v int32) {
	return p.UserID
}

var UpdateUserInfoReq_Passengers_DEFAULT *Passengers

func (p *UpdateUserInfoReq) GetPassengers() (v *Passengers) {
	if !p.IsSetPassengers() {
		return UpdateUserInfoReq_Passengers_DEFAULT
	}
	return p.Passengers
}
func (p *UpdateUserInfoReq) SetUserID(val int32) {
	p.UserID = val
}
func (p *UpdateUserInfoReq) SetPassengers(val *Passengers) {
	p.Passengers = val
}

func (p *UpdateUserInfoReq) IsSetPassengers() bool {
	return p.Passengers != nil
}

func (p *UpdateUserInfoReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdateUserInfoReq(%+v)", *p)
}

var fieldIDToName_UpdateUserInfoReq = map[int16]string{
	1: "UserID",
	2: "passengers",
}

type UpdateUserInfoResp struct {
	Message    string      `thrift:"Message,1" frugal:"1,default,string" json:"Message"`
	Code       int64       `thrift:"Code,2" frugal:"2,default,i64" json:"Code"`
	Passengers *Passengers `thrift:"passengers,3" frugal:"3,default,Passengers" json:"passengers"`
}

func NewUpdateUserInfoResp() *UpdateUserInfoResp {
	return &UpdateUserInfoResp{}
}

func (p *UpdateUserInfoResp) InitDefault() {
}

func (p *UpdateUserInfoResp) GetMessage() (v string) {
	return p.Message
}

func (p *UpdateUserInfoResp) GetCode() (v int64) {
	return p.Code
}

var UpdateUserInfoResp_Passengers_DEFAULT *Passengers

func (p *UpdateUserInfoResp) GetPassengers() (v *Passengers) {
	if !p.IsSetPassengers() {
		return UpdateUserInfoResp_Passengers_DEFAULT
	}
	return p.Passengers
}
func (p *UpdateUserInfoResp) SetMessage(val string) {
	p.Message = val
}
func (p *UpdateUserInfoResp) SetCode(val int64) {
	p.Code = val
}
func (p *UpdateUserInfoResp) SetPassengers(val *Passengers) {
	p.Passengers = val
}

func (p *UpdateUserInfoResp) IsSetPassengers() bool {
	return p.Passengers != nil
}

func (p *UpdateUserInfoResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdateUserInfoResp(%+v)", *p)
}

var fieldIDToName_UpdateUserInfoResp = map[int16]string{
	1: "Message",
	2: "Code",
	3: "passengers",
}

type PassengersServer interface {
	SendSms(ctx context.Context, req *SendSmsReq) (r *SendSmsResp, err error)

	Register(ctx context.Context, req *RegisterReq) (r *RegisterResp, err error)

	Login(ctx context.Context, req *LoginReq) (r *LoginResp, err error)

	GetLocation(ctx context.Context, req *LocationReq) (r *LocationResp, err error)

	GetTripInfo(ctx context.Context, req *TripReq) (r *TripResp, err error)

	GetPricing(ctx context.Context, req *PricingReq) (r *PricingResp, err error)

	PlaceOrder(ctx context.Context, req *OrderReq) (r *OrderResp, err error)

	RoutePlan(ctx context.Context, req *RoutePlanReq) (r *RoutePlanResp, err error)

	WechatLogin(ctx context.Context, req *WechatLoginReq) (r *WechatLoginResp, err error)

	BindWechat(ctx context.Context, req *BindWechatReq) (r *BindWechatResp, err error)

	UnbindWechat(ctx context.Context, req *UnbindWechatReq) (r *UnbindWechatResp, err error)

	GetUserInfo(ctx context.Context, req *GetUserInfoReq) (r *GetUserInfoResp, err error)

	UpdateUserInfo(ctx context.Context, req *UpdateUserInfoReq) (r *UpdateUserInfoResp, err error)
}

type PassengersServerSendSmsArgs struct {
	Req *SendSmsReq `thrift:"req,1" frugal:"1,default,SendSmsReq" json:"req"`
}

func NewPassengersServerSendSmsArgs() *PassengersServerSendSmsArgs {
	return &PassengersServerSendSmsArgs{}
}

func (p *PassengersServerSendSmsArgs) InitDefault() {
}

var PassengersServerSendSmsArgs_Req_DEFAULT *SendSmsReq

func (p *PassengersServerSendSmsArgs) GetReq() (v *SendSmsReq) {
	if !p.IsSetReq() {
		return PassengersServerSendSmsArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *PassengersServerSendSmsArgs) SetReq(val *SendSmsReq) {
	p.Req = val
}

func (p *PassengersServerSendSmsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *PassengersServerSendSmsArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PassengersServerSendSmsArgs(%+v)", *p)
}

var fieldIDToName_PassengersServerSendSmsArgs = map[int16]string{
	1: "req",
}

type PassengersServerSendSmsResult struct {
	Success *SendSmsResp `thrift:"success,0,optional" frugal:"0,optional,SendSmsResp" json:"success,omitempty"`
}

func NewPassengersServerSendSmsResult() *PassengersServerSendSmsResult {
	return &PassengersServerSendSmsResult{}
}

func (p *PassengersServerSendSmsResult) InitDefault() {
}

var PassengersServerSendSmsResult_Success_DEFAULT *SendSmsResp

func (p *PassengersServerSendSmsResult) GetSuccess() (v *SendSmsResp) {
	if !p.IsSetSuccess() {
		return PassengersServerSendSmsResult_Success_DEFAULT
	}
	return p.Success
}
func (p *PassengersServerSendSmsResult) SetSuccess(x interface{}) {
	p.Success = x.(*SendSmsResp)
}

func (p *PassengersServerSendSmsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *PassengersServerSendSmsResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PassengersServerSendSmsResult(%+v)", *p)
}

var fieldIDToName_PassengersServerSendSmsResult = map[int16]string{
	0: "success",
}

type PassengersServerRegisterArgs struct {
	Req *RegisterReq `thrift:"req,1" frugal:"1,default,RegisterReq" json:"req"`
}

func NewPassengersServerRegisterArgs() *PassengersServerRegisterArgs {
	return &PassengersServerRegisterArgs{}
}

func (p *PassengersServerRegisterArgs) InitDefault() {
}

var PassengersServerRegisterArgs_Req_DEFAULT *RegisterReq

func (p *PassengersServerRegisterArgs) GetReq() (v *RegisterReq) {
	if !p.IsSetReq() {
		return PassengersServerRegisterArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *PassengersServerRegisterArgs) SetReq(val *RegisterReq) {
	p.Req = val
}

func (p *PassengersServerRegisterArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *PassengersServerRegisterArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PassengersServerRegisterArgs(%+v)", *p)
}

var fieldIDToName_PassengersServerRegisterArgs = map[int16]string{
	1: "req",
}

type PassengersServerRegisterResult struct {
	Success *RegisterResp `thrift:"success,0,optional" frugal:"0,optional,RegisterResp" json:"success,omitempty"`
}

func NewPassengersServerRegisterResult() *PassengersServerRegisterResult {
	return &PassengersServerRegisterResult{}
}

func (p *PassengersServerRegisterResult) InitDefault() {
}

var PassengersServerRegisterResult_Success_DEFAULT *RegisterResp

func (p *PassengersServerRegisterResult) GetSuccess() (v *RegisterResp) {
	if !p.IsSetSuccess() {
		return PassengersServerRegisterResult_Success_DEFAULT
	}
	return p.Success
}
func (p *PassengersServerRegisterResult) SetSuccess(x interface{}) {
	p.Success = x.(*RegisterResp)
}

func (p *PassengersServerRegisterResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *PassengersServerRegisterResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PassengersServerRegisterResult(%+v)", *p)
}

var fieldIDToName_PassengersServerRegisterResult = map[int16]string{
	0: "success",
}

type PassengersServerLoginArgs struct {
	Req *LoginReq `thrift:"req,1" frugal:"1,default,LoginReq" json:"req"`
}

func NewPassengersServerLoginArgs() *PassengersServerLoginArgs {
	return &PassengersServerLoginArgs{}
}

func (p *PassengersServerLoginArgs) InitDefault() {
}

var PassengersServerLoginArgs_Req_DEFAULT *LoginReq

func (p *PassengersServerLoginArgs) GetReq() (v *LoginReq) {
	if !p.IsSetReq() {
		return PassengersServerLoginArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *PassengersServerLoginArgs) SetReq(val *LoginReq) {
	p.Req = val
}

func (p *PassengersServerLoginArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *PassengersServerLoginArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PassengersServerLoginArgs(%+v)", *p)
}

var fieldIDToName_PassengersServerLoginArgs = map[int16]string{
	1: "req",
}

type PassengersServerLoginResult struct {
	Success *LoginResp `thrift:"success,0,optional" frugal:"0,optional,LoginResp" json:"success,omitempty"`
}

func NewPassengersServerLoginResult() *PassengersServerLoginResult {
	return &PassengersServerLoginResult{}
}

func (p *PassengersServerLoginResult) InitDefault() {
}

var PassengersServerLoginResult_Success_DEFAULT *LoginResp

func (p *PassengersServerLoginResult) GetSuccess() (v *LoginResp) {
	if !p.IsSetSuccess() {
		return PassengersServerLoginResult_Success_DEFAULT
	}
	return p.Success
}
func (p *PassengersServerLoginResult) SetSuccess(x interface{}) {
	p.Success = x.(*LoginResp)
}

func (p *PassengersServerLoginResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *PassengersServerLoginResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PassengersServerLoginResult(%+v)", *p)
}

var fieldIDToName_PassengersServerLoginResult = map[int16]string{
	0: "success",
}

type PassengersServerGetLocationArgs struct {
	Req *LocationReq `thrift:"req,1" frugal:"1,default,LocationReq" json:"req"`
}

func NewPassengersServerGetLocationArgs() *PassengersServerGetLocationArgs {
	return &PassengersServerGetLocationArgs{}
}

func (p *PassengersServerGetLocationArgs) InitDefault() {
}

var PassengersServerGetLocationArgs_Req_DEFAULT *LocationReq

func (p *PassengersServerGetLocationArgs) GetReq() (v *LocationReq) {
	if !p.IsSetReq() {
		return PassengersServerGetLocationArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *PassengersServerGetLocationArgs) SetReq(val *LocationReq) {
	p.Req = val
}

func (p *PassengersServerGetLocationArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *PassengersServerGetLocationArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PassengersServerGetLocationArgs(%+v)", *p)
}

var fieldIDToName_PassengersServerGetLocationArgs = map[int16]string{
	1: "req",
}

type PassengersServerGetLocationResult struct {
	Success *LocationResp `thrift:"success,0,optional" frugal:"0,optional,LocationResp" json:"success,omitempty"`
}

func NewPassengersServerGetLocationResult() *PassengersServerGetLocationResult {
	return &PassengersServerGetLocationResult{}
}

func (p *PassengersServerGetLocationResult) InitDefault() {
}

var PassengersServerGetLocationResult_Success_DEFAULT *LocationResp

func (p *PassengersServerGetLocationResult) GetSuccess() (v *LocationResp) {
	if !p.IsSetSuccess() {
		return PassengersServerGetLocationResult_Success_DEFAULT
	}
	return p.Success
}
func (p *PassengersServerGetLocationResult) SetSuccess(x interface{}) {
	p.Success = x.(*LocationResp)
}

func (p *PassengersServerGetLocationResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *PassengersServerGetLocationResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PassengersServerGetLocationResult(%+v)", *p)
}

var fieldIDToName_PassengersServerGetLocationResult = map[int16]string{
	0: "success",
}

type PassengersServerGetTripInfoArgs struct {
	Req *TripReq `thrift:"req,1" frugal:"1,default,TripReq" json:"req"`
}

func NewPassengersServerGetTripInfoArgs() *PassengersServerGetTripInfoArgs {
	return &PassengersServerGetTripInfoArgs{}
}

func (p *PassengersServerGetTripInfoArgs) InitDefault() {
}

var PassengersServerGetTripInfoArgs_Req_DEFAULT *TripReq

func (p *PassengersServerGetTripInfoArgs) GetReq() (v *TripReq) {
	if !p.IsSetReq() {
		return PassengersServerGetTripInfoArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *PassengersServerGetTripInfoArgs) SetReq(val *TripReq) {
	p.Req = val
}

func (p *PassengersServerGetTripInfoArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *PassengersServerGetTripInfoArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PassengersServerGetTripInfoArgs(%+v)", *p)
}

var fieldIDToName_PassengersServerGetTripInfoArgs = map[int16]string{
	1: "req",
}

type PassengersServerGetTripInfoResult struct {
	Success *TripResp `thrift:"success,0,optional" frugal:"0,optional,TripResp" json:"success,omitempty"`
}

func NewPassengersServerGetTripInfoResult() *PassengersServerGetTripInfoResult {
	return &PassengersServerGetTripInfoResult{}
}

func (p *PassengersServerGetTripInfoResult) InitDefault() {
}

var PassengersServerGetTripInfoResult_Success_DEFAULT *TripResp

func (p *PassengersServerGetTripInfoResult) GetSuccess() (v *TripResp) {
	if !p.IsSetSuccess() {
		return PassengersServerGetTripInfoResult_Success_DEFAULT
	}
	return p.Success
}
func (p *PassengersServerGetTripInfoResult) SetSuccess(x interface{}) {
	p.Success = x.(*TripResp)
}

func (p *PassengersServerGetTripInfoResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *PassengersServerGetTripInfoResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PassengersServerGetTripInfoResult(%+v)", *p)
}

var fieldIDToName_PassengersServerGetTripInfoResult = map[int16]string{
	0: "success",
}

type PassengersServerGetPricingArgs struct {
	Req *PricingReq `thrift:"req,1" frugal:"1,default,PricingReq" json:"req"`
}

func NewPassengersServerGetPricingArgs() *PassengersServerGetPricingArgs {
	return &PassengersServerGetPricingArgs{}
}

func (p *PassengersServerGetPricingArgs) InitDefault() {
}

var PassengersServerGetPricingArgs_Req_DEFAULT *PricingReq

func (p *PassengersServerGetPricingArgs) GetReq() (v *PricingReq) {
	if !p.IsSetReq() {
		return PassengersServerGetPricingArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *PassengersServerGetPricingArgs) SetReq(val *PricingReq) {
	p.Req = val
}

func (p *PassengersServerGetPricingArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *PassengersServerGetPricingArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PassengersServerGetPricingArgs(%+v)", *p)
}

var fieldIDToName_PassengersServerGetPricingArgs = map[int16]string{
	1: "req",
}

type PassengersServerGetPricingResult struct {
	Success *PricingResp `thrift:"success,0,optional" frugal:"0,optional,PricingResp" json:"success,omitempty"`
}

func NewPassengersServerGetPricingResult() *PassengersServerGetPricingResult {
	return &PassengersServerGetPricingResult{}
}

func (p *PassengersServerGetPricingResult) InitDefault() {
}

var PassengersServerGetPricingResult_Success_DEFAULT *PricingResp

func (p *PassengersServerGetPricingResult) GetSuccess() (v *PricingResp) {
	if !p.IsSetSuccess() {
		return PassengersServerGetPricingResult_Success_DEFAULT
	}
	return p.Success
}
func (p *PassengersServerGetPricingResult) SetSuccess(x interface{}) {
	p.Success = x.(*PricingResp)
}

func (p *PassengersServerGetPricingResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *PassengersServerGetPricingResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PassengersServerGetPricingResult(%+v)", *p)
}

var fieldIDToName_PassengersServerGetPricingResult = map[int16]string{
	0: "success",
}

type PassengersServerPlaceOrderArgs struct {
	Req *OrderReq `thrift:"req,1" frugal:"1,default,OrderReq" json:"req"`
}

func NewPassengersServerPlaceOrderArgs() *PassengersServerPlaceOrderArgs {
	return &PassengersServerPlaceOrderArgs{}
}

func (p *PassengersServerPlaceOrderArgs) InitDefault() {
}

var PassengersServerPlaceOrderArgs_Req_DEFAULT *OrderReq

func (p *PassengersServerPlaceOrderArgs) GetReq() (v *OrderReq) {
	if !p.IsSetReq() {
		return PassengersServerPlaceOrderArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *PassengersServerPlaceOrderArgs) SetReq(val *OrderReq) {
	p.Req = val
}

func (p *PassengersServerPlaceOrderArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *PassengersServerPlaceOrderArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PassengersServerPlaceOrderArgs(%+v)", *p)
}

var fieldIDToName_PassengersServerPlaceOrderArgs = map[int16]string{
	1: "req",
}

type PassengersServerPlaceOrderResult struct {
	Success *OrderResp `thrift:"success,0,optional" frugal:"0,optional,OrderResp" json:"success,omitempty"`
}

func NewPassengersServerPlaceOrderResult() *PassengersServerPlaceOrderResult {
	return &PassengersServerPlaceOrderResult{}
}

func (p *PassengersServerPlaceOrderResult) InitDefault() {
}

var PassengersServerPlaceOrderResult_Success_DEFAULT *OrderResp

func (p *PassengersServerPlaceOrderResult) GetSuccess() (v *OrderResp) {
	if !p.IsSetSuccess() {
		return PassengersServerPlaceOrderResult_Success_DEFAULT
	}
	return p.Success
}
func (p *PassengersServerPlaceOrderResult) SetSuccess(x interface{}) {
	p.Success = x.(*OrderResp)
}

func (p *PassengersServerPlaceOrderResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *PassengersServerPlaceOrderResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PassengersServerPlaceOrderResult(%+v)", *p)
}

var fieldIDToName_PassengersServerPlaceOrderResult = map[int16]string{
	0: "success",
}

type PassengersServerRoutePlanArgs struct {
	Req *RoutePlanReq `thrift:"req,1" frugal:"1,default,RoutePlanReq" json:"req"`
}

func NewPassengersServerRoutePlanArgs() *PassengersServerRoutePlanArgs {
	return &PassengersServerRoutePlanArgs{}
}

func (p *PassengersServerRoutePlanArgs) InitDefault() {
}

var PassengersServerRoutePlanArgs_Req_DEFAULT *RoutePlanReq

func (p *PassengersServerRoutePlanArgs) GetReq() (v *RoutePlanReq) {
	if !p.IsSetReq() {
		return PassengersServerRoutePlanArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *PassengersServerRoutePlanArgs) SetReq(val *RoutePlanReq) {
	p.Req = val
}

func (p *PassengersServerRoutePlanArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *PassengersServerRoutePlanArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PassengersServerRoutePlanArgs(%+v)", *p)
}

var fieldIDToName_PassengersServerRoutePlanArgs = map[int16]string{
	1: "req",
}

type PassengersServerRoutePlanResult struct {
	Success *RoutePlanResp `thrift:"success,0,optional" frugal:"0,optional,RoutePlanResp" json:"success,omitempty"`
}

func NewPassengersServerRoutePlanResult() *PassengersServerRoutePlanResult {
	return &PassengersServerRoutePlanResult{}
}

func (p *PassengersServerRoutePlanResult) InitDefault() {
}

var PassengersServerRoutePlanResult_Success_DEFAULT *RoutePlanResp

func (p *PassengersServerRoutePlanResult) GetSuccess() (v *RoutePlanResp) {
	if !p.IsSetSuccess() {
		return PassengersServerRoutePlanResult_Success_DEFAULT
	}
	return p.Success
}
func (p *PassengersServerRoutePlanResult) SetSuccess(x interface{}) {
	p.Success = x.(*RoutePlanResp)
}

func (p *PassengersServerRoutePlanResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *PassengersServerRoutePlanResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PassengersServerRoutePlanResult(%+v)", *p)
}

var fieldIDToName_PassengersServerRoutePlanResult = map[int16]string{
	0: "success",
}

type PassengersServerWechatLoginArgs struct {
	Req *WechatLoginReq `thrift:"req,1" frugal:"1,default,WechatLoginReq" json:"req"`
}

func NewPassengersServerWechatLoginArgs() *PassengersServerWechatLoginArgs {
	return &PassengersServerWechatLoginArgs{}
}

func (p *PassengersServerWechatLoginArgs) InitDefault() {
}

var PassengersServerWechatLoginArgs_Req_DEFAULT *WechatLoginReq

func (p *PassengersServerWechatLoginArgs) GetReq() (v *WechatLoginReq) {
	if !p.IsSetReq() {
		return PassengersServerWechatLoginArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *PassengersServerWechatLoginArgs) SetReq(val *WechatLoginReq) {
	p.Req = val
}

func (p *PassengersServerWechatLoginArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *PassengersServerWechatLoginArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PassengersServerWechatLoginArgs(%+v)", *p)
}

var fieldIDToName_PassengersServerWechatLoginArgs = map[int16]string{
	1: "req",
}

type PassengersServerWechatLoginResult struct {
	Success *WechatLoginResp `thrift:"success,0,optional" frugal:"0,optional,WechatLoginResp" json:"success,omitempty"`
}

func NewPassengersServerWechatLoginResult() *PassengersServerWechatLoginResult {
	return &PassengersServerWechatLoginResult{}
}

func (p *PassengersServerWechatLoginResult) InitDefault() {
}

var PassengersServerWechatLoginResult_Success_DEFAULT *WechatLoginResp

func (p *PassengersServerWechatLoginResult) GetSuccess() (v *WechatLoginResp) {
	if !p.IsSetSuccess() {
		return PassengersServerWechatLoginResult_Success_DEFAULT
	}
	return p.Success
}
func (p *PassengersServerWechatLoginResult) SetSuccess(x interface{}) {
	p.Success = x.(*WechatLoginResp)
}

func (p *PassengersServerWechatLoginResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *PassengersServerWechatLoginResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PassengersServerWechatLoginResult(%+v)", *p)
}

var fieldIDToName_PassengersServerWechatLoginResult = map[int16]string{
	0: "success",
}

type PassengersServerBindWechatArgs struct {
	Req *BindWechatReq `thrift:"req,1" frugal:"1,default,BindWechatReq" json:"req"`
}

func NewPassengersServerBindWechatArgs() *PassengersServerBindWechatArgs {
	return &PassengersServerBindWechatArgs{}
}

func (p *PassengersServerBindWechatArgs) InitDefault() {
}

var PassengersServerBindWechatArgs_Req_DEFAULT *BindWechatReq

func (p *PassengersServerBindWechatArgs) GetReq() (v *BindWechatReq) {
	if !p.IsSetReq() {
		return PassengersServerBindWechatArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *PassengersServerBindWechatArgs) SetReq(val *BindWechatReq) {
	p.Req = val
}

func (p *PassengersServerBindWechatArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *PassengersServerBindWechatArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PassengersServerBindWechatArgs(%+v)", *p)
}

var fieldIDToName_PassengersServerBindWechatArgs = map[int16]string{
	1: "req",
}

type PassengersServerBindWechatResult struct {
	Success *BindWechatResp `thrift:"success,0,optional" frugal:"0,optional,BindWechatResp" json:"success,omitempty"`
}

func NewPassengersServerBindWechatResult() *PassengersServerBindWechatResult {
	return &PassengersServerBindWechatResult{}
}

func (p *PassengersServerBindWechatResult) InitDefault() {
}

var PassengersServerBindWechatResult_Success_DEFAULT *BindWechatResp

func (p *PassengersServerBindWechatResult) GetSuccess() (v *BindWechatResp) {
	if !p.IsSetSuccess() {
		return PassengersServerBindWechatResult_Success_DEFAULT
	}
	return p.Success
}
func (p *PassengersServerBindWechatResult) SetSuccess(x interface{}) {
	p.Success = x.(*BindWechatResp)
}

func (p *PassengersServerBindWechatResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *PassengersServerBindWechatResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PassengersServerBindWechatResult(%+v)", *p)
}

var fieldIDToName_PassengersServerBindWechatResult = map[int16]string{
	0: "success",
}

type PassengersServerUnbindWechatArgs struct {
	Req *UnbindWechatReq `thrift:"req,1" frugal:"1,default,UnbindWechatReq" json:"req"`
}

func NewPassengersServerUnbindWechatArgs() *PassengersServerUnbindWechatArgs {
	return &PassengersServerUnbindWechatArgs{}
}

func (p *PassengersServerUnbindWechatArgs) InitDefault() {
}

var PassengersServerUnbindWechatArgs_Req_DEFAULT *UnbindWechatReq

func (p *PassengersServerUnbindWechatArgs) GetReq() (v *UnbindWechatReq) {
	if !p.IsSetReq() {
		return PassengersServerUnbindWechatArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *PassengersServerUnbindWechatArgs) SetReq(val *UnbindWechatReq) {
	p.Req = val
}

func (p *PassengersServerUnbindWechatArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *PassengersServerUnbindWechatArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PassengersServerUnbindWechatArgs(%+v)", *p)
}

var fieldIDToName_PassengersServerUnbindWechatArgs = map[int16]string{
	1: "req",
}

type PassengersServerUnbindWechatResult struct {
	Success *UnbindWechatResp `thrift:"success,0,optional" frugal:"0,optional,UnbindWechatResp" json:"success,omitempty"`
}

func NewPassengersServerUnbindWechatResult() *PassengersServerUnbindWechatResult {
	return &PassengersServerUnbindWechatResult{}
}

func (p *PassengersServerUnbindWechatResult) InitDefault() {
}

var PassengersServerUnbindWechatResult_Success_DEFAULT *UnbindWechatResp

func (p *PassengersServerUnbindWechatResult) GetSuccess() (v *UnbindWechatResp) {
	if !p.IsSetSuccess() {
		return PassengersServerUnbindWechatResult_Success_DEFAULT
	}
	return p.Success
}
func (p *PassengersServerUnbindWechatResult) SetSuccess(x interface{}) {
	p.Success = x.(*UnbindWechatResp)
}

func (p *PassengersServerUnbindWechatResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *PassengersServerUnbindWechatResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PassengersServerUnbindWechatResult(%+v)", *p)
}

var fieldIDToName_PassengersServerUnbindWechatResult = map[int16]string{
	0: "success",
}

type PassengersServerGetUserInfoArgs struct {
	Req *GetUserInfoReq `thrift:"req,1" frugal:"1,default,GetUserInfoReq" json:"req"`
}

func NewPassengersServerGetUserInfoArgs() *PassengersServerGetUserInfoArgs {
	return &PassengersServerGetUserInfoArgs{}
}

func (p *PassengersServerGetUserInfoArgs) InitDefault() {
}

var PassengersServerGetUserInfoArgs_Req_DEFAULT *GetUserInfoReq

func (p *PassengersServerGetUserInfoArgs) GetReq() (v *GetUserInfoReq) {
	if !p.IsSetReq() {
		return PassengersServerGetUserInfoArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *PassengersServerGetUserInfoArgs) SetReq(val *GetUserInfoReq) {
	p.Req = val
}

func (p *PassengersServerGetUserInfoArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *PassengersServerGetUserInfoArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PassengersServerGetUserInfoArgs(%+v)", *p)
}

var fieldIDToName_PassengersServerGetUserInfoArgs = map[int16]string{
	1: "req",
}

type PassengersServerGetUserInfoResult struct {
	Success *GetUserInfoResp `thrift:"success,0,optional" frugal:"0,optional,GetUserInfoResp" json:"success,omitempty"`
}

func NewPassengersServerGetUserInfoResult() *PassengersServerGetUserInfoResult {
	return &PassengersServerGetUserInfoResult{}
}

func (p *PassengersServerGetUserInfoResult) InitDefault() {
}

var PassengersServerGetUserInfoResult_Success_DEFAULT *GetUserInfoResp

func (p *PassengersServerGetUserInfoResult) GetSuccess() (v *GetUserInfoResp) {
	if !p.IsSetSuccess() {
		return PassengersServerGetUserInfoResult_Success_DEFAULT
	}
	return p.Success
}
func (p *PassengersServerGetUserInfoResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetUserInfoResp)
}

func (p *PassengersServerGetUserInfoResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *PassengersServerGetUserInfoResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PassengersServerGetUserInfoResult(%+v)", *p)
}

var fieldIDToName_PassengersServerGetUserInfoResult = map[int16]string{
	0: "success",
}

type PassengersServerUpdateUserInfoArgs struct {
	Req *UpdateUserInfoReq `thrift:"req,1" frugal:"1,default,UpdateUserInfoReq" json:"req"`
}

func NewPassengersServerUpdateUserInfoArgs() *PassengersServerUpdateUserInfoArgs {
	return &PassengersServerUpdateUserInfoArgs{}
}

func (p *PassengersServerUpdateUserInfoArgs) InitDefault() {
}

var PassengersServerUpdateUserInfoArgs_Req_DEFAULT *UpdateUserInfoReq

func (p *PassengersServerUpdateUserInfoArgs) GetReq() (v *UpdateUserInfoReq) {
	if !p.IsSetReq() {
		return PassengersServerUpdateUserInfoArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *PassengersServerUpdateUserInfoArgs) SetReq(val *UpdateUserInfoReq) {
	p.Req = val
}

func (p *PassengersServerUpdateUserInfoArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *PassengersServerUpdateUserInfoArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PassengersServerUpdateUserInfoArgs(%+v)", *p)
}

var fieldIDToName_PassengersServerUpdateUserInfoArgs = map[int16]string{
	1: "req",
}

type PassengersServerUpdateUserInfoResult struct {
	Success *UpdateUserInfoResp `thrift:"success,0,optional" frugal:"0,optional,UpdateUserInfoResp" json:"success,omitempty"`
}

func NewPassengersServerUpdateUserInfoResult() *PassengersServerUpdateUserInfoResult {
	return &PassengersServerUpdateUserInfoResult{}
}

func (p *PassengersServerUpdateUserInfoResult) InitDefault() {
}

var PassengersServerUpdateUserInfoResult_Success_DEFAULT *UpdateUserInfoResp

func (p *PassengersServerUpdateUserInfoResult) GetSuccess() (v *UpdateUserInfoResp) {
	if !p.IsSetSuccess() {
		return PassengersServerUpdateUserInfoResult_Success_DEFAULT
	}
	return p.Success
}
func (p *PassengersServerUpdateUserInfoResult) SetSuccess(x interface{}) {
	p.Success = x.(*UpdateUserInfoResp)
}

func (p *PassengersServerUpdateUserInfoResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *PassengersServerUpdateUserInfoResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PassengersServerUpdateUserInfoResult(%+v)", *p)
}

var fieldIDToName_PassengersServerUpdateUserInfoResult = map[int16]string{
	0: "success",
}
