// Code generated by Kitex v0.14.1. DO NOT EDIT.

package userservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	user "lxh_cx/kitex_gen/lxh_cx/user"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	SendSms(ctx context.Context, req *user.SendSmsReq, callOptions ...callopt.Option) (r *user.SendSmsResp, err error)
	Register(ctx context.Context, req *user.RegisterReq, callOptions ...callopt.Option) (r *user.RegisterResp, err error)
	Login(ctx context.Context, req *user.LoginReq, callOptions ...callopt.Option) (r *user.LoginResp, err error)
	UserInfoList(ctx context.Context, req *user.UserInfoListReq, callOptions ...callopt.Option) (r *user.UserInfoListResp, err error)
	BindMobile(ctx context.Context, req *user.BindMobileReq, callOptions ...callopt.Option) (r *user.BindMobileResp, err error)
	UpdateUserInfo(ctx context.Context, req *user.UpdateUserInfoReq, callOptions ...callopt.Option) (r *user.UpdateUserInfoResp, err error)
	UpdateCancelOrder(ctx context.Context, req *user.UpdateCancelOrderReq, callOptions ...callopt.Option) (r *user.UpdateCancelOrderResp, err error)
	FindRouteRecord(ctx context.Context, req *user.FindRouteRecordReq, callOptions ...callopt.Option) (r *user.FindRouteRecordResp, err error)
	SetRouteUser(ctx context.Context, req *user.SetRouteUserReq, callOptions ...callopt.Option) (r *user.SetRouteUserResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kUserServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kUserServiceClient struct {
	*kClient
}

func (p *kUserServiceClient) SendSms(ctx context.Context, req *user.SendSmsReq, callOptions ...callopt.Option) (r *user.SendSmsResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SendSms(ctx, req)
}

func (p *kUserServiceClient) Register(ctx context.Context, req *user.RegisterReq, callOptions ...callopt.Option) (r *user.RegisterResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Register(ctx, req)
}

func (p *kUserServiceClient) Login(ctx context.Context, req *user.LoginReq, callOptions ...callopt.Option) (r *user.LoginResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Login(ctx, req)
}

func (p *kUserServiceClient) UserInfoList(ctx context.Context, req *user.UserInfoListReq, callOptions ...callopt.Option) (r *user.UserInfoListResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UserInfoList(ctx, req)
}

func (p *kUserServiceClient) BindMobile(ctx context.Context, req *user.BindMobileReq, callOptions ...callopt.Option) (r *user.BindMobileResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.BindMobile(ctx, req)
}

func (p *kUserServiceClient) UpdateUserInfo(ctx context.Context, req *user.UpdateUserInfoReq, callOptions ...callopt.Option) (r *user.UpdateUserInfoResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateUserInfo(ctx, req)
}

func (p *kUserServiceClient) UpdateCancelOrder(ctx context.Context, req *user.UpdateCancelOrderReq, callOptions ...callopt.Option) (r *user.UpdateCancelOrderResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateCancelOrder(ctx, req)
}

func (p *kUserServiceClient) FindRouteRecord(ctx context.Context, req *user.FindRouteRecordReq, callOptions ...callopt.Option) (r *user.FindRouteRecordResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.FindRouteRecord(ctx, req)
}

func (p *kUserServiceClient) SetRouteUser(ctx context.Context, req *user.SetRouteUserReq, callOptions ...callopt.Option) (r *user.SetRouteUserResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SetRouteUser(ctx, req)
}
