// Code generated by Kitex v0.14.1. DO NOT EDIT.

package userservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	user "lxh_cx/kitex_gen/lxh_cx/user"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"SendSms": kitex.NewMethodInfo(
		sendSmsHandler,
		newUserServiceSendSmsArgs,
		newUserServiceSendSmsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Register": kitex.NewMethodInfo(
		registerHandler,
		newUserServiceRegisterArgs,
		newUserServiceRegisterResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Login": kitex.NewMethodInfo(
		loginHandler,
		newUserServiceLoginArgs,
		newUserServiceLoginResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"UserInfoList": kitex.NewMethodInfo(
		userInfoListHandler,
		newUserServiceUserInfoListArgs,
		newUserServiceUserInfoListResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"BindMobile": kitex.NewMethodInfo(
		bindMobileHandler,
		newUserServiceBindMobileArgs,
		newUserServiceBindMobileResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"UpdateUserInfo": kitex.NewMethodInfo(
		updateUserInfoHandler,
		newUserServiceUpdateUserInfoArgs,
		newUserServiceUpdateUserInfoResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"UpdateCancelOrder": kitex.NewMethodInfo(
		updateCancelOrderHandler,
		newUserServiceUpdateCancelOrderArgs,
		newUserServiceUpdateCancelOrderResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"FindRouteRecord": kitex.NewMethodInfo(
		findRouteRecordHandler,
		newUserServiceFindRouteRecordArgs,
		newUserServiceFindRouteRecordResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"SetRouteUser": kitex.NewMethodInfo(
		setRouteUserHandler,
		newUserServiceSetRouteUserArgs,
		newUserServiceSetRouteUserResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	userServiceServiceInfo                = NewServiceInfo()
	userServiceServiceInfoForClient       = NewServiceInfoForClient()
	userServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return userServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return userServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return userServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "UserService"
	handlerType := (*user.UserService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "user",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.14.1",
		Extra:           extra,
	}
	return svcInfo
}

func sendSmsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceSendSmsArgs)
	realResult := result.(*user.UserServiceSendSmsResult)
	success, err := handler.(user.UserService).SendSms(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceSendSmsArgs() interface{} {
	return user.NewUserServiceSendSmsArgs()
}

func newUserServiceSendSmsResult() interface{} {
	return user.NewUserServiceSendSmsResult()
}

func registerHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceRegisterArgs)
	realResult := result.(*user.UserServiceRegisterResult)
	success, err := handler.(user.UserService).Register(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceRegisterArgs() interface{} {
	return user.NewUserServiceRegisterArgs()
}

func newUserServiceRegisterResult() interface{} {
	return user.NewUserServiceRegisterResult()
}

func loginHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceLoginArgs)
	realResult := result.(*user.UserServiceLoginResult)
	success, err := handler.(user.UserService).Login(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceLoginArgs() interface{} {
	return user.NewUserServiceLoginArgs()
}

func newUserServiceLoginResult() interface{} {
	return user.NewUserServiceLoginResult()
}

func userInfoListHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceUserInfoListArgs)
	realResult := result.(*user.UserServiceUserInfoListResult)
	success, err := handler.(user.UserService).UserInfoList(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceUserInfoListArgs() interface{} {
	return user.NewUserServiceUserInfoListArgs()
}

func newUserServiceUserInfoListResult() interface{} {
	return user.NewUserServiceUserInfoListResult()
}

func bindMobileHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceBindMobileArgs)
	realResult := result.(*user.UserServiceBindMobileResult)
	success, err := handler.(user.UserService).BindMobile(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceBindMobileArgs() interface{} {
	return user.NewUserServiceBindMobileArgs()
}

func newUserServiceBindMobileResult() interface{} {
	return user.NewUserServiceBindMobileResult()
}

func updateUserInfoHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceUpdateUserInfoArgs)
	realResult := result.(*user.UserServiceUpdateUserInfoResult)
	success, err := handler.(user.UserService).UpdateUserInfo(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceUpdateUserInfoArgs() interface{} {
	return user.NewUserServiceUpdateUserInfoArgs()
}

func newUserServiceUpdateUserInfoResult() interface{} {
	return user.NewUserServiceUpdateUserInfoResult()
}

func updateCancelOrderHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceUpdateCancelOrderArgs)
	realResult := result.(*user.UserServiceUpdateCancelOrderResult)
	success, err := handler.(user.UserService).UpdateCancelOrder(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceUpdateCancelOrderArgs() interface{} {
	return user.NewUserServiceUpdateCancelOrderArgs()
}

func newUserServiceUpdateCancelOrderResult() interface{} {
	return user.NewUserServiceUpdateCancelOrderResult()
}

func findRouteRecordHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceFindRouteRecordArgs)
	realResult := result.(*user.UserServiceFindRouteRecordResult)
	success, err := handler.(user.UserService).FindRouteRecord(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceFindRouteRecordArgs() interface{} {
	return user.NewUserServiceFindRouteRecordArgs()
}

func newUserServiceFindRouteRecordResult() interface{} {
	return user.NewUserServiceFindRouteRecordResult()
}

func setRouteUserHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceSetRouteUserArgs)
	realResult := result.(*user.UserServiceSetRouteUserResult)
	success, err := handler.(user.UserService).SetRouteUser(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceSetRouteUserArgs() interface{} {
	return user.NewUserServiceSetRouteUserArgs()
}

func newUserServiceSetRouteUserResult() interface{} {
	return user.NewUserServiceSetRouteUserResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) SendSms(ctx context.Context, req *user.SendSmsReq) (r *user.SendSmsResp, err error) {
	var _args user.UserServiceSendSmsArgs
	_args.Req = req
	var _result user.UserServiceSendSmsResult
	if err = p.c.Call(ctx, "SendSms", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Register(ctx context.Context, req *user.RegisterReq) (r *user.RegisterResp, err error) {
	var _args user.UserServiceRegisterArgs
	_args.Req = req
	var _result user.UserServiceRegisterResult
	if err = p.c.Call(ctx, "Register", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Login(ctx context.Context, req *user.LoginReq) (r *user.LoginResp, err error) {
	var _args user.UserServiceLoginArgs
	_args.Req = req
	var _result user.UserServiceLoginResult
	if err = p.c.Call(ctx, "Login", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UserInfoList(ctx context.Context, req *user.UserInfoListReq) (r *user.UserInfoListResp, err error) {
	var _args user.UserServiceUserInfoListArgs
	_args.Req = req
	var _result user.UserServiceUserInfoListResult
	if err = p.c.Call(ctx, "UserInfoList", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) BindMobile(ctx context.Context, req *user.BindMobileReq) (r *user.BindMobileResp, err error) {
	var _args user.UserServiceBindMobileArgs
	_args.Req = req
	var _result user.UserServiceBindMobileResult
	if err = p.c.Call(ctx, "BindMobile", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpdateUserInfo(ctx context.Context, req *user.UpdateUserInfoReq) (r *user.UpdateUserInfoResp, err error) {
	var _args user.UserServiceUpdateUserInfoArgs
	_args.Req = req
	var _result user.UserServiceUpdateUserInfoResult
	if err = p.c.Call(ctx, "UpdateUserInfo", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpdateCancelOrder(ctx context.Context, req *user.UpdateCancelOrderReq) (r *user.UpdateCancelOrderResp, err error) {
	var _args user.UserServiceUpdateCancelOrderArgs
	_args.Req = req
	var _result user.UserServiceUpdateCancelOrderResult
	if err = p.c.Call(ctx, "UpdateCancelOrder", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) FindRouteRecord(ctx context.Context, req *user.FindRouteRecordReq) (r *user.FindRouteRecordResp, err error) {
	var _args user.UserServiceFindRouteRecordArgs
	_args.Req = req
	var _result user.UserServiceFindRouteRecordResult
	if err = p.c.Call(ctx, "FindRouteRecord", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) SetRouteUser(ctx context.Context, req *user.SetRouteUserReq) (r *user.SetRouteUserResp, err error) {
	var _args user.UserServiceSetRouteUserArgs
	_args.Req = req
	var _result user.UserServiceSetRouteUserResult
	if err = p.c.Call(ctx, "SetRouteUser", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
