// Code generated by thriftgo (0.4.2). DO NOT EDIT.

package order

import (
	"context"
	"fmt"
	"lxh_cx/kitex_gen/lxh_cx/base"
)

type PassengerAddOrderReq struct {
	PassengerId int32  `thrift:"passengerId,1" frugal:"1,default,i32" json:"passengerId"`
	StartAddr   string `thrift:"startAddr,2" frugal:"2,default,string" json:"startAddr"`
	EndEnd      string `thrift:"endEnd,3" frugal:"3,default,string" json:"endEnd"`
}

func NewPassengerAddOrderReq() *PassengerAddOrderReq {
	return &PassengerAddOrderReq{}
}

func (p *PassengerAddOrderReq) InitDefault() {
}

func (p *PassengerAddOrderReq) GetPassengerId() (v int32) {
	return p.PassengerId
}

func (p *PassengerAddOrderReq) GetStartAddr() (v string) {
	return p.StartAddr
}

func (p *PassengerAddOrderReq) GetEndEnd() (v string) {
	return p.EndEnd
}
func (p *PassengerAddOrderReq) SetPassengerId(val int32) {
	p.PassengerId = val
}
func (p *PassengerAddOrderReq) SetStartAddr(val string) {
	p.StartAddr = val
}
func (p *PassengerAddOrderReq) SetEndEnd(val string) {
	p.EndEnd = val
}

func (p *PassengerAddOrderReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PassengerAddOrderReq(%+v)", *p)
}

var fieldIDToName_PassengerAddOrderReq = map[int16]string{
	1: "passengerId",
	2: "startAddr",
	3: "endEnd",
}

type PassengerAddOrderResp struct {
	BaseResp *base.BaseResp `thrift:"baseResp,1" frugal:"1,default,base.BaseResp" json:"baseResp"`
}

func NewPassengerAddOrderResp() *PassengerAddOrderResp {
	return &PassengerAddOrderResp{}
}

func (p *PassengerAddOrderResp) InitDefault() {
}

var PassengerAddOrderResp_BaseResp_DEFAULT *base.BaseResp

func (p *PassengerAddOrderResp) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return PassengerAddOrderResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *PassengerAddOrderResp) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}

func (p *PassengerAddOrderResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *PassengerAddOrderResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PassengerAddOrderResp(%+v)", *p)
}

var fieldIDToName_PassengerAddOrderResp = map[int16]string{
	1: "baseResp",
}

type RouteAddReq struct {
	DataString string `thrift:"dataString,1" frugal:"1,default,string" json:"dataString"`
}

func NewRouteAddReq() *RouteAddReq {
	return &RouteAddReq{}
}

func (p *RouteAddReq) InitDefault() {
}

func (p *RouteAddReq) GetDataString() (v string) {
	return p.DataString
}
func (p *RouteAddReq) SetDataString(val string) {
	p.DataString = val
}

func (p *RouteAddReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RouteAddReq(%+v)", *p)
}

var fieldIDToName_RouteAddReq = map[int16]string{
	1: "dataString",
}

type RouteAddResp struct {
	BaseResp *base.BaseResp `thrift:"baseResp,1" frugal:"1,default,base.BaseResp" json:"baseResp"`
}

func NewRouteAddResp() *RouteAddResp {
	return &RouteAddResp{}
}

func (p *RouteAddResp) InitDefault() {
}

var RouteAddResp_BaseResp_DEFAULT *base.BaseResp

func (p *RouteAddResp) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return RouteAddResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *RouteAddResp) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}

func (p *RouteAddResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *RouteAddResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RouteAddResp(%+v)", *p)
}

var fieldIDToName_RouteAddResp = map[int16]string{
	1: "baseResp",
}

type OrderService interface {
	PassengerAddOrder(ctx context.Context, req *PassengerAddOrderReq) (r *PassengerAddOrderResp, err error)

	RouteAdd(ctx context.Context, req *RouteAddReq) (r *RouteAddResp, err error)
}

type OrderServicePassengerAddOrderArgs struct {
	Req *PassengerAddOrderReq `thrift:"req,1" frugal:"1,default,PassengerAddOrderReq" json:"req"`
}

func NewOrderServicePassengerAddOrderArgs() *OrderServicePassengerAddOrderArgs {
	return &OrderServicePassengerAddOrderArgs{}
}

func (p *OrderServicePassengerAddOrderArgs) InitDefault() {
}

var OrderServicePassengerAddOrderArgs_Req_DEFAULT *PassengerAddOrderReq

func (p *OrderServicePassengerAddOrderArgs) GetReq() (v *PassengerAddOrderReq) {
	if !p.IsSetReq() {
		return OrderServicePassengerAddOrderArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *OrderServicePassengerAddOrderArgs) SetReq(val *PassengerAddOrderReq) {
	p.Req = val
}

func (p *OrderServicePassengerAddOrderArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *OrderServicePassengerAddOrderArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderServicePassengerAddOrderArgs(%+v)", *p)
}

var fieldIDToName_OrderServicePassengerAddOrderArgs = map[int16]string{
	1: "req",
}

type OrderServicePassengerAddOrderResult struct {
	Success *PassengerAddOrderResp `thrift:"success,0,optional" frugal:"0,optional,PassengerAddOrderResp" json:"success,omitempty"`
}

func NewOrderServicePassengerAddOrderResult() *OrderServicePassengerAddOrderResult {
	return &OrderServicePassengerAddOrderResult{}
}

func (p *OrderServicePassengerAddOrderResult) InitDefault() {
}

var OrderServicePassengerAddOrderResult_Success_DEFAULT *PassengerAddOrderResp

func (p *OrderServicePassengerAddOrderResult) GetSuccess() (v *PassengerAddOrderResp) {
	if !p.IsSetSuccess() {
		return OrderServicePassengerAddOrderResult_Success_DEFAULT
	}
	return p.Success
}
func (p *OrderServicePassengerAddOrderResult) SetSuccess(x interface{}) {
	p.Success = x.(*PassengerAddOrderResp)
}

func (p *OrderServicePassengerAddOrderResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *OrderServicePassengerAddOrderResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderServicePassengerAddOrderResult(%+v)", *p)
}

var fieldIDToName_OrderServicePassengerAddOrderResult = map[int16]string{
	0: "success",
}

type OrderServiceRouteAddArgs struct {
	Req *RouteAddReq `thrift:"req,1" frugal:"1,default,RouteAddReq" json:"req"`
}

func NewOrderServiceRouteAddArgs() *OrderServiceRouteAddArgs {
	return &OrderServiceRouteAddArgs{}
}

func (p *OrderServiceRouteAddArgs) InitDefault() {
}

var OrderServiceRouteAddArgs_Req_DEFAULT *RouteAddReq

func (p *OrderServiceRouteAddArgs) GetReq() (v *RouteAddReq) {
	if !p.IsSetReq() {
		return OrderServiceRouteAddArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *OrderServiceRouteAddArgs) SetReq(val *RouteAddReq) {
	p.Req = val
}

func (p *OrderServiceRouteAddArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *OrderServiceRouteAddArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderServiceRouteAddArgs(%+v)", *p)
}

var fieldIDToName_OrderServiceRouteAddArgs = map[int16]string{
	1: "req",
}

type OrderServiceRouteAddResult struct {
	Success *RouteAddResp `thrift:"success,0,optional" frugal:"0,optional,RouteAddResp" json:"success,omitempty"`
}

func NewOrderServiceRouteAddResult() *OrderServiceRouteAddResult {
	return &OrderServiceRouteAddResult{}
}

func (p *OrderServiceRouteAddResult) InitDefault() {
}

var OrderServiceRouteAddResult_Success_DEFAULT *RouteAddResp

func (p *OrderServiceRouteAddResult) GetSuccess() (v *RouteAddResp) {
	if !p.IsSetSuccess() {
		return OrderServiceRouteAddResult_Success_DEFAULT
	}
	return p.Success
}
func (p *OrderServiceRouteAddResult) SetSuccess(x interface{}) {
	p.Success = x.(*RouteAddResp)
}

func (p *OrderServiceRouteAddResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *OrderServiceRouteAddResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderServiceRouteAddResult(%+v)", *p)
}

var fieldIDToName_OrderServiceRouteAddResult = map[int16]string{
	0: "success",
}
