// Code generated by thriftgo (0.4.2). DO NOT EDIT.

package driver

import (
	"context"
	"fmt"
)

type LxhDriver struct {
	Id        int32   `thrift:"Id,1" frugal:"1,default,i32" json:"Id"`
	Name      string  `thrift:"Name,2" frugal:"2,default,string" json:"Name"`
	NickName  string  `thrift:"NickName,3" frugal:"3,default,string" json:"NickName"`
	AllAcount float64 `thrift:"AllAcount,4" frugal:"4,default,double" json:"AllAcount"`
	CarAge    int32   `thrift:"CarAge,5" frugal:"5,default,i32" json:"CarAge"`
	Status    string  `thrift:"Status,6" frugal:"6,default,string" json:"Status"`
	Mobile    string  `thrift:"Mobile,7" frugal:"7,default,string" json:"Mobile"`
	FileId    int32   `thrift:"FileId,8" frugal:"8,default,i32" json:"FileId"`
}

func NewLxhDriver() *LxhDriver {
	return &LxhDriver{}
}

func (p *LxhDriver) InitDefault() {
}

func (p *LxhDriver) GetId() (v int32) {
	return p.Id
}

func (p *LxhDriver) GetName() (v string) {
	return p.Name
}

func (p *LxhDriver) GetNickName() (v string) {
	return p.NickName
}

func (p *LxhDriver) GetAllAcount() (v float64) {
	return p.AllAcount
}

func (p *LxhDriver) GetCarAge() (v int32) {
	return p.CarAge
}

func (p *LxhDriver) GetStatus() (v string) {
	return p.Status
}

func (p *LxhDriver) GetMobile() (v string) {
	return p.Mobile
}

func (p *LxhDriver) GetFileId() (v int32) {
	return p.FileId
}
func (p *LxhDriver) SetId(val int32) {
	p.Id = val
}
func (p *LxhDriver) SetName(val string) {
	p.Name = val
}
func (p *LxhDriver) SetNickName(val string) {
	p.NickName = val
}
func (p *LxhDriver) SetAllAcount(val float64) {
	p.AllAcount = val
}
func (p *LxhDriver) SetCarAge(val int32) {
	p.CarAge = val
}
func (p *LxhDriver) SetStatus(val string) {
	p.Status = val
}
func (p *LxhDriver) SetMobile(val string) {
	p.Mobile = val
}
func (p *LxhDriver) SetFileId(val int32) {
	p.FileId = val
}

func (p *LxhDriver) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LxhDriver(%+v)", *p)
}

var fieldIDToName_LxhDriver = map[int16]string{
	1: "Id",
	2: "Name",
	3: "NickName",
	4: "AllAcount",
	5: "CarAge",
	6: "Status",
	7: "Mobile",
	8: "FileId",
}

type SendSmsDriverReq struct {
	Mobile string `thrift:"Mobile,1" frugal:"1,default,string" json:"Mobile"`
	Source string `thrift:"Source,2" frugal:"2,default,string" json:"Source"`
}

func NewSendSmsDriverReq() *SendSmsDriverReq {
	return &SendSmsDriverReq{}
}

func (p *SendSmsDriverReq) InitDefault() {
}

func (p *SendSmsDriverReq) GetMobile() (v string) {
	return p.Mobile
}

func (p *SendSmsDriverReq) GetSource() (v string) {
	return p.Source
}
func (p *SendSmsDriverReq) SetMobile(val string) {
	p.Mobile = val
}
func (p *SendSmsDriverReq) SetSource(val string) {
	p.Source = val
}

func (p *SendSmsDriverReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SendSmsDriverReq(%+v)", *p)
}

var fieldIDToName_SendSmsDriverReq = map[int16]string{
	1: "Mobile",
	2: "Source",
}

type SendSmsDriverResp struct {
	Message string `thrift:"Message,1" frugal:"1,default,string" json:"Message"`
	Code    int64  `thrift:"Code,2" frugal:"2,default,i64" json:"Code"`
}

func NewSendSmsDriverResp() *SendSmsDriverResp {
	return &SendSmsDriverResp{}
}

func (p *SendSmsDriverResp) InitDefault() {
}

func (p *SendSmsDriverResp) GetMessage() (v string) {
	return p.Message
}

func (p *SendSmsDriverResp) GetCode() (v int64) {
	return p.Code
}
func (p *SendSmsDriverResp) SetMessage(val string) {
	p.Message = val
}
func (p *SendSmsDriverResp) SetCode(val int64) {
	p.Code = val
}

func (p *SendSmsDriverResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SendSmsDriverResp(%+v)", *p)
}

var fieldIDToName_SendSmsDriverResp = map[int16]string{
	1: "Message",
	2: "Code",
}

type DriverRegisterReq struct {
	Mobile  string `thrift:"Mobile,1" frugal:"1,default,string" json:"Mobile"`
	SmsCode string `thrift:"SmsCode,2" frugal:"2,default,string" json:"SmsCode"`
	Name    string `thrift:"Name,3" frugal:"3,default,string" json:"Name"`
}

func NewDriverRegisterReq() *DriverRegisterReq {
	return &DriverRegisterReq{}
}

func (p *DriverRegisterReq) InitDefault() {
}

func (p *DriverRegisterReq) GetMobile() (v string) {
	return p.Mobile
}

func (p *DriverRegisterReq) GetSmsCode() (v string) {
	return p.SmsCode
}

func (p *DriverRegisterReq) GetName() (v string) {
	return p.Name
}
func (p *DriverRegisterReq) SetMobile(val string) {
	p.Mobile = val
}
func (p *DriverRegisterReq) SetSmsCode(val string) {
	p.SmsCode = val
}
func (p *DriverRegisterReq) SetName(val string) {
	p.Name = val
}

func (p *DriverRegisterReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DriverRegisterReq(%+v)", *p)
}

var fieldIDToName_DriverRegisterReq = map[int16]string{
	1: "Mobile",
	2: "SmsCode",
	3: "Name",
}

type DriverRegisterResp struct {
	Message string `thrift:"Message,1" frugal:"1,default,string" json:"Message"`
	Code    int64  `thrift:"Code,2" frugal:"2,default,i64" json:"Code"`
}

func NewDriverRegisterResp() *DriverRegisterResp {
	return &DriverRegisterResp{}
}

func (p *DriverRegisterResp) InitDefault() {
}

func (p *DriverRegisterResp) GetMessage() (v string) {
	return p.Message
}

func (p *DriverRegisterResp) GetCode() (v int64) {
	return p.Code
}
func (p *DriverRegisterResp) SetMessage(val string) {
	p.Message = val
}
func (p *DriverRegisterResp) SetCode(val int64) {
	p.Code = val
}

func (p *DriverRegisterResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DriverRegisterResp(%+v)", *p)
}

var fieldIDToName_DriverRegisterResp = map[int16]string{
	1: "Message",
	2: "Code",
}

type GetDriverInfoReq struct {
	DriverID int32 `thrift:"DriverID,1" frugal:"1,default,i32" json:"DriverID"`
}

func NewGetDriverInfoReq() *GetDriverInfoReq {
	return &GetDriverInfoReq{}
}

func (p *GetDriverInfoReq) InitDefault() {
}

func (p *GetDriverInfoReq) GetDriverID() (v int32) {
	return p.DriverID
}
func (p *GetDriverInfoReq) SetDriverID(val int32) {
	p.DriverID = val
}

func (p *GetDriverInfoReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetDriverInfoReq(%+v)", *p)
}

var fieldIDToName_GetDriverInfoReq = map[int16]string{
	1: "DriverID",
}

type GetDriverInfoResp struct {
	Message string     `thrift:"Message,1" frugal:"1,default,string" json:"Message"`
	Code    int64      `thrift:"Code,2" frugal:"2,default,i64" json:"Code"`
	Driver  *LxhDriver `thrift:"Driver,3" frugal:"3,default,LxhDriver" json:"Driver"`
}

func NewGetDriverInfoResp() *GetDriverInfoResp {
	return &GetDriverInfoResp{}
}

func (p *GetDriverInfoResp) InitDefault() {
}

func (p *GetDriverInfoResp) GetMessage() (v string) {
	return p.Message
}

func (p *GetDriverInfoResp) GetCode() (v int64) {
	return p.Code
}

var GetDriverInfoResp_Driver_DEFAULT *LxhDriver

func (p *GetDriverInfoResp) GetDriver() (v *LxhDriver) {
	if !p.IsSetDriver() {
		return GetDriverInfoResp_Driver_DEFAULT
	}
	return p.Driver
}
func (p *GetDriverInfoResp) SetMessage(val string) {
	p.Message = val
}
func (p *GetDriverInfoResp) SetCode(val int64) {
	p.Code = val
}
func (p *GetDriverInfoResp) SetDriver(val *LxhDriver) {
	p.Driver = val
}

func (p *GetDriverInfoResp) IsSetDriver() bool {
	return p.Driver != nil
}

func (p *GetDriverInfoResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetDriverInfoResp(%+v)", *p)
}

var fieldIDToName_GetDriverInfoResp = map[int16]string{
	1: "Message",
	2: "Code",
	3: "Driver",
}

type UpdateDriverStatusReq struct {
	DriverID   int32 `thrift:"DriverID,1" frugal:"1,default,i32" json:"DriverID"`
	WorkStatus int16 `thrift:"WorkStatus,2" frugal:"2,default,i16" json:"WorkStatus"`
}

func NewUpdateDriverStatusReq() *UpdateDriverStatusReq {
	return &UpdateDriverStatusReq{}
}

func (p *UpdateDriverStatusReq) InitDefault() {
}

func (p *UpdateDriverStatusReq) GetDriverID() (v int32) {
	return p.DriverID
}

func (p *UpdateDriverStatusReq) GetWorkStatus() (v int16) {
	return p.WorkStatus
}
func (p *UpdateDriverStatusReq) SetDriverID(val int32) {
	p.DriverID = val
}
func (p *UpdateDriverStatusReq) SetWorkStatus(val int16) {
	p.WorkStatus = val
}

func (p *UpdateDriverStatusReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdateDriverStatusReq(%+v)", *p)
}

var fieldIDToName_UpdateDriverStatusReq = map[int16]string{
	1: "DriverID",
	2: "WorkStatus",
}

type UpdateDriverStatusResp struct {
	Message string `thrift:"Message,1" frugal:"1,default,string" json:"Message"`
	Code    int16  `thrift:"Code,2" frugal:"2,default,i16" json:"Code"`
}

func NewUpdateDriverStatusResp() *UpdateDriverStatusResp {
	return &UpdateDriverStatusResp{}
}

func (p *UpdateDriverStatusResp) InitDefault() {
}

func (p *UpdateDriverStatusResp) GetMessage() (v string) {
	return p.Message
}

func (p *UpdateDriverStatusResp) GetCode() (v int16) {
	return p.Code
}
func (p *UpdateDriverStatusResp) SetMessage(val string) {
	p.Message = val
}
func (p *UpdateDriverStatusResp) SetCode(val int16) {
	p.Code = val
}

func (p *UpdateDriverStatusResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdateDriverStatusResp(%+v)", *p)
}

var fieldIDToName_UpdateDriverStatusResp = map[int16]string{
	1: "Message",
	2: "Code",
}

type GetAwaitOrderReq struct {
	DriverID int32 `thrift:"DriverID,1" frugal:"1,default,i32" json:"DriverID"`
	Distance int32 `thrift:"Distance,2" frugal:"2,default,i32" json:"Distance"`
}

func NewGetAwaitOrderReq() *GetAwaitOrderReq {
	return &GetAwaitOrderReq{}
}

func (p *GetAwaitOrderReq) InitDefault() {
}

func (p *GetAwaitOrderReq) GetDriverID() (v int32) {
	return p.DriverID
}

func (p *GetAwaitOrderReq) GetDistance() (v int32) {
	return p.Distance
}
func (p *GetAwaitOrderReq) SetDriverID(val int32) {
	p.DriverID = val
}
func (p *GetAwaitOrderReq) SetDistance(val int32) {
	p.Distance = val
}

func (p *GetAwaitOrderReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetAwaitOrderReq(%+v)", *p)
}

var fieldIDToName_GetAwaitOrderReq = map[int16]string{
	1: "DriverID",
	2: "Distance",
}

type GetAwaitOrderResp struct {
	Message string `thrift:"Message,1" frugal:"1,default,string" json:"Message"`
	Code    int16  `thrift:"Code,2" frugal:"2,default,i16" json:"Code"`
}

func NewGetAwaitOrderResp() *GetAwaitOrderResp {
	return &GetAwaitOrderResp{}
}

func (p *GetAwaitOrderResp) InitDefault() {
}

func (p *GetAwaitOrderResp) GetMessage() (v string) {
	return p.Message
}

func (p *GetAwaitOrderResp) GetCode() (v int16) {
	return p.Code
}
func (p *GetAwaitOrderResp) SetMessage(val string) {
	p.Message = val
}
func (p *GetAwaitOrderResp) SetCode(val int16) {
	p.Code = val
}

func (p *GetAwaitOrderResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetAwaitOrderResp(%+v)", *p)
}

var fieldIDToName_GetAwaitOrderResp = map[int16]string{
	1: "Message",
	2: "Code",
}

type AccessOrderReq struct {
	OrderID  int32 `thrift:"OrderID,1" frugal:"1,default,i32" json:"OrderID"`
	DriverID int32 `thrift:"DriverID,2" frugal:"2,default,i32" json:"DriverID"`
}

func NewAccessOrderReq() *AccessOrderReq {
	return &AccessOrderReq{}
}

func (p *AccessOrderReq) InitDefault() {
}

func (p *AccessOrderReq) GetOrderID() (v int32) {
	return p.OrderID
}

func (p *AccessOrderReq) GetDriverID() (v int32) {
	return p.DriverID
}
func (p *AccessOrderReq) SetOrderID(val int32) {
	p.OrderID = val
}
func (p *AccessOrderReq) SetDriverID(val int32) {
	p.DriverID = val
}

func (p *AccessOrderReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AccessOrderReq(%+v)", *p)
}

var fieldIDToName_AccessOrderReq = map[int16]string{
	1: "OrderID",
	2: "DriverID",
}

type AccessOrderResp struct {
	Message string `thrift:"Message,1" frugal:"1,default,string" json:"Message"`
	Code    int16  `thrift:"Code,2" frugal:"2,default,i16" json:"Code"`
}

func NewAccessOrderResp() *AccessOrderResp {
	return &AccessOrderResp{}
}

func (p *AccessOrderResp) InitDefault() {
}

func (p *AccessOrderResp) GetMessage() (v string) {
	return p.Message
}

func (p *AccessOrderResp) GetCode() (v int16) {
	return p.Code
}
func (p *AccessOrderResp) SetMessage(val string) {
	p.Message = val
}
func (p *AccessOrderResp) SetCode(val int16) {
	p.Code = val
}

func (p *AccessOrderResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AccessOrderResp(%+v)", *p)
}

var fieldIDToName_AccessOrderResp = map[int16]string{
	1: "Message",
	2: "Code",
}

type RejectionOrderReq struct {
	OrderID  int32 `thrift:"OrderID,1" frugal:"1,default,i32" json:"OrderID"`
	DriverID int32 `thrift:"DriverID,2" frugal:"2,default,i32" json:"DriverID"`
}

func NewRejectionOrderReq() *RejectionOrderReq {
	return &RejectionOrderReq{}
}

func (p *RejectionOrderReq) InitDefault() {
}

func (p *RejectionOrderReq) GetOrderID() (v int32) {
	return p.OrderID
}

func (p *RejectionOrderReq) GetDriverID() (v int32) {
	return p.DriverID
}
func (p *RejectionOrderReq) SetOrderID(val int32) {
	p.OrderID = val
}
func (p *RejectionOrderReq) SetDriverID(val int32) {
	p.DriverID = val
}

func (p *RejectionOrderReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RejectionOrderReq(%+v)", *p)
}

var fieldIDToName_RejectionOrderReq = map[int16]string{
	1: "OrderID",
	2: "DriverID",
}

type RejectionOrderResp struct {
	Message string `thrift:"Message,1" frugal:"1,default,string" json:"Message"`
	Code    int16  `thrift:"Code,2" frugal:"2,default,i16" json:"Code"`
}

func NewRejectionOrderResp() *RejectionOrderResp {
	return &RejectionOrderResp{}
}

func (p *RejectionOrderResp) InitDefault() {
}

func (p *RejectionOrderResp) GetMessage() (v string) {
	return p.Message
}

func (p *RejectionOrderResp) GetCode() (v int16) {
	return p.Code
}
func (p *RejectionOrderResp) SetMessage(val string) {
	p.Message = val
}
func (p *RejectionOrderResp) SetCode(val int16) {
	p.Code = val
}

func (p *RejectionOrderResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RejectionOrderResp(%+v)", *p)
}

var fieldIDToName_RejectionOrderResp = map[int16]string{
	1: "Message",
	2: "Code",
}

type StartTripReq struct {
	DriverID int32 `thrift:"DriverID,1" frugal:"1,default,i32" json:"DriverID"`
	OrderID  int32 `thrift:"OrderID,2" frugal:"2,default,i32" json:"OrderID"`
}

func NewStartTripReq() *StartTripReq {
	return &StartTripReq{}
}

func (p *StartTripReq) InitDefault() {
}

func (p *StartTripReq) GetDriverID() (v int32) {
	return p.DriverID
}

func (p *StartTripReq) GetOrderID() (v int32) {
	return p.OrderID
}
func (p *StartTripReq) SetDriverID(val int32) {
	p.DriverID = val
}
func (p *StartTripReq) SetOrderID(val int32) {
	p.OrderID = val
}

func (p *StartTripReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("StartTripReq(%+v)", *p)
}

var fieldIDToName_StartTripReq = map[int16]string{
	1: "DriverID",
	2: "OrderID",
}

type StartTripResp struct {
	Message string `thrift:"Message,1" frugal:"1,default,string" json:"Message"`
	Code    int16  `thrift:"Code,2" frugal:"2,default,i16" json:"Code"`
}

func NewStartTripResp() *StartTripResp {
	return &StartTripResp{}
}

func (p *StartTripResp) InitDefault() {
}

func (p *StartTripResp) GetMessage() (v string) {
	return p.Message
}

func (p *StartTripResp) GetCode() (v int16) {
	return p.Code
}
func (p *StartTripResp) SetMessage(val string) {
	p.Message = val
}
func (p *StartTripResp) SetCode(val int16) {
	p.Code = val
}

func (p *StartTripResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("StartTripResp(%+v)", *p)
}

var fieldIDToName_StartTripResp = map[int16]string{
	1: "Message",
	2: "Code",
}

type EndTripReq struct {
	DriverID int32 `thrift:"DriverID,1" frugal:"1,default,i32" json:"DriverID"`
	OrderID  int32 `thrift:"OrderID,2" frugal:"2,default,i32" json:"OrderID"`
}

func NewEndTripReq() *EndTripReq {
	return &EndTripReq{}
}

func (p *EndTripReq) InitDefault() {
}

func (p *EndTripReq) GetDriverID() (v int32) {
	return p.DriverID
}

func (p *EndTripReq) GetOrderID() (v int32) {
	return p.OrderID
}
func (p *EndTripReq) SetDriverID(val int32) {
	p.DriverID = val
}
func (p *EndTripReq) SetOrderID(val int32) {
	p.OrderID = val
}

func (p *EndTripReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("EndTripReq(%+v)", *p)
}

var fieldIDToName_EndTripReq = map[int16]string{
	1: "DriverID",
	2: "OrderID",
}

type EndTripResp struct {
	Message string `thrift:"Message,1" frugal:"1,default,string" json:"Message"`
	Code    int16  `thrift:"Code,2" frugal:"2,default,i16" json:"Code"`
}

func NewEndTripResp() *EndTripResp {
	return &EndTripResp{}
}

func (p *EndTripResp) InitDefault() {
}

func (p *EndTripResp) GetMessage() (v string) {
	return p.Message
}

func (p *EndTripResp) GetCode() (v int16) {
	return p.Code
}
func (p *EndTripResp) SetMessage(val string) {
	p.Message = val
}
func (p *EndTripResp) SetCode(val int16) {
	p.Code = val
}

func (p *EndTripResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("EndTripResp(%+v)", *p)
}

var fieldIDToName_EndTripResp = map[int16]string{
	1: "Message",
	2: "Code",
}

type ArriveLocationReq struct {
	DriverID int32 `thrift:"DriverID,1" frugal:"1,default,i32" json:"DriverID"`
	OrderID  int32 `thrift:"OrderID,2" frugal:"2,default,i32" json:"OrderID"`
}

func NewArriveLocationReq() *ArriveLocationReq {
	return &ArriveLocationReq{}
}

func (p *ArriveLocationReq) InitDefault() {
}

func (p *ArriveLocationReq) GetDriverID() (v int32) {
	return p.DriverID
}

func (p *ArriveLocationReq) GetOrderID() (v int32) {
	return p.OrderID
}
func (p *ArriveLocationReq) SetDriverID(val int32) {
	p.DriverID = val
}
func (p *ArriveLocationReq) SetOrderID(val int32) {
	p.OrderID = val
}

func (p *ArriveLocationReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ArriveLocationReq(%+v)", *p)
}

var fieldIDToName_ArriveLocationReq = map[int16]string{
	1: "DriverID",
	2: "OrderID",
}

type ArriveLocationResp struct {
	Message string `thrift:"Message,1" frugal:"1,default,string" json:"Message"`
	Code    int16  `thrift:"Code,2" frugal:"2,default,i16" json:"Code"`
}

func NewArriveLocationResp() *ArriveLocationResp {
	return &ArriveLocationResp{}
}

func (p *ArriveLocationResp) InitDefault() {
}

func (p *ArriveLocationResp) GetMessage() (v string) {
	return p.Message
}

func (p *ArriveLocationResp) GetCode() (v int16) {
	return p.Code
}
func (p *ArriveLocationResp) SetMessage(val string) {
	p.Message = val
}
func (p *ArriveLocationResp) SetCode(val int16) {
	p.Code = val
}

func (p *ArriveLocationResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ArriveLocationResp(%+v)", *p)
}

var fieldIDToName_ArriveLocationResp = map[int16]string{
	1: "Message",
	2: "Code",
}

type DriverServer interface {
	SendSms(ctx context.Context, req *SendSmsDriverReq) (r *SendSmsDriverResp, err error)

	Register(ctx context.Context, req *DriverRegisterReq) (r *DriverRegisterResp, err error)

	GetDriverInfo(ctx context.Context, req *GetDriverInfoReq) (r *GetDriverInfoResp, err error)

	UpdateDriverStatus(ctx context.Context, req *UpdateDriverStatusReq) (r *UpdateDriverStatusResp, err error)

	GetAwaitOrder(ctx context.Context, req *GetAwaitOrderReq) (r *GetAwaitOrderResp, err error)

	AccessOrder(ctx context.Context, req *AccessOrderReq) (r *AccessOrderResp, err error)

	RejectionOrder(ctx context.Context, req *RejectionOrderReq) (r *RejectionOrderResp, err error)

	ArriveLocation(ctx context.Context, req *ArriveLocationReq) (r *ArriveLocationResp, err error)

	StartTrip(ctx context.Context, req *StartTripReq) (r *StartTripResp, err error)

	EndTrip(ctx context.Context, req *EndTripReq) (r *EndTripResp, err error)
}

type DriverServerSendSmsArgs struct {
	Req *SendSmsDriverReq `thrift:"req,1" frugal:"1,default,SendSmsDriverReq" json:"req"`
}

func NewDriverServerSendSmsArgs() *DriverServerSendSmsArgs {
	return &DriverServerSendSmsArgs{}
}

func (p *DriverServerSendSmsArgs) InitDefault() {
}

var DriverServerSendSmsArgs_Req_DEFAULT *SendSmsDriverReq

func (p *DriverServerSendSmsArgs) GetReq() (v *SendSmsDriverReq) {
	if !p.IsSetReq() {
		return DriverServerSendSmsArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *DriverServerSendSmsArgs) SetReq(val *SendSmsDriverReq) {
	p.Req = val
}

func (p *DriverServerSendSmsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *DriverServerSendSmsArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DriverServerSendSmsArgs(%+v)", *p)
}

var fieldIDToName_DriverServerSendSmsArgs = map[int16]string{
	1: "req",
}

type DriverServerSendSmsResult struct {
	Success *SendSmsDriverResp `thrift:"success,0,optional" frugal:"0,optional,SendSmsDriverResp" json:"success,omitempty"`
}

func NewDriverServerSendSmsResult() *DriverServerSendSmsResult {
	return &DriverServerSendSmsResult{}
}

func (p *DriverServerSendSmsResult) InitDefault() {
}

var DriverServerSendSmsResult_Success_DEFAULT *SendSmsDriverResp

func (p *DriverServerSendSmsResult) GetSuccess() (v *SendSmsDriverResp) {
	if !p.IsSetSuccess() {
		return DriverServerSendSmsResult_Success_DEFAULT
	}
	return p.Success
}
func (p *DriverServerSendSmsResult) SetSuccess(x interface{}) {
	p.Success = x.(*SendSmsDriverResp)
}

func (p *DriverServerSendSmsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *DriverServerSendSmsResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DriverServerSendSmsResult(%+v)", *p)
}

var fieldIDToName_DriverServerSendSmsResult = map[int16]string{
	0: "success",
}

type DriverServerRegisterArgs struct {
	Req *DriverRegisterReq `thrift:"req,1" frugal:"1,default,DriverRegisterReq" json:"req"`
}

func NewDriverServerRegisterArgs() *DriverServerRegisterArgs {
	return &DriverServerRegisterArgs{}
}

func (p *DriverServerRegisterArgs) InitDefault() {
}

var DriverServerRegisterArgs_Req_DEFAULT *DriverRegisterReq

func (p *DriverServerRegisterArgs) GetReq() (v *DriverRegisterReq) {
	if !p.IsSetReq() {
		return DriverServerRegisterArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *DriverServerRegisterArgs) SetReq(val *DriverRegisterReq) {
	p.Req = val
}

func (p *DriverServerRegisterArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *DriverServerRegisterArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DriverServerRegisterArgs(%+v)", *p)
}

var fieldIDToName_DriverServerRegisterArgs = map[int16]string{
	1: "req",
}

type DriverServerRegisterResult struct {
	Success *DriverRegisterResp `thrift:"success,0,optional" frugal:"0,optional,DriverRegisterResp" json:"success,omitempty"`
}

func NewDriverServerRegisterResult() *DriverServerRegisterResult {
	return &DriverServerRegisterResult{}
}

func (p *DriverServerRegisterResult) InitDefault() {
}

var DriverServerRegisterResult_Success_DEFAULT *DriverRegisterResp

func (p *DriverServerRegisterResult) GetSuccess() (v *DriverRegisterResp) {
	if !p.IsSetSuccess() {
		return DriverServerRegisterResult_Success_DEFAULT
	}
	return p.Success
}
func (p *DriverServerRegisterResult) SetSuccess(x interface{}) {
	p.Success = x.(*DriverRegisterResp)
}

func (p *DriverServerRegisterResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *DriverServerRegisterResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DriverServerRegisterResult(%+v)", *p)
}

var fieldIDToName_DriverServerRegisterResult = map[int16]string{
	0: "success",
}

type DriverServerGetDriverInfoArgs struct {
	Req *GetDriverInfoReq `thrift:"req,1" frugal:"1,default,GetDriverInfoReq" json:"req"`
}

func NewDriverServerGetDriverInfoArgs() *DriverServerGetDriverInfoArgs {
	return &DriverServerGetDriverInfoArgs{}
}

func (p *DriverServerGetDriverInfoArgs) InitDefault() {
}

var DriverServerGetDriverInfoArgs_Req_DEFAULT *GetDriverInfoReq

func (p *DriverServerGetDriverInfoArgs) GetReq() (v *GetDriverInfoReq) {
	if !p.IsSetReq() {
		return DriverServerGetDriverInfoArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *DriverServerGetDriverInfoArgs) SetReq(val *GetDriverInfoReq) {
	p.Req = val
}

func (p *DriverServerGetDriverInfoArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *DriverServerGetDriverInfoArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DriverServerGetDriverInfoArgs(%+v)", *p)
}

var fieldIDToName_DriverServerGetDriverInfoArgs = map[int16]string{
	1: "req",
}

type DriverServerGetDriverInfoResult struct {
	Success *GetDriverInfoResp `thrift:"success,0,optional" frugal:"0,optional,GetDriverInfoResp" json:"success,omitempty"`
}

func NewDriverServerGetDriverInfoResult() *DriverServerGetDriverInfoResult {
	return &DriverServerGetDriverInfoResult{}
}

func (p *DriverServerGetDriverInfoResult) InitDefault() {
}

var DriverServerGetDriverInfoResult_Success_DEFAULT *GetDriverInfoResp

func (p *DriverServerGetDriverInfoResult) GetSuccess() (v *GetDriverInfoResp) {
	if !p.IsSetSuccess() {
		return DriverServerGetDriverInfoResult_Success_DEFAULT
	}
	return p.Success
}
func (p *DriverServerGetDriverInfoResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetDriverInfoResp)
}

func (p *DriverServerGetDriverInfoResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *DriverServerGetDriverInfoResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DriverServerGetDriverInfoResult(%+v)", *p)
}

var fieldIDToName_DriverServerGetDriverInfoResult = map[int16]string{
	0: "success",
}

type DriverServerUpdateDriverStatusArgs struct {
	Req *UpdateDriverStatusReq `thrift:"req,1" frugal:"1,default,UpdateDriverStatusReq" json:"req"`
}

func NewDriverServerUpdateDriverStatusArgs() *DriverServerUpdateDriverStatusArgs {
	return &DriverServerUpdateDriverStatusArgs{}
}

func (p *DriverServerUpdateDriverStatusArgs) InitDefault() {
}

var DriverServerUpdateDriverStatusArgs_Req_DEFAULT *UpdateDriverStatusReq

func (p *DriverServerUpdateDriverStatusArgs) GetReq() (v *UpdateDriverStatusReq) {
	if !p.IsSetReq() {
		return DriverServerUpdateDriverStatusArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *DriverServerUpdateDriverStatusArgs) SetReq(val *UpdateDriverStatusReq) {
	p.Req = val
}

func (p *DriverServerUpdateDriverStatusArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *DriverServerUpdateDriverStatusArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DriverServerUpdateDriverStatusArgs(%+v)", *p)
}

var fieldIDToName_DriverServerUpdateDriverStatusArgs = map[int16]string{
	1: "req",
}

type DriverServerUpdateDriverStatusResult struct {
	Success *UpdateDriverStatusResp `thrift:"success,0,optional" frugal:"0,optional,UpdateDriverStatusResp" json:"success,omitempty"`
}

func NewDriverServerUpdateDriverStatusResult() *DriverServerUpdateDriverStatusResult {
	return &DriverServerUpdateDriverStatusResult{}
}

func (p *DriverServerUpdateDriverStatusResult) InitDefault() {
}

var DriverServerUpdateDriverStatusResult_Success_DEFAULT *UpdateDriverStatusResp

func (p *DriverServerUpdateDriverStatusResult) GetSuccess() (v *UpdateDriverStatusResp) {
	if !p.IsSetSuccess() {
		return DriverServerUpdateDriverStatusResult_Success_DEFAULT
	}
	return p.Success
}
func (p *DriverServerUpdateDriverStatusResult) SetSuccess(x interface{}) {
	p.Success = x.(*UpdateDriverStatusResp)
}

func (p *DriverServerUpdateDriverStatusResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *DriverServerUpdateDriverStatusResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DriverServerUpdateDriverStatusResult(%+v)", *p)
}

var fieldIDToName_DriverServerUpdateDriverStatusResult = map[int16]string{
	0: "success",
}

type DriverServerGetAwaitOrderArgs struct {
	Req *GetAwaitOrderReq `thrift:"req,1" frugal:"1,default,GetAwaitOrderReq" json:"req"`
}

func NewDriverServerGetAwaitOrderArgs() *DriverServerGetAwaitOrderArgs {
	return &DriverServerGetAwaitOrderArgs{}
}

func (p *DriverServerGetAwaitOrderArgs) InitDefault() {
}

var DriverServerGetAwaitOrderArgs_Req_DEFAULT *GetAwaitOrderReq

func (p *DriverServerGetAwaitOrderArgs) GetReq() (v *GetAwaitOrderReq) {
	if !p.IsSetReq() {
		return DriverServerGetAwaitOrderArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *DriverServerGetAwaitOrderArgs) SetReq(val *GetAwaitOrderReq) {
	p.Req = val
}

func (p *DriverServerGetAwaitOrderArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *DriverServerGetAwaitOrderArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DriverServerGetAwaitOrderArgs(%+v)", *p)
}

var fieldIDToName_DriverServerGetAwaitOrderArgs = map[int16]string{
	1: "req",
}

type DriverServerGetAwaitOrderResult struct {
	Success *GetAwaitOrderResp `thrift:"success,0,optional" frugal:"0,optional,GetAwaitOrderResp" json:"success,omitempty"`
}

func NewDriverServerGetAwaitOrderResult() *DriverServerGetAwaitOrderResult {
	return &DriverServerGetAwaitOrderResult{}
}

func (p *DriverServerGetAwaitOrderResult) InitDefault() {
}

var DriverServerGetAwaitOrderResult_Success_DEFAULT *GetAwaitOrderResp

func (p *DriverServerGetAwaitOrderResult) GetSuccess() (v *GetAwaitOrderResp) {
	if !p.IsSetSuccess() {
		return DriverServerGetAwaitOrderResult_Success_DEFAULT
	}
	return p.Success
}
func (p *DriverServerGetAwaitOrderResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetAwaitOrderResp)
}

func (p *DriverServerGetAwaitOrderResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *DriverServerGetAwaitOrderResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DriverServerGetAwaitOrderResult(%+v)", *p)
}

var fieldIDToName_DriverServerGetAwaitOrderResult = map[int16]string{
	0: "success",
}

type DriverServerAccessOrderArgs struct {
	Req *AccessOrderReq `thrift:"req,1" frugal:"1,default,AccessOrderReq" json:"req"`
}

func NewDriverServerAccessOrderArgs() *DriverServerAccessOrderArgs {
	return &DriverServerAccessOrderArgs{}
}

func (p *DriverServerAccessOrderArgs) InitDefault() {
}

var DriverServerAccessOrderArgs_Req_DEFAULT *AccessOrderReq

func (p *DriverServerAccessOrderArgs) GetReq() (v *AccessOrderReq) {
	if !p.IsSetReq() {
		return DriverServerAccessOrderArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *DriverServerAccessOrderArgs) SetReq(val *AccessOrderReq) {
	p.Req = val
}

func (p *DriverServerAccessOrderArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *DriverServerAccessOrderArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DriverServerAccessOrderArgs(%+v)", *p)
}

var fieldIDToName_DriverServerAccessOrderArgs = map[int16]string{
	1: "req",
}

type DriverServerAccessOrderResult struct {
	Success *AccessOrderResp `thrift:"success,0,optional" frugal:"0,optional,AccessOrderResp" json:"success,omitempty"`
}

func NewDriverServerAccessOrderResult() *DriverServerAccessOrderResult {
	return &DriverServerAccessOrderResult{}
}

func (p *DriverServerAccessOrderResult) InitDefault() {
}

var DriverServerAccessOrderResult_Success_DEFAULT *AccessOrderResp

func (p *DriverServerAccessOrderResult) GetSuccess() (v *AccessOrderResp) {
	if !p.IsSetSuccess() {
		return DriverServerAccessOrderResult_Success_DEFAULT
	}
	return p.Success
}
func (p *DriverServerAccessOrderResult) SetSuccess(x interface{}) {
	p.Success = x.(*AccessOrderResp)
}

func (p *DriverServerAccessOrderResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *DriverServerAccessOrderResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DriverServerAccessOrderResult(%+v)", *p)
}

var fieldIDToName_DriverServerAccessOrderResult = map[int16]string{
	0: "success",
}

type DriverServerRejectionOrderArgs struct {
	Req *RejectionOrderReq `thrift:"req,1" frugal:"1,default,RejectionOrderReq" json:"req"`
}

func NewDriverServerRejectionOrderArgs() *DriverServerRejectionOrderArgs {
	return &DriverServerRejectionOrderArgs{}
}

func (p *DriverServerRejectionOrderArgs) InitDefault() {
}

var DriverServerRejectionOrderArgs_Req_DEFAULT *RejectionOrderReq

func (p *DriverServerRejectionOrderArgs) GetReq() (v *RejectionOrderReq) {
	if !p.IsSetReq() {
		return DriverServerRejectionOrderArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *DriverServerRejectionOrderArgs) SetReq(val *RejectionOrderReq) {
	p.Req = val
}

func (p *DriverServerRejectionOrderArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *DriverServerRejectionOrderArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DriverServerRejectionOrderArgs(%+v)", *p)
}

var fieldIDToName_DriverServerRejectionOrderArgs = map[int16]string{
	1: "req",
}

type DriverServerRejectionOrderResult struct {
	Success *RejectionOrderResp `thrift:"success,0,optional" frugal:"0,optional,RejectionOrderResp" json:"success,omitempty"`
}

func NewDriverServerRejectionOrderResult() *DriverServerRejectionOrderResult {
	return &DriverServerRejectionOrderResult{}
}

func (p *DriverServerRejectionOrderResult) InitDefault() {
}

var DriverServerRejectionOrderResult_Success_DEFAULT *RejectionOrderResp

func (p *DriverServerRejectionOrderResult) GetSuccess() (v *RejectionOrderResp) {
	if !p.IsSetSuccess() {
		return DriverServerRejectionOrderResult_Success_DEFAULT
	}
	return p.Success
}
func (p *DriverServerRejectionOrderResult) SetSuccess(x interface{}) {
	p.Success = x.(*RejectionOrderResp)
}

func (p *DriverServerRejectionOrderResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *DriverServerRejectionOrderResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DriverServerRejectionOrderResult(%+v)", *p)
}

var fieldIDToName_DriverServerRejectionOrderResult = map[int16]string{
	0: "success",
}

type DriverServerArriveLocationArgs struct {
	Req *ArriveLocationReq `thrift:"req,1" frugal:"1,default,ArriveLocationReq" json:"req"`
}

func NewDriverServerArriveLocationArgs() *DriverServerArriveLocationArgs {
	return &DriverServerArriveLocationArgs{}
}

func (p *DriverServerArriveLocationArgs) InitDefault() {
}

var DriverServerArriveLocationArgs_Req_DEFAULT *ArriveLocationReq

func (p *DriverServerArriveLocationArgs) GetReq() (v *ArriveLocationReq) {
	if !p.IsSetReq() {
		return DriverServerArriveLocationArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *DriverServerArriveLocationArgs) SetReq(val *ArriveLocationReq) {
	p.Req = val
}

func (p *DriverServerArriveLocationArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *DriverServerArriveLocationArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DriverServerArriveLocationArgs(%+v)", *p)
}

var fieldIDToName_DriverServerArriveLocationArgs = map[int16]string{
	1: "req",
}

type DriverServerArriveLocationResult struct {
	Success *ArriveLocationResp `thrift:"success,0,optional" frugal:"0,optional,ArriveLocationResp" json:"success,omitempty"`
}

func NewDriverServerArriveLocationResult() *DriverServerArriveLocationResult {
	return &DriverServerArriveLocationResult{}
}

func (p *DriverServerArriveLocationResult) InitDefault() {
}

var DriverServerArriveLocationResult_Success_DEFAULT *ArriveLocationResp

func (p *DriverServerArriveLocationResult) GetSuccess() (v *ArriveLocationResp) {
	if !p.IsSetSuccess() {
		return DriverServerArriveLocationResult_Success_DEFAULT
	}
	return p.Success
}
func (p *DriverServerArriveLocationResult) SetSuccess(x interface{}) {
	p.Success = x.(*ArriveLocationResp)
}

func (p *DriverServerArriveLocationResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *DriverServerArriveLocationResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DriverServerArriveLocationResult(%+v)", *p)
}

var fieldIDToName_DriverServerArriveLocationResult = map[int16]string{
	0: "success",
}

type DriverServerStartTripArgs struct {
	Req *StartTripReq `thrift:"req,1" frugal:"1,default,StartTripReq" json:"req"`
}

func NewDriverServerStartTripArgs() *DriverServerStartTripArgs {
	return &DriverServerStartTripArgs{}
}

func (p *DriverServerStartTripArgs) InitDefault() {
}

var DriverServerStartTripArgs_Req_DEFAULT *StartTripReq

func (p *DriverServerStartTripArgs) GetReq() (v *StartTripReq) {
	if !p.IsSetReq() {
		return DriverServerStartTripArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *DriverServerStartTripArgs) SetReq(val *StartTripReq) {
	p.Req = val
}

func (p *DriverServerStartTripArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *DriverServerStartTripArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DriverServerStartTripArgs(%+v)", *p)
}

var fieldIDToName_DriverServerStartTripArgs = map[int16]string{
	1: "req",
}

type DriverServerStartTripResult struct {
	Success *StartTripResp `thrift:"success,0,optional" frugal:"0,optional,StartTripResp" json:"success,omitempty"`
}

func NewDriverServerStartTripResult() *DriverServerStartTripResult {
	return &DriverServerStartTripResult{}
}

func (p *DriverServerStartTripResult) InitDefault() {
}

var DriverServerStartTripResult_Success_DEFAULT *StartTripResp

func (p *DriverServerStartTripResult) GetSuccess() (v *StartTripResp) {
	if !p.IsSetSuccess() {
		return DriverServerStartTripResult_Success_DEFAULT
	}
	return p.Success
}
func (p *DriverServerStartTripResult) SetSuccess(x interface{}) {
	p.Success = x.(*StartTripResp)
}

func (p *DriverServerStartTripResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *DriverServerStartTripResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DriverServerStartTripResult(%+v)", *p)
}

var fieldIDToName_DriverServerStartTripResult = map[int16]string{
	0: "success",
}

type DriverServerEndTripArgs struct {
	Req *EndTripReq `thrift:"req,1" frugal:"1,default,EndTripReq" json:"req"`
}

func NewDriverServerEndTripArgs() *DriverServerEndTripArgs {
	return &DriverServerEndTripArgs{}
}

func (p *DriverServerEndTripArgs) InitDefault() {
}

var DriverServerEndTripArgs_Req_DEFAULT *EndTripReq

func (p *DriverServerEndTripArgs) GetReq() (v *EndTripReq) {
	if !p.IsSetReq() {
		return DriverServerEndTripArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *DriverServerEndTripArgs) SetReq(val *EndTripReq) {
	p.Req = val
}

func (p *DriverServerEndTripArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *DriverServerEndTripArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DriverServerEndTripArgs(%+v)", *p)
}

var fieldIDToName_DriverServerEndTripArgs = map[int16]string{
	1: "req",
}

type DriverServerEndTripResult struct {
	Success *EndTripResp `thrift:"success,0,optional" frugal:"0,optional,EndTripResp" json:"success,omitempty"`
}

func NewDriverServerEndTripResult() *DriverServerEndTripResult {
	return &DriverServerEndTripResult{}
}

func (p *DriverServerEndTripResult) InitDefault() {
}

var DriverServerEndTripResult_Success_DEFAULT *EndTripResp

func (p *DriverServerEndTripResult) GetSuccess() (v *EndTripResp) {
	if !p.IsSetSuccess() {
		return DriverServerEndTripResult_Success_DEFAULT
	}
	return p.Success
}
func (p *DriverServerEndTripResult) SetSuccess(x interface{}) {
	p.Success = x.(*EndTripResp)
}

func (p *DriverServerEndTripResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *DriverServerEndTripResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DriverServerEndTripResult(%+v)", *p)
}

var fieldIDToName_DriverServerEndTripResult = map[int16]string{
	0: "success",
}
