// Code generated by thriftgo (0.4.2). DO NOT EDIT.

package driver

import (
	"context"
	"fmt"
)

type DriverPetitionReq struct {
	Name                 string `thrift:"name,1" frugal:"1,default,string" json:"name"`
	Mobile               string `thrift:"mobile,2" frugal:"2,default,string" json:"mobile"`
	NickName             string `thrift:"nick_name,3" frugal:"3,default,string" json:"nick_name"`
	CarAge               int64  `thrift:"car_age,4" frugal:"4,default,i64" json:"car_age"`
	IdCardFileId         string `thrift:"id_card_file_id,5" frugal:"5,default,string" json:"id_card_file_id"`
	DriverLicenseFileId  string `thrift:"driver_license_file_id,6" frugal:"6,default,string" json:"driver_license_file_id"`
	DrivingLicenseFileId string `thrift:"driving_license_file_id,7" frugal:"7,default,string" json:"driving_license_file_id"`
	AvatarFileId         string `thrift:"avatar_file_id,8" frugal:"8,default,string" json:"avatar_file_id"`
}

func NewDriverPetitionReq() *DriverPetitionReq {
	return &DriverPetitionReq{}
}

func (p *DriverPetitionReq) InitDefault() {
}

func (p *DriverPetitionReq) GetName() (v string) {
	return p.Name
}

func (p *DriverPetitionReq) GetMobile() (v string) {
	return p.Mobile
}

func (p *DriverPetitionReq) GetNickName() (v string) {
	return p.NickName
}

func (p *DriverPetitionReq) GetCarAge() (v int64) {
	return p.CarAge
}

func (p *DriverPetitionReq) GetIdCardFileId() (v string) {
	return p.IdCardFileId
}

func (p *DriverPetitionReq) GetDriverLicenseFileId() (v string) {
	return p.DriverLicenseFileId
}

func (p *DriverPetitionReq) GetDrivingLicenseFileId() (v string) {
	return p.DrivingLicenseFileId
}

func (p *DriverPetitionReq) GetAvatarFileId() (v string) {
	return p.AvatarFileId
}
func (p *DriverPetitionReq) SetName(val string) {
	p.Name = val
}
func (p *DriverPetitionReq) SetMobile(val string) {
	p.Mobile = val
}
func (p *DriverPetitionReq) SetNickName(val string) {
	p.NickName = val
}
func (p *DriverPetitionReq) SetCarAge(val int64) {
	p.CarAge = val
}
func (p *DriverPetitionReq) SetIdCardFileId(val string) {
	p.IdCardFileId = val
}
func (p *DriverPetitionReq) SetDriverLicenseFileId(val string) {
	p.DriverLicenseFileId = val
}
func (p *DriverPetitionReq) SetDrivingLicenseFileId(val string) {
	p.DrivingLicenseFileId = val
}
func (p *DriverPetitionReq) SetAvatarFileId(val string) {
	p.AvatarFileId = val
}

func (p *DriverPetitionReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DriverPetitionReq(%+v)", *p)
}

var fieldIDToName_DriverPetitionReq = map[int16]string{
	1: "name",
	2: "mobile",
	3: "nick_name",
	4: "car_age",
	5: "id_card_file_id",
	6: "driver_license_file_id",
	7: "driving_license_file_id",
	8: "avatar_file_id",
}

type DriverPetitionResp struct {
	Code          int16  `thrift:"code,1" frugal:"1,default,i16" json:"code"`
	Message       string `thrift:"message,2" frugal:"2,default,string" json:"message"`
	ApplicationId *int64 `thrift:"application_id,3,optional" frugal:"3,optional,i64" json:"application_id,omitempty"`
}

func NewDriverPetitionResp() *DriverPetitionResp {
	return &DriverPetitionResp{}
}

func (p *DriverPetitionResp) InitDefault() {
}

func (p *DriverPetitionResp) GetCode() (v int16) {
	return p.Code
}

func (p *DriverPetitionResp) GetMessage() (v string) {
	return p.Message
}

var DriverPetitionResp_ApplicationId_DEFAULT int64

func (p *DriverPetitionResp) GetApplicationId() (v int64) {
	if !p.IsSetApplicationId() {
		return DriverPetitionResp_ApplicationId_DEFAULT
	}
	return *p.ApplicationId
}
func (p *DriverPetitionResp) SetCode(val int16) {
	p.Code = val
}
func (p *DriverPetitionResp) SetMessage(val string) {
	p.Message = val
}
func (p *DriverPetitionResp) SetApplicationId(val *int64) {
	p.ApplicationId = val
}

func (p *DriverPetitionResp) IsSetApplicationId() bool {
	return p.ApplicationId != nil
}

func (p *DriverPetitionResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DriverPetitionResp(%+v)", *p)
}

var fieldIDToName_DriverPetitionResp = map[int16]string{
	1: "code",
	2: "message",
	3: "application_id",
}

type CheckStatusReq struct {
	DriverId int64 `thrift:"driver_id,1" frugal:"1,default,i64" json:"driver_id"`
}

func NewCheckStatusReq() *CheckStatusReq {
	return &CheckStatusReq{}
}

func (p *CheckStatusReq) InitDefault() {
}

func (p *CheckStatusReq) GetDriverId() (v int64) {
	return p.DriverId
}
func (p *CheckStatusReq) SetDriverId(val int64) {
	p.DriverId = val
}

func (p *CheckStatusReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CheckStatusReq(%+v)", *p)
}

var fieldIDToName_CheckStatusReq = map[int16]string{
	1: "driver_id",
}

type CheckStatusResp struct {
	Code        int16   `thrift:"code,1" frugal:"1,default,i16" json:"code"`
	Message     string  `thrift:"message,2" frugal:"2,default,string" json:"message"`
	CheckStatus *string `thrift:"check_status,3,optional" frugal:"3,optional,string" json:"check_status,omitempty"`
	Remark      *string `thrift:"remark,4,optional" frugal:"4,optional,string" json:"remark,omitempty"`
}

func NewCheckStatusResp() *CheckStatusResp {
	return &CheckStatusResp{}
}

func (p *CheckStatusResp) InitDefault() {
}

func (p *CheckStatusResp) GetCode() (v int16) {
	return p.Code
}

func (p *CheckStatusResp) GetMessage() (v string) {
	return p.Message
}

var CheckStatusResp_CheckStatus_DEFAULT string

func (p *CheckStatusResp) GetCheckStatus() (v string) {
	if !p.IsSetCheckStatus() {
		return CheckStatusResp_CheckStatus_DEFAULT
	}
	return *p.CheckStatus
}

var CheckStatusResp_Remark_DEFAULT string

func (p *CheckStatusResp) GetRemark() (v string) {
	if !p.IsSetRemark() {
		return CheckStatusResp_Remark_DEFAULT
	}
	return *p.Remark
}
func (p *CheckStatusResp) SetCode(val int16) {
	p.Code = val
}
func (p *CheckStatusResp) SetMessage(val string) {
	p.Message = val
}
func (p *CheckStatusResp) SetCheckStatus(val *string) {
	p.CheckStatus = val
}
func (p *CheckStatusResp) SetRemark(val *string) {
	p.Remark = val
}

func (p *CheckStatusResp) IsSetCheckStatus() bool {
	return p.CheckStatus != nil
}

func (p *CheckStatusResp) IsSetRemark() bool {
	return p.Remark != nil
}

func (p *CheckStatusResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CheckStatusResp(%+v)", *p)
}

var fieldIDToName_CheckStatusResp = map[int16]string{
	1: "code",
	2: "message",
	3: "check_status",
	4: "remark",
}

type DriverLoginReq struct {
	Mobile  string `thrift:"mobile,1" frugal:"1,default,string" json:"mobile"`
	SmsCode string `thrift:"sms_code,2" frugal:"2,default,string" json:"sms_code"`
}

func NewDriverLoginReq() *DriverLoginReq {
	return &DriverLoginReq{}
}

func (p *DriverLoginReq) InitDefault() {
}

func (p *DriverLoginReq) GetMobile() (v string) {
	return p.Mobile
}

func (p *DriverLoginReq) GetSmsCode() (v string) {
	return p.SmsCode
}
func (p *DriverLoginReq) SetMobile(val string) {
	p.Mobile = val
}
func (p *DriverLoginReq) SetSmsCode(val string) {
	p.SmsCode = val
}

func (p *DriverLoginReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DriverLoginReq(%+v)", *p)
}

var fieldIDToName_DriverLoginReq = map[int16]string{
	1: "mobile",
	2: "sms_code",
}

type DriverLoginResp struct {
	Code       int16       `thrift:"code,1" frugal:"1,default,i16" json:"code"`
	Message    string      `thrift:"message,2" frugal:"2,default,string" json:"message"`
	DriverId   *int64      `thrift:"driver_id,3,optional" frugal:"3,optional,i64" json:"driver_id,omitempty"`
	Token      *string     `thrift:"token,4,optional" frugal:"4,optional,string" json:"token,omitempty"`
	DriverInfo *DriverInfo `thrift:"driver_info,5,optional" frugal:"5,optional,DriverInfo" json:"driver_info,omitempty"`
}

func NewDriverLoginResp() *DriverLoginResp {
	return &DriverLoginResp{}
}

func (p *DriverLoginResp) InitDefault() {
}

func (p *DriverLoginResp) GetCode() (v int16) {
	return p.Code
}

func (p *DriverLoginResp) GetMessage() (v string) {
	return p.Message
}

var DriverLoginResp_DriverId_DEFAULT int64

func (p *DriverLoginResp) GetDriverId() (v int64) {
	if !p.IsSetDriverId() {
		return DriverLoginResp_DriverId_DEFAULT
	}
	return *p.DriverId
}

var DriverLoginResp_Token_DEFAULT string

func (p *DriverLoginResp) GetToken() (v string) {
	if !p.IsSetToken() {
		return DriverLoginResp_Token_DEFAULT
	}
	return *p.Token
}

var DriverLoginResp_DriverInfo_DEFAULT *DriverInfo

func (p *DriverLoginResp) GetDriverInfo() (v *DriverInfo) {
	if !p.IsSetDriverInfo() {
		return DriverLoginResp_DriverInfo_DEFAULT
	}
	return p.DriverInfo
}
func (p *DriverLoginResp) SetCode(val int16) {
	p.Code = val
}
func (p *DriverLoginResp) SetMessage(val string) {
	p.Message = val
}
func (p *DriverLoginResp) SetDriverId(val *int64) {
	p.DriverId = val
}
func (p *DriverLoginResp) SetToken(val *string) {
	p.Token = val
}
func (p *DriverLoginResp) SetDriverInfo(val *DriverInfo) {
	p.DriverInfo = val
}

func (p *DriverLoginResp) IsSetDriverId() bool {
	return p.DriverId != nil
}

func (p *DriverLoginResp) IsSetToken() bool {
	return p.Token != nil
}

func (p *DriverLoginResp) IsSetDriverInfo() bool {
	return p.DriverInfo != nil
}

func (p *DriverLoginResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DriverLoginResp(%+v)", *p)
}

var fieldIDToName_DriverLoginResp = map[int16]string{
	1: "code",
	2: "message",
	3: "driver_id",
	4: "token",
	5: "driver_info",
}

type DriverInfo struct {
	Id         int64   `thrift:"id,1" frugal:"1,default,i64" json:"id"`
	Name       string  `thrift:"name,2" frugal:"2,default,string" json:"name"`
	NickName   string  `thrift:"nick_name,3" frugal:"3,default,string" json:"nick_name"`
	Mobile     string  `thrift:"mobile,4" frugal:"4,default,string" json:"mobile"`
	AllAccount float64 `thrift:"all_account,5" frugal:"5,default,double" json:"all_account"`
	CarAge     int64   `thrift:"car_age,6" frugal:"6,default,i64" json:"car_age"`
	Status     string  `thrift:"status,7" frugal:"7,default,string" json:"status"`
	FileId     int64   `thrift:"file_id,8" frugal:"8,default,i64" json:"file_id"`
}

func NewDriverInfo() *DriverInfo {
	return &DriverInfo{}
}

func (p *DriverInfo) InitDefault() {
}

func (p *DriverInfo) GetId() (v int64) {
	return p.Id
}

func (p *DriverInfo) GetName() (v string) {
	return p.Name
}

func (p *DriverInfo) GetNickName() (v string) {
	return p.NickName
}

func (p *DriverInfo) GetMobile() (v string) {
	return p.Mobile
}

func (p *DriverInfo) GetAllAccount() (v float64) {
	return p.AllAccount
}

func (p *DriverInfo) GetCarAge() (v int64) {
	return p.CarAge
}

func (p *DriverInfo) GetStatus() (v string) {
	return p.Status
}

func (p *DriverInfo) GetFileId() (v int64) {
	return p.FileId
}
func (p *DriverInfo) SetId(val int64) {
	p.Id = val
}
func (p *DriverInfo) SetName(val string) {
	p.Name = val
}
func (p *DriverInfo) SetNickName(val string) {
	p.NickName = val
}
func (p *DriverInfo) SetMobile(val string) {
	p.Mobile = val
}
func (p *DriverInfo) SetAllAccount(val float64) {
	p.AllAccount = val
}
func (p *DriverInfo) SetCarAge(val int64) {
	p.CarAge = val
}
func (p *DriverInfo) SetStatus(val string) {
	p.Status = val
}
func (p *DriverInfo) SetFileId(val int64) {
	p.FileId = val
}

func (p *DriverInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DriverInfo(%+v)", *p)
}

var fieldIDToName_DriverInfo = map[int16]string{
	1: "id",
	2: "name",
	3: "nick_name",
	4: "mobile",
	5: "all_account",
	6: "car_age",
	7: "status",
	8: "file_id",
}

type GetDriverInfoReq struct {
	DriverId int64 `thrift:"driver_id,1" frugal:"1,default,i64" json:"driver_id"`
}

func NewGetDriverInfoReq() *GetDriverInfoReq {
	return &GetDriverInfoReq{}
}

func (p *GetDriverInfoReq) InitDefault() {
}

func (p *GetDriverInfoReq) GetDriverId() (v int64) {
	return p.DriverId
}
func (p *GetDriverInfoReq) SetDriverId(val int64) {
	p.DriverId = val
}

func (p *GetDriverInfoReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetDriverInfoReq(%+v)", *p)
}

var fieldIDToName_GetDriverInfoReq = map[int16]string{
	1: "driver_id",
}

type GetDriverInfoResp struct {
	Code       int16       `thrift:"code,1" frugal:"1,default,i16" json:"code"`
	Message    string      `thrift:"message,2" frugal:"2,default,string" json:"message"`
	DriverInfo *DriverInfo `thrift:"driver_info,3,optional" frugal:"3,optional,DriverInfo" json:"driver_info,omitempty"`
}

func NewGetDriverInfoResp() *GetDriverInfoResp {
	return &GetDriverInfoResp{}
}

func (p *GetDriverInfoResp) InitDefault() {
}

func (p *GetDriverInfoResp) GetCode() (v int16) {
	return p.Code
}

func (p *GetDriverInfoResp) GetMessage() (v string) {
	return p.Message
}

var GetDriverInfoResp_DriverInfo_DEFAULT *DriverInfo

func (p *GetDriverInfoResp) GetDriverInfo() (v *DriverInfo) {
	if !p.IsSetDriverInfo() {
		return GetDriverInfoResp_DriverInfo_DEFAULT
	}
	return p.DriverInfo
}
func (p *GetDriverInfoResp) SetCode(val int16) {
	p.Code = val
}
func (p *GetDriverInfoResp) SetMessage(val string) {
	p.Message = val
}
func (p *GetDriverInfoResp) SetDriverInfo(val *DriverInfo) {
	p.DriverInfo = val
}

func (p *GetDriverInfoResp) IsSetDriverInfo() bool {
	return p.DriverInfo != nil
}

func (p *GetDriverInfoResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetDriverInfoResp(%+v)", *p)
}

var fieldIDToName_GetDriverInfoResp = map[int16]string{
	1: "code",
	2: "message",
	3: "driver_info",
}

type UpdateDriverInfoReq struct {
	DriverId int64   `thrift:"driver_id,1" frugal:"1,default,i64" json:"driver_id"`
	NickName *string `thrift:"nick_name,2,optional" frugal:"2,optional,string" json:"nick_name,omitempty"`
	FileId   *int64  `thrift:"file_id,3,optional" frugal:"3,optional,i64" json:"file_id,omitempty"`
}

func NewUpdateDriverInfoReq() *UpdateDriverInfoReq {
	return &UpdateDriverInfoReq{}
}

func (p *UpdateDriverInfoReq) InitDefault() {
}

func (p *UpdateDriverInfoReq) GetDriverId() (v int64) {
	return p.DriverId
}

var UpdateDriverInfoReq_NickName_DEFAULT string

func (p *UpdateDriverInfoReq) GetNickName() (v string) {
	if !p.IsSetNickName() {
		return UpdateDriverInfoReq_NickName_DEFAULT
	}
	return *p.NickName
}

var UpdateDriverInfoReq_FileId_DEFAULT int64

func (p *UpdateDriverInfoReq) GetFileId() (v int64) {
	if !p.IsSetFileId() {
		return UpdateDriverInfoReq_FileId_DEFAULT
	}
	return *p.FileId
}
func (p *UpdateDriverInfoReq) SetDriverId(val int64) {
	p.DriverId = val
}
func (p *UpdateDriverInfoReq) SetNickName(val *string) {
	p.NickName = val
}
func (p *UpdateDriverInfoReq) SetFileId(val *int64) {
	p.FileId = val
}

func (p *UpdateDriverInfoReq) IsSetNickName() bool {
	return p.NickName != nil
}

func (p *UpdateDriverInfoReq) IsSetFileId() bool {
	return p.FileId != nil
}

func (p *UpdateDriverInfoReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdateDriverInfoReq(%+v)", *p)
}

var fieldIDToName_UpdateDriverInfoReq = map[int16]string{
	1: "driver_id",
	2: "nick_name",
	3: "file_id",
}

type UpdateDriverInfoResp struct {
	Code    int16  `thrift:"code,1" frugal:"1,default,i16" json:"code"`
	Message string `thrift:"message,2" frugal:"2,default,string" json:"message"`
}

func NewUpdateDriverInfoResp() *UpdateDriverInfoResp {
	return &UpdateDriverInfoResp{}
}

func (p *UpdateDriverInfoResp) InitDefault() {
}

func (p *UpdateDriverInfoResp) GetCode() (v int16) {
	return p.Code
}

func (p *UpdateDriverInfoResp) GetMessage() (v string) {
	return p.Message
}
func (p *UpdateDriverInfoResp) SetCode(val int16) {
	p.Code = val
}
func (p *UpdateDriverInfoResp) SetMessage(val string) {
	p.Message = val
}

func (p *UpdateDriverInfoResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdateDriverInfoResp(%+v)", *p)
}

var fieldIDToName_UpdateDriverInfoResp = map[int16]string{
	1: "code",
	2: "message",
}

type ChangeStatusReq struct {
	DriverId  int64   `thrift:"driver_id,1" frugal:"1,default,i64" json:"driver_id"`
	Status    string  `thrift:"status,2" frugal:"2,default,string" json:"status"`
	Longitude *string `thrift:"longitude,3,optional" frugal:"3,optional,string" json:"longitude,omitempty"`
	Latitude  *string `thrift:"latitude,4,optional" frugal:"4,optional,string" json:"latitude,omitempty"`
}

func NewChangeStatusReq() *ChangeStatusReq {
	return &ChangeStatusReq{}
}

func (p *ChangeStatusReq) InitDefault() {
}

func (p *ChangeStatusReq) GetDriverId() (v int64) {
	return p.DriverId
}

func (p *ChangeStatusReq) GetStatus() (v string) {
	return p.Status
}

var ChangeStatusReq_Longitude_DEFAULT string

func (p *ChangeStatusReq) GetLongitude() (v string) {
	if !p.IsSetLongitude() {
		return ChangeStatusReq_Longitude_DEFAULT
	}
	return *p.Longitude
}

var ChangeStatusReq_Latitude_DEFAULT string

func (p *ChangeStatusReq) GetLatitude() (v string) {
	if !p.IsSetLatitude() {
		return ChangeStatusReq_Latitude_DEFAULT
	}
	return *p.Latitude
}
func (p *ChangeStatusReq) SetDriverId(val int64) {
	p.DriverId = val
}
func (p *ChangeStatusReq) SetStatus(val string) {
	p.Status = val
}
func (p *ChangeStatusReq) SetLongitude(val *string) {
	p.Longitude = val
}
func (p *ChangeStatusReq) SetLatitude(val *string) {
	p.Latitude = val
}

func (p *ChangeStatusReq) IsSetLongitude() bool {
	return p.Longitude != nil
}

func (p *ChangeStatusReq) IsSetLatitude() bool {
	return p.Latitude != nil
}

func (p *ChangeStatusReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ChangeStatusReq(%+v)", *p)
}

var fieldIDToName_ChangeStatusReq = map[int16]string{
	1: "driver_id",
	2: "status",
	3: "longitude",
	4: "latitude",
}

type ChangeStatusResp struct {
	Code    int16  `thrift:"code,1" frugal:"1,default,i16" json:"code"`
	Message string `thrift:"message,2" frugal:"2,default,string" json:"message"`
}

func NewChangeStatusResp() *ChangeStatusResp {
	return &ChangeStatusResp{}
}

func (p *ChangeStatusResp) InitDefault() {
}

func (p *ChangeStatusResp) GetCode() (v int16) {
	return p.Code
}

func (p *ChangeStatusResp) GetMessage() (v string) {
	return p.Message
}
func (p *ChangeStatusResp) SetCode(val int16) {
	p.Code = val
}
func (p *ChangeStatusResp) SetMessage(val string) {
	p.Message = val
}

func (p *ChangeStatusResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ChangeStatusResp(%+v)", *p)
}

var fieldIDToName_ChangeStatusResp = map[int16]string{
	1: "code",
	2: "message",
}

type OrderInfo struct {
	Id              int64   `thrift:"id,1" frugal:"1,default,i64" json:"id"`
	OrderCode       string  `thrift:"order_code,2" frugal:"2,default,string" json:"order_code"`
	Amount          float64 `thrift:"amount,3" frugal:"3,default,double" json:"amount"`
	OrderStatus     string  `thrift:"order_status,4" frugal:"4,default,string" json:"order_status"`
	PassengerId     int64   `thrift:"passenger_id,5" frugal:"5,default,i64" json:"passenger_id"`
	PassengerName   string  `thrift:"passenger_name,6" frugal:"6,default,string" json:"passenger_name"`
	PassengerMobile string  `thrift:"passenger_mobile,7" frugal:"7,default,string" json:"passenger_mobile"`
	StartAddr       string  `thrift:"start_addr,8" frugal:"8,default,string" json:"start_addr"`
	EndAddr         string  `thrift:"end_addr,9" frugal:"9,default,string" json:"end_addr"`
	StartTime       string  `thrift:"start_time,10" frugal:"10,default,string" json:"start_time"`
	EndTime         string  `thrift:"end_time,11" frugal:"11,default,string" json:"end_time"`
	OrderType       string  `thrift:"order_type,12" frugal:"12,default,string" json:"order_type"`
}

func NewOrderInfo() *OrderInfo {
	return &OrderInfo{}
}

func (p *OrderInfo) InitDefault() {
}

func (p *OrderInfo) GetId() (v int64) {
	return p.Id
}

func (p *OrderInfo) GetOrderCode() (v string) {
	return p.OrderCode
}

func (p *OrderInfo) GetAmount() (v float64) {
	return p.Amount
}

func (p *OrderInfo) GetOrderStatus() (v string) {
	return p.OrderStatus
}

func (p *OrderInfo) GetPassengerId() (v int64) {
	return p.PassengerId
}

func (p *OrderInfo) GetPassengerName() (v string) {
	return p.PassengerName
}

func (p *OrderInfo) GetPassengerMobile() (v string) {
	return p.PassengerMobile
}

func (p *OrderInfo) GetStartAddr() (v string) {
	return p.StartAddr
}

func (p *OrderInfo) GetEndAddr() (v string) {
	return p.EndAddr
}

func (p *OrderInfo) GetStartTime() (v string) {
	return p.StartTime
}

func (p *OrderInfo) GetEndTime() (v string) {
	return p.EndTime
}

func (p *OrderInfo) GetOrderType() (v string) {
	return p.OrderType
}
func (p *OrderInfo) SetId(val int64) {
	p.Id = val
}
func (p *OrderInfo) SetOrderCode(val string) {
	p.OrderCode = val
}
func (p *OrderInfo) SetAmount(val float64) {
	p.Amount = val
}
func (p *OrderInfo) SetOrderStatus(val string) {
	p.OrderStatus = val
}
func (p *OrderInfo) SetPassengerId(val int64) {
	p.PassengerId = val
}
func (p *OrderInfo) SetPassengerName(val string) {
	p.PassengerName = val
}
func (p *OrderInfo) SetPassengerMobile(val string) {
	p.PassengerMobile = val
}
func (p *OrderInfo) SetStartAddr(val string) {
	p.StartAddr = val
}
func (p *OrderInfo) SetEndAddr(val string) {
	p.EndAddr = val
}
func (p *OrderInfo) SetStartTime(val string) {
	p.StartTime = val
}
func (p *OrderInfo) SetEndTime(val string) {
	p.EndTime = val
}
func (p *OrderInfo) SetOrderType(val string) {
	p.OrderType = val
}

func (p *OrderInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderInfo(%+v)", *p)
}

var fieldIDToName_OrderInfo = map[int16]string{
	1:  "id",
	2:  "order_code",
	3:  "amount",
	4:  "order_status",
	5:  "passenger_id",
	6:  "passenger_name",
	7:  "passenger_mobile",
	8:  "start_addr",
	9:  "end_addr",
	10: "start_time",
	11: "end_time",
	12: "order_type",
}

type GetPendingOrdersReq struct {
	DriverId  int64  `thrift:"driver_id,1" frugal:"1,default,i64" json:"driver_id"`
	Longitude string `thrift:"longitude,2" frugal:"2,default,string" json:"longitude"`
	Latitude  string `thrift:"latitude,3" frugal:"3,default,string" json:"latitude"`
	Radius    *int32 `thrift:"radius,4,optional" frugal:"4,optional,i32" json:"radius,omitempty"`
}

func NewGetPendingOrdersReq() *GetPendingOrdersReq {
	return &GetPendingOrdersReq{}
}

func (p *GetPendingOrdersReq) InitDefault() {
}

func (p *GetPendingOrdersReq) GetDriverId() (v int64) {
	return p.DriverId
}

func (p *GetPendingOrdersReq) GetLongitude() (v string) {
	return p.Longitude
}

func (p *GetPendingOrdersReq) GetLatitude() (v string) {
	return p.Latitude
}

var GetPendingOrdersReq_Radius_DEFAULT int32

func (p *GetPendingOrdersReq) GetRadius() (v int32) {
	if !p.IsSetRadius() {
		return GetPendingOrdersReq_Radius_DEFAULT
	}
	return *p.Radius
}
func (p *GetPendingOrdersReq) SetDriverId(val int64) {
	p.DriverId = val
}
func (p *GetPendingOrdersReq) SetLongitude(val string) {
	p.Longitude = val
}
func (p *GetPendingOrdersReq) SetLatitude(val string) {
	p.Latitude = val
}
func (p *GetPendingOrdersReq) SetRadius(val *int32) {
	p.Radius = val
}

func (p *GetPendingOrdersReq) IsSetRadius() bool {
	return p.Radius != nil
}

func (p *GetPendingOrdersReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetPendingOrdersReq(%+v)", *p)
}

var fieldIDToName_GetPendingOrdersReq = map[int16]string{
	1: "driver_id",
	2: "longitude",
	3: "latitude",
	4: "radius",
}

type GetPendingOrdersResp struct {
	Code    int16        `thrift:"code,1" frugal:"1,default,i16" json:"code"`
	Message string       `thrift:"message,2" frugal:"2,default,string" json:"message"`
	Orders  []*OrderInfo `thrift:"orders,3,optional" frugal:"3,optional,list<OrderInfo>" json:"orders,omitempty"`
}

func NewGetPendingOrdersResp() *GetPendingOrdersResp {
	return &GetPendingOrdersResp{}
}

func (p *GetPendingOrdersResp) InitDefault() {
}

func (p *GetPendingOrdersResp) GetCode() (v int16) {
	return p.Code
}

func (p *GetPendingOrdersResp) GetMessage() (v string) {
	return p.Message
}

var GetPendingOrdersResp_Orders_DEFAULT []*OrderInfo

func (p *GetPendingOrdersResp) GetOrders() (v []*OrderInfo) {
	if !p.IsSetOrders() {
		return GetPendingOrdersResp_Orders_DEFAULT
	}
	return p.Orders
}
func (p *GetPendingOrdersResp) SetCode(val int16) {
	p.Code = val
}
func (p *GetPendingOrdersResp) SetMessage(val string) {
	p.Message = val
}
func (p *GetPendingOrdersResp) SetOrders(val []*OrderInfo) {
	p.Orders = val
}

func (p *GetPendingOrdersResp) IsSetOrders() bool {
	return p.Orders != nil
}

func (p *GetPendingOrdersResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetPendingOrdersResp(%+v)", *p)
}

var fieldIDToName_GetPendingOrdersResp = map[int16]string{
	1: "code",
	2: "message",
	3: "orders",
}

type AcceptOrderReq struct {
	DriverId int64 `thrift:"driver_id,1" frugal:"1,default,i64" json:"driver_id"`
	OrderId  int64 `thrift:"order_id,2" frugal:"2,default,i64" json:"order_id"`
}

func NewAcceptOrderReq() *AcceptOrderReq {
	return &AcceptOrderReq{}
}

func (p *AcceptOrderReq) InitDefault() {
}

func (p *AcceptOrderReq) GetDriverId() (v int64) {
	return p.DriverId
}

func (p *AcceptOrderReq) GetOrderId() (v int64) {
	return p.OrderId
}
func (p *AcceptOrderReq) SetDriverId(val int64) {
	p.DriverId = val
}
func (p *AcceptOrderReq) SetOrderId(val int64) {
	p.OrderId = val
}

func (p *AcceptOrderReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AcceptOrderReq(%+v)", *p)
}

var fieldIDToName_AcceptOrderReq = map[int16]string{
	1: "driver_id",
	2: "order_id",
}

type AcceptOrderResp struct {
	Code      int16      `thrift:"code,1" frugal:"1,default,i16" json:"code"`
	Message   string     `thrift:"message,2" frugal:"2,default,string" json:"message"`
	OrderInfo *OrderInfo `thrift:"order_info,3,optional" frugal:"3,optional,OrderInfo" json:"order_info,omitempty"`
}

func NewAcceptOrderResp() *AcceptOrderResp {
	return &AcceptOrderResp{}
}

func (p *AcceptOrderResp) InitDefault() {
}

func (p *AcceptOrderResp) GetCode() (v int16) {
	return p.Code
}

func (p *AcceptOrderResp) GetMessage() (v string) {
	return p.Message
}

var AcceptOrderResp_OrderInfo_DEFAULT *OrderInfo

func (p *AcceptOrderResp) GetOrderInfo() (v *OrderInfo) {
	if !p.IsSetOrderInfo() {
		return AcceptOrderResp_OrderInfo_DEFAULT
	}
	return p.OrderInfo
}
func (p *AcceptOrderResp) SetCode(val int16) {
	p.Code = val
}
func (p *AcceptOrderResp) SetMessage(val string) {
	p.Message = val
}
func (p *AcceptOrderResp) SetOrderInfo(val *OrderInfo) {
	p.OrderInfo = val
}

func (p *AcceptOrderResp) IsSetOrderInfo() bool {
	return p.OrderInfo != nil
}

func (p *AcceptOrderResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AcceptOrderResp(%+v)", *p)
}

var fieldIDToName_AcceptOrderResp = map[int16]string{
	1: "code",
	2: "message",
	3: "order_info",
}

type StartTripReq struct {
	DriverId  int64  `thrift:"driver_id,1" frugal:"1,default,i64" json:"driver_id"`
	OrderId   int64  `thrift:"order_id,2" frugal:"2,default,i64" json:"order_id"`
	Longitude string `thrift:"longitude,3" frugal:"3,default,string" json:"longitude"`
	Latitude  string `thrift:"latitude,4" frugal:"4,default,string" json:"latitude"`
}

func NewStartTripReq() *StartTripReq {
	return &StartTripReq{}
}

func (p *StartTripReq) InitDefault() {
}

func (p *StartTripReq) GetDriverId() (v int64) {
	return p.DriverId
}

func (p *StartTripReq) GetOrderId() (v int64) {
	return p.OrderId
}

func (p *StartTripReq) GetLongitude() (v string) {
	return p.Longitude
}

func (p *StartTripReq) GetLatitude() (v string) {
	return p.Latitude
}
func (p *StartTripReq) SetDriverId(val int64) {
	p.DriverId = val
}
func (p *StartTripReq) SetOrderId(val int64) {
	p.OrderId = val
}
func (p *StartTripReq) SetLongitude(val string) {
	p.Longitude = val
}
func (p *StartTripReq) SetLatitude(val string) {
	p.Latitude = val
}

func (p *StartTripReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("StartTripReq(%+v)", *p)
}

var fieldIDToName_StartTripReq = map[int16]string{
	1: "driver_id",
	2: "order_id",
	3: "longitude",
	4: "latitude",
}

type StartTripResp struct {
	Code    int16  `thrift:"code,1" frugal:"1,default,i16" json:"code"`
	Message string `thrift:"message,2" frugal:"2,default,string" json:"message"`
}

func NewStartTripResp() *StartTripResp {
	return &StartTripResp{}
}

func (p *StartTripResp) InitDefault() {
}

func (p *StartTripResp) GetCode() (v int16) {
	return p.Code
}

func (p *StartTripResp) GetMessage() (v string) {
	return p.Message
}
func (p *StartTripResp) SetCode(val int16) {
	p.Code = val
}
func (p *StartTripResp) SetMessage(val string) {
	p.Message = val
}

func (p *StartTripResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("StartTripResp(%+v)", *p)
}

var fieldIDToName_StartTripResp = map[int16]string{
	1: "code",
	2: "message",
}

type CompleteOrderReq struct {
	DriverId     int64   `thrift:"driver_id,1" frugal:"1,default,i64" json:"driver_id"`
	OrderId      int64   `thrift:"order_id,2" frugal:"2,default,i64" json:"order_id"`
	Longitude    string  `thrift:"longitude,3" frugal:"3,default,string" json:"longitude"`
	Latitude     string  `thrift:"latitude,4" frugal:"4,default,string" json:"latitude"`
	ActualAmount float64 `thrift:"actual_amount,5" frugal:"5,default,double" json:"actual_amount"`
}

func NewCompleteOrderReq() *CompleteOrderReq {
	return &CompleteOrderReq{}
}

func (p *CompleteOrderReq) InitDefault() {
}

func (p *CompleteOrderReq) GetDriverId() (v int64) {
	return p.DriverId
}

func (p *CompleteOrderReq) GetOrderId() (v int64) {
	return p.OrderId
}

func (p *CompleteOrderReq) GetLongitude() (v string) {
	return p.Longitude
}

func (p *CompleteOrderReq) GetLatitude() (v string) {
	return p.Latitude
}

func (p *CompleteOrderReq) GetActualAmount() (v float64) {
	return p.ActualAmount
}
func (p *CompleteOrderReq) SetDriverId(val int64) {
	p.DriverId = val
}
func (p *CompleteOrderReq) SetOrderId(val int64) {
	p.OrderId = val
}
func (p *CompleteOrderReq) SetLongitude(val string) {
	p.Longitude = val
}
func (p *CompleteOrderReq) SetLatitude(val string) {
	p.Latitude = val
}
func (p *CompleteOrderReq) SetActualAmount(val float64) {
	p.ActualAmount = val
}

func (p *CompleteOrderReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CompleteOrderReq(%+v)", *p)
}

var fieldIDToName_CompleteOrderReq = map[int16]string{
	1: "driver_id",
	2: "order_id",
	3: "longitude",
	4: "latitude",
	5: "actual_amount",
}

type CompleteOrderResp struct {
	Code         int16    `thrift:"code,1" frugal:"1,default,i16" json:"code"`
	Message      string   `thrift:"message,2" frugal:"2,default,string" json:"message"`
	DriverIncome *float64 `thrift:"driver_income,3,optional" frugal:"3,optional,double" json:"driver_income,omitempty"`
}

func NewCompleteOrderResp() *CompleteOrderResp {
	return &CompleteOrderResp{}
}

func (p *CompleteOrderResp) InitDefault() {
}

func (p *CompleteOrderResp) GetCode() (v int16) {
	return p.Code
}

func (p *CompleteOrderResp) GetMessage() (v string) {
	return p.Message
}

var CompleteOrderResp_DriverIncome_DEFAULT float64

func (p *CompleteOrderResp) GetDriverIncome() (v float64) {
	if !p.IsSetDriverIncome() {
		return CompleteOrderResp_DriverIncome_DEFAULT
	}
	return *p.DriverIncome
}
func (p *CompleteOrderResp) SetCode(val int16) {
	p.Code = val
}
func (p *CompleteOrderResp) SetMessage(val string) {
	p.Message = val
}
func (p *CompleteOrderResp) SetDriverIncome(val *float64) {
	p.DriverIncome = val
}

func (p *CompleteOrderResp) IsSetDriverIncome() bool {
	return p.DriverIncome != nil
}

func (p *CompleteOrderResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CompleteOrderResp(%+v)", *p)
}

var fieldIDToName_CompleteOrderResp = map[int16]string{
	1: "code",
	2: "message",
	3: "driver_income",
}

type CancelOrderReq struct {
	DriverId     int64   `thrift:"driver_id,1" frugal:"1,default,i64" json:"driver_id"`
	OrderId      int64   `thrift:"order_id,2" frugal:"2,default,i64" json:"order_id"`
	CancelReason string  `thrift:"cancel_reason,3" frugal:"3,default,string" json:"cancel_reason"`
	CancelRemark *string `thrift:"cancel_remark,4,optional" frugal:"4,optional,string" json:"cancel_remark,omitempty"`
}

func NewCancelOrderReq() *CancelOrderReq {
	return &CancelOrderReq{}
}

func (p *CancelOrderReq) InitDefault() {
}

func (p *CancelOrderReq) GetDriverId() (v int64) {
	return p.DriverId
}

func (p *CancelOrderReq) GetOrderId() (v int64) {
	return p.OrderId
}

func (p *CancelOrderReq) GetCancelReason() (v string) {
	return p.CancelReason
}

var CancelOrderReq_CancelRemark_DEFAULT string

func (p *CancelOrderReq) GetCancelRemark() (v string) {
	if !p.IsSetCancelRemark() {
		return CancelOrderReq_CancelRemark_DEFAULT
	}
	return *p.CancelRemark
}
func (p *CancelOrderReq) SetDriverId(val int64) {
	p.DriverId = val
}
func (p *CancelOrderReq) SetOrderId(val int64) {
	p.OrderId = val
}
func (p *CancelOrderReq) SetCancelReason(val string) {
	p.CancelReason = val
}
func (p *CancelOrderReq) SetCancelRemark(val *string) {
	p.CancelRemark = val
}

func (p *CancelOrderReq) IsSetCancelRemark() bool {
	return p.CancelRemark != nil
}

func (p *CancelOrderReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CancelOrderReq(%+v)", *p)
}

var fieldIDToName_CancelOrderReq = map[int16]string{
	1: "driver_id",
	2: "order_id",
	3: "cancel_reason",
	4: "cancel_remark",
}

type CancelOrderResp struct {
	Code    int16  `thrift:"code,1" frugal:"1,default,i16" json:"code"`
	Message string `thrift:"message,2" frugal:"2,default,string" json:"message"`
}

func NewCancelOrderResp() *CancelOrderResp {
	return &CancelOrderResp{}
}

func (p *CancelOrderResp) InitDefault() {
}

func (p *CancelOrderResp) GetCode() (v int16) {
	return p.Code
}

func (p *CancelOrderResp) GetMessage() (v string) {
	return p.Message
}
func (p *CancelOrderResp) SetCode(val int16) {
	p.Code = val
}
func (p *CancelOrderResp) SetMessage(val string) {
	p.Message = val
}

func (p *CancelOrderResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CancelOrderResp(%+v)", *p)
}

var fieldIDToName_CancelOrderResp = map[int16]string{
	1: "code",
	2: "message",
}

type IncomeDetail struct {
	Date        string  `thrift:"date,1" frugal:"1,default,string" json:"date"`
	OrderCount  int32   `thrift:"order_count,2" frugal:"2,default,i32" json:"order_count"`
	TotalIncome float64 `thrift:"total_income,3" frugal:"3,default,double" json:"total_income"`
	PlatformFee float64 `thrift:"platform_fee,4" frugal:"4,default,double" json:"platform_fee"`
	NetIncome   float64 `thrift:"net_income,5" frugal:"5,default,double" json:"net_income"`
}

func NewIncomeDetail() *IncomeDetail {
	return &IncomeDetail{}
}

func (p *IncomeDetail) InitDefault() {
}

func (p *IncomeDetail) GetDate() (v string) {
	return p.Date
}

func (p *IncomeDetail) GetOrderCount() (v int32) {
	return p.OrderCount
}

func (p *IncomeDetail) GetTotalIncome() (v float64) {
	return p.TotalIncome
}

func (p *IncomeDetail) GetPlatformFee() (v float64) {
	return p.PlatformFee
}

func (p *IncomeDetail) GetNetIncome() (v float64) {
	return p.NetIncome
}
func (p *IncomeDetail) SetDate(val string) {
	p.Date = val
}
func (p *IncomeDetail) SetOrderCount(val int32) {
	p.OrderCount = val
}
func (p *IncomeDetail) SetTotalIncome(val float64) {
	p.TotalIncome = val
}
func (p *IncomeDetail) SetPlatformFee(val float64) {
	p.PlatformFee = val
}
func (p *IncomeDetail) SetNetIncome(val float64) {
	p.NetIncome = val
}

func (p *IncomeDetail) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("IncomeDetail(%+v)", *p)
}

var fieldIDToName_IncomeDetail = map[int16]string{
	1: "date",
	2: "order_count",
	3: "total_income",
	4: "platform_fee",
	5: "net_income",
}

type GetIncomeReq struct {
	DriverId  int64  `thrift:"driver_id,1" frugal:"1,default,i64" json:"driver_id"`
	StartDate string `thrift:"start_date,2" frugal:"2,default,string" json:"start_date"`
	EndDate   string `thrift:"end_date,3" frugal:"3,default,string" json:"end_date"`
}

func NewGetIncomeReq() *GetIncomeReq {
	return &GetIncomeReq{}
}

func (p *GetIncomeReq) InitDefault() {
}

func (p *GetIncomeReq) GetDriverId() (v int64) {
	return p.DriverId
}

func (p *GetIncomeReq) GetStartDate() (v string) {
	return p.StartDate
}

func (p *GetIncomeReq) GetEndDate() (v string) {
	return p.EndDate
}
func (p *GetIncomeReq) SetDriverId(val int64) {
	p.DriverId = val
}
func (p *GetIncomeReq) SetStartDate(val string) {
	p.StartDate = val
}
func (p *GetIncomeReq) SetEndDate(val string) {
	p.EndDate = val
}

func (p *GetIncomeReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetIncomeReq(%+v)", *p)
}

var fieldIDToName_GetIncomeReq = map[int16]string{
	1: "driver_id",
	2: "start_date",
	3: "end_date",
}

type GetIncomeResp struct {
	Code          int16           `thrift:"code,1" frugal:"1,default,i16" json:"code"`
	Message       string          `thrift:"message,2" frugal:"2,default,string" json:"message"`
	IncomeDetails []*IncomeDetail `thrift:"income_details,3,optional" frugal:"3,optional,list<IncomeDetail>" json:"income_details,omitempty"`
	TotalIncome   *float64        `thrift:"total_income,4,optional" frugal:"4,optional,double" json:"total_income,omitempty"`
}

func NewGetIncomeResp() *GetIncomeResp {
	return &GetIncomeResp{}
}

func (p *GetIncomeResp) InitDefault() {
}

func (p *GetIncomeResp) GetCode() (v int16) {
	return p.Code
}

func (p *GetIncomeResp) GetMessage() (v string) {
	return p.Message
}

var GetIncomeResp_IncomeDetails_DEFAULT []*IncomeDetail

func (p *GetIncomeResp) GetIncomeDetails() (v []*IncomeDetail) {
	if !p.IsSetIncomeDetails() {
		return GetIncomeResp_IncomeDetails_DEFAULT
	}
	return p.IncomeDetails
}

var GetIncomeResp_TotalIncome_DEFAULT float64

func (p *GetIncomeResp) GetTotalIncome() (v float64) {
	if !p.IsSetTotalIncome() {
		return GetIncomeResp_TotalIncome_DEFAULT
	}
	return *p.TotalIncome
}
func (p *GetIncomeResp) SetCode(val int16) {
	p.Code = val
}
func (p *GetIncomeResp) SetMessage(val string) {
	p.Message = val
}
func (p *GetIncomeResp) SetIncomeDetails(val []*IncomeDetail) {
	p.IncomeDetails = val
}
func (p *GetIncomeResp) SetTotalIncome(val *float64) {
	p.TotalIncome = val
}

func (p *GetIncomeResp) IsSetIncomeDetails() bool {
	return p.IncomeDetails != nil
}

func (p *GetIncomeResp) IsSetTotalIncome() bool {
	return p.TotalIncome != nil
}

func (p *GetIncomeResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetIncomeResp(%+v)", *p)
}

var fieldIDToName_GetIncomeResp = map[int16]string{
	1: "code",
	2: "message",
	3: "income_details",
	4: "total_income",
}

type UpdateLocationReq struct {
	DriverId  int64    `thrift:"driver_id,1" frugal:"1,default,i64" json:"driver_id"`
	Longitude string   `thrift:"longitude,2" frugal:"2,default,string" json:"longitude"`
	Latitude  string   `thrift:"latitude,3" frugal:"3,default,string" json:"latitude"`
	Speed     *float64 `thrift:"speed,4,optional" frugal:"4,optional,double" json:"speed,omitempty"`
	Direction *float64 `thrift:"direction,5,optional" frugal:"5,optional,double" json:"direction,omitempty"`
}

func NewUpdateLocationReq() *UpdateLocationReq {
	return &UpdateLocationReq{}
}

func (p *UpdateLocationReq) InitDefault() {
}

func (p *UpdateLocationReq) GetDriverId() (v int64) {
	return p.DriverId
}

func (p *UpdateLocationReq) GetLongitude() (v string) {
	return p.Longitude
}

func (p *UpdateLocationReq) GetLatitude() (v string) {
	return p.Latitude
}

var UpdateLocationReq_Speed_DEFAULT float64

func (p *UpdateLocationReq) GetSpeed() (v float64) {
	if !p.IsSetSpeed() {
		return UpdateLocationReq_Speed_DEFAULT
	}
	return *p.Speed
}

var UpdateLocationReq_Direction_DEFAULT float64

func (p *UpdateLocationReq) GetDirection() (v float64) {
	if !p.IsSetDirection() {
		return UpdateLocationReq_Direction_DEFAULT
	}
	return *p.Direction
}
func (p *UpdateLocationReq) SetDriverId(val int64) {
	p.DriverId = val
}
func (p *UpdateLocationReq) SetLongitude(val string) {
	p.Longitude = val
}
func (p *UpdateLocationReq) SetLatitude(val string) {
	p.Latitude = val
}
func (p *UpdateLocationReq) SetSpeed(val *float64) {
	p.Speed = val
}
func (p *UpdateLocationReq) SetDirection(val *float64) {
	p.Direction = val
}

func (p *UpdateLocationReq) IsSetSpeed() bool {
	return p.Speed != nil
}

func (p *UpdateLocationReq) IsSetDirection() bool {
	return p.Direction != nil
}

func (p *UpdateLocationReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdateLocationReq(%+v)", *p)
}

var fieldIDToName_UpdateLocationReq = map[int16]string{
	1: "driver_id",
	2: "longitude",
	3: "latitude",
	4: "speed",
	5: "direction",
}

type UpdateLocationResp struct {
	Code    int16  `thrift:"code,1" frugal:"1,default,i16" json:"code"`
	Message string `thrift:"message,2" frugal:"2,default,string" json:"message"`
}

func NewUpdateLocationResp() *UpdateLocationResp {
	return &UpdateLocationResp{}
}

func (p *UpdateLocationResp) InitDefault() {
}

func (p *UpdateLocationResp) GetCode() (v int16) {
	return p.Code
}

func (p *UpdateLocationResp) GetMessage() (v string) {
	return p.Message
}
func (p *UpdateLocationResp) SetCode(val int16) {
	p.Code = val
}
func (p *UpdateLocationResp) SetMessage(val string) {
	p.Message = val
}

func (p *UpdateLocationResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdateLocationResp(%+v)", *p)
}

var fieldIDToName_UpdateLocationResp = map[int16]string{
	1: "code",
	2: "message",
}

type DriverService interface {
	DriverPetition(ctx context.Context, req *DriverPetitionReq) (r *DriverPetitionResp, err error)

	CheckStatus(ctx context.Context, req *CheckStatusReq) (r *CheckStatusResp, err error)

	DriverLogin(ctx context.Context, req *DriverLoginReq) (r *DriverLoginResp, err error)

	GetDriverInfo(ctx context.Context, req *GetDriverInfoReq) (r *GetDriverInfoResp, err error)

	UpdateDriverInfo(ctx context.Context, req *UpdateDriverInfoReq) (r *UpdateDriverInfoResp, err error)

	ChangeStatus(ctx context.Context, req *ChangeStatusReq) (r *ChangeStatusResp, err error)

	GetPendingOrders(ctx context.Context, req *GetPendingOrdersReq) (r *GetPendingOrdersResp, err error)

	AcceptOrder(ctx context.Context, req *AcceptOrderReq) (r *AcceptOrderResp, err error)

	StartTrip(ctx context.Context, req *StartTripReq) (r *StartTripResp, err error)

	CompleteOrder(ctx context.Context, req *CompleteOrderReq) (r *CompleteOrderResp, err error)

	CancelOrder(ctx context.Context, req *CancelOrderReq) (r *CancelOrderResp, err error)

	GetIncome(ctx context.Context, req *GetIncomeReq) (r *GetIncomeResp, err error)

	UpdateLocation(ctx context.Context, req *UpdateLocationReq) (r *UpdateLocationResp, err error)
}

type DriverServiceDriverPetitionArgs struct {
	Req *DriverPetitionReq `thrift:"req,1" frugal:"1,default,DriverPetitionReq" json:"req"`
}

func NewDriverServiceDriverPetitionArgs() *DriverServiceDriverPetitionArgs {
	return &DriverServiceDriverPetitionArgs{}
}

func (p *DriverServiceDriverPetitionArgs) InitDefault() {
}

var DriverServiceDriverPetitionArgs_Req_DEFAULT *DriverPetitionReq

func (p *DriverServiceDriverPetitionArgs) GetReq() (v *DriverPetitionReq) {
	if !p.IsSetReq() {
		return DriverServiceDriverPetitionArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *DriverServiceDriverPetitionArgs) SetReq(val *DriverPetitionReq) {
	p.Req = val
}

func (p *DriverServiceDriverPetitionArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *DriverServiceDriverPetitionArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DriverServiceDriverPetitionArgs(%+v)", *p)
}

var fieldIDToName_DriverServiceDriverPetitionArgs = map[int16]string{
	1: "req",
}

type DriverServiceDriverPetitionResult struct {
	Success *DriverPetitionResp `thrift:"success,0,optional" frugal:"0,optional,DriverPetitionResp" json:"success,omitempty"`
}

func NewDriverServiceDriverPetitionResult() *DriverServiceDriverPetitionResult {
	return &DriverServiceDriverPetitionResult{}
}

func (p *DriverServiceDriverPetitionResult) InitDefault() {
}

var DriverServiceDriverPetitionResult_Success_DEFAULT *DriverPetitionResp

func (p *DriverServiceDriverPetitionResult) GetSuccess() (v *DriverPetitionResp) {
	if !p.IsSetSuccess() {
		return DriverServiceDriverPetitionResult_Success_DEFAULT
	}
	return p.Success
}
func (p *DriverServiceDriverPetitionResult) SetSuccess(x interface{}) {
	p.Success = x.(*DriverPetitionResp)
}

func (p *DriverServiceDriverPetitionResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *DriverServiceDriverPetitionResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DriverServiceDriverPetitionResult(%+v)", *p)
}

var fieldIDToName_DriverServiceDriverPetitionResult = map[int16]string{
	0: "success",
}

type DriverServiceCheckStatusArgs struct {
	Req *CheckStatusReq `thrift:"req,1" frugal:"1,default,CheckStatusReq" json:"req"`
}

func NewDriverServiceCheckStatusArgs() *DriverServiceCheckStatusArgs {
	return &DriverServiceCheckStatusArgs{}
}

func (p *DriverServiceCheckStatusArgs) InitDefault() {
}

var DriverServiceCheckStatusArgs_Req_DEFAULT *CheckStatusReq

func (p *DriverServiceCheckStatusArgs) GetReq() (v *CheckStatusReq) {
	if !p.IsSetReq() {
		return DriverServiceCheckStatusArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *DriverServiceCheckStatusArgs) SetReq(val *CheckStatusReq) {
	p.Req = val
}

func (p *DriverServiceCheckStatusArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *DriverServiceCheckStatusArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DriverServiceCheckStatusArgs(%+v)", *p)
}

var fieldIDToName_DriverServiceCheckStatusArgs = map[int16]string{
	1: "req",
}

type DriverServiceCheckStatusResult struct {
	Success *CheckStatusResp `thrift:"success,0,optional" frugal:"0,optional,CheckStatusResp" json:"success,omitempty"`
}

func NewDriverServiceCheckStatusResult() *DriverServiceCheckStatusResult {
	return &DriverServiceCheckStatusResult{}
}

func (p *DriverServiceCheckStatusResult) InitDefault() {
}

var DriverServiceCheckStatusResult_Success_DEFAULT *CheckStatusResp

func (p *DriverServiceCheckStatusResult) GetSuccess() (v *CheckStatusResp) {
	if !p.IsSetSuccess() {
		return DriverServiceCheckStatusResult_Success_DEFAULT
	}
	return p.Success
}
func (p *DriverServiceCheckStatusResult) SetSuccess(x interface{}) {
	p.Success = x.(*CheckStatusResp)
}

func (p *DriverServiceCheckStatusResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *DriverServiceCheckStatusResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DriverServiceCheckStatusResult(%+v)", *p)
}

var fieldIDToName_DriverServiceCheckStatusResult = map[int16]string{
	0: "success",
}

type DriverServiceDriverLoginArgs struct {
	Req *DriverLoginReq `thrift:"req,1" frugal:"1,default,DriverLoginReq" json:"req"`
}

func NewDriverServiceDriverLoginArgs() *DriverServiceDriverLoginArgs {
	return &DriverServiceDriverLoginArgs{}
}

func (p *DriverServiceDriverLoginArgs) InitDefault() {
}

var DriverServiceDriverLoginArgs_Req_DEFAULT *DriverLoginReq

func (p *DriverServiceDriverLoginArgs) GetReq() (v *DriverLoginReq) {
	if !p.IsSetReq() {
		return DriverServiceDriverLoginArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *DriverServiceDriverLoginArgs) SetReq(val *DriverLoginReq) {
	p.Req = val
}

func (p *DriverServiceDriverLoginArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *DriverServiceDriverLoginArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DriverServiceDriverLoginArgs(%+v)", *p)
}

var fieldIDToName_DriverServiceDriverLoginArgs = map[int16]string{
	1: "req",
}

type DriverServiceDriverLoginResult struct {
	Success *DriverLoginResp `thrift:"success,0,optional" frugal:"0,optional,DriverLoginResp" json:"success,omitempty"`
}

func NewDriverServiceDriverLoginResult() *DriverServiceDriverLoginResult {
	return &DriverServiceDriverLoginResult{}
}

func (p *DriverServiceDriverLoginResult) InitDefault() {
}

var DriverServiceDriverLoginResult_Success_DEFAULT *DriverLoginResp

func (p *DriverServiceDriverLoginResult) GetSuccess() (v *DriverLoginResp) {
	if !p.IsSetSuccess() {
		return DriverServiceDriverLoginResult_Success_DEFAULT
	}
	return p.Success
}
func (p *DriverServiceDriverLoginResult) SetSuccess(x interface{}) {
	p.Success = x.(*DriverLoginResp)
}

func (p *DriverServiceDriverLoginResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *DriverServiceDriverLoginResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DriverServiceDriverLoginResult(%+v)", *p)
}

var fieldIDToName_DriverServiceDriverLoginResult = map[int16]string{
	0: "success",
}

type DriverServiceGetDriverInfoArgs struct {
	Req *GetDriverInfoReq `thrift:"req,1" frugal:"1,default,GetDriverInfoReq" json:"req"`
}

func NewDriverServiceGetDriverInfoArgs() *DriverServiceGetDriverInfoArgs {
	return &DriverServiceGetDriverInfoArgs{}
}

func (p *DriverServiceGetDriverInfoArgs) InitDefault() {
}

var DriverServiceGetDriverInfoArgs_Req_DEFAULT *GetDriverInfoReq

func (p *DriverServiceGetDriverInfoArgs) GetReq() (v *GetDriverInfoReq) {
	if !p.IsSetReq() {
		return DriverServiceGetDriverInfoArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *DriverServiceGetDriverInfoArgs) SetReq(val *GetDriverInfoReq) {
	p.Req = val
}

func (p *DriverServiceGetDriverInfoArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *DriverServiceGetDriverInfoArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DriverServiceGetDriverInfoArgs(%+v)", *p)
}

var fieldIDToName_DriverServiceGetDriverInfoArgs = map[int16]string{
	1: "req",
}

type DriverServiceGetDriverInfoResult struct {
	Success *GetDriverInfoResp `thrift:"success,0,optional" frugal:"0,optional,GetDriverInfoResp" json:"success,omitempty"`
}

func NewDriverServiceGetDriverInfoResult() *DriverServiceGetDriverInfoResult {
	return &DriverServiceGetDriverInfoResult{}
}

func (p *DriverServiceGetDriverInfoResult) InitDefault() {
}

var DriverServiceGetDriverInfoResult_Success_DEFAULT *GetDriverInfoResp

func (p *DriverServiceGetDriverInfoResult) GetSuccess() (v *GetDriverInfoResp) {
	if !p.IsSetSuccess() {
		return DriverServiceGetDriverInfoResult_Success_DEFAULT
	}
	return p.Success
}
func (p *DriverServiceGetDriverInfoResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetDriverInfoResp)
}

func (p *DriverServiceGetDriverInfoResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *DriverServiceGetDriverInfoResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DriverServiceGetDriverInfoResult(%+v)", *p)
}

var fieldIDToName_DriverServiceGetDriverInfoResult = map[int16]string{
	0: "success",
}

type DriverServiceUpdateDriverInfoArgs struct {
	Req *UpdateDriverInfoReq `thrift:"req,1" frugal:"1,default,UpdateDriverInfoReq" json:"req"`
}

func NewDriverServiceUpdateDriverInfoArgs() *DriverServiceUpdateDriverInfoArgs {
	return &DriverServiceUpdateDriverInfoArgs{}
}

func (p *DriverServiceUpdateDriverInfoArgs) InitDefault() {
}

var DriverServiceUpdateDriverInfoArgs_Req_DEFAULT *UpdateDriverInfoReq

func (p *DriverServiceUpdateDriverInfoArgs) GetReq() (v *UpdateDriverInfoReq) {
	if !p.IsSetReq() {
		return DriverServiceUpdateDriverInfoArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *DriverServiceUpdateDriverInfoArgs) SetReq(val *UpdateDriverInfoReq) {
	p.Req = val
}

func (p *DriverServiceUpdateDriverInfoArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *DriverServiceUpdateDriverInfoArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DriverServiceUpdateDriverInfoArgs(%+v)", *p)
}

var fieldIDToName_DriverServiceUpdateDriverInfoArgs = map[int16]string{
	1: "req",
}

type DriverServiceUpdateDriverInfoResult struct {
	Success *UpdateDriverInfoResp `thrift:"success,0,optional" frugal:"0,optional,UpdateDriverInfoResp" json:"success,omitempty"`
}

func NewDriverServiceUpdateDriverInfoResult() *DriverServiceUpdateDriverInfoResult {
	return &DriverServiceUpdateDriverInfoResult{}
}

func (p *DriverServiceUpdateDriverInfoResult) InitDefault() {
}

var DriverServiceUpdateDriverInfoResult_Success_DEFAULT *UpdateDriverInfoResp

func (p *DriverServiceUpdateDriverInfoResult) GetSuccess() (v *UpdateDriverInfoResp) {
	if !p.IsSetSuccess() {
		return DriverServiceUpdateDriverInfoResult_Success_DEFAULT
	}
	return p.Success
}
func (p *DriverServiceUpdateDriverInfoResult) SetSuccess(x interface{}) {
	p.Success = x.(*UpdateDriverInfoResp)
}

func (p *DriverServiceUpdateDriverInfoResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *DriverServiceUpdateDriverInfoResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DriverServiceUpdateDriverInfoResult(%+v)", *p)
}

var fieldIDToName_DriverServiceUpdateDriverInfoResult = map[int16]string{
	0: "success",
}

type DriverServiceChangeStatusArgs struct {
	Req *ChangeStatusReq `thrift:"req,1" frugal:"1,default,ChangeStatusReq" json:"req"`
}

func NewDriverServiceChangeStatusArgs() *DriverServiceChangeStatusArgs {
	return &DriverServiceChangeStatusArgs{}
}

func (p *DriverServiceChangeStatusArgs) InitDefault() {
}

var DriverServiceChangeStatusArgs_Req_DEFAULT *ChangeStatusReq

func (p *DriverServiceChangeStatusArgs) GetReq() (v *ChangeStatusReq) {
	if !p.IsSetReq() {
		return DriverServiceChangeStatusArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *DriverServiceChangeStatusArgs) SetReq(val *ChangeStatusReq) {
	p.Req = val
}

func (p *DriverServiceChangeStatusArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *DriverServiceChangeStatusArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DriverServiceChangeStatusArgs(%+v)", *p)
}

var fieldIDToName_DriverServiceChangeStatusArgs = map[int16]string{
	1: "req",
}

type DriverServiceChangeStatusResult struct {
	Success *ChangeStatusResp `thrift:"success,0,optional" frugal:"0,optional,ChangeStatusResp" json:"success,omitempty"`
}

func NewDriverServiceChangeStatusResult() *DriverServiceChangeStatusResult {
	return &DriverServiceChangeStatusResult{}
}

func (p *DriverServiceChangeStatusResult) InitDefault() {
}

var DriverServiceChangeStatusResult_Success_DEFAULT *ChangeStatusResp

func (p *DriverServiceChangeStatusResult) GetSuccess() (v *ChangeStatusResp) {
	if !p.IsSetSuccess() {
		return DriverServiceChangeStatusResult_Success_DEFAULT
	}
	return p.Success
}
func (p *DriverServiceChangeStatusResult) SetSuccess(x interface{}) {
	p.Success = x.(*ChangeStatusResp)
}

func (p *DriverServiceChangeStatusResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *DriverServiceChangeStatusResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DriverServiceChangeStatusResult(%+v)", *p)
}

var fieldIDToName_DriverServiceChangeStatusResult = map[int16]string{
	0: "success",
}

type DriverServiceGetPendingOrdersArgs struct {
	Req *GetPendingOrdersReq `thrift:"req,1" frugal:"1,default,GetPendingOrdersReq" json:"req"`
}

func NewDriverServiceGetPendingOrdersArgs() *DriverServiceGetPendingOrdersArgs {
	return &DriverServiceGetPendingOrdersArgs{}
}

func (p *DriverServiceGetPendingOrdersArgs) InitDefault() {
}

var DriverServiceGetPendingOrdersArgs_Req_DEFAULT *GetPendingOrdersReq

func (p *DriverServiceGetPendingOrdersArgs) GetReq() (v *GetPendingOrdersReq) {
	if !p.IsSetReq() {
		return DriverServiceGetPendingOrdersArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *DriverServiceGetPendingOrdersArgs) SetReq(val *GetPendingOrdersReq) {
	p.Req = val
}

func (p *DriverServiceGetPendingOrdersArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *DriverServiceGetPendingOrdersArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DriverServiceGetPendingOrdersArgs(%+v)", *p)
}

var fieldIDToName_DriverServiceGetPendingOrdersArgs = map[int16]string{
	1: "req",
}

type DriverServiceGetPendingOrdersResult struct {
	Success *GetPendingOrdersResp `thrift:"success,0,optional" frugal:"0,optional,GetPendingOrdersResp" json:"success,omitempty"`
}

func NewDriverServiceGetPendingOrdersResult() *DriverServiceGetPendingOrdersResult {
	return &DriverServiceGetPendingOrdersResult{}
}

func (p *DriverServiceGetPendingOrdersResult) InitDefault() {
}

var DriverServiceGetPendingOrdersResult_Success_DEFAULT *GetPendingOrdersResp

func (p *DriverServiceGetPendingOrdersResult) GetSuccess() (v *GetPendingOrdersResp) {
	if !p.IsSetSuccess() {
		return DriverServiceGetPendingOrdersResult_Success_DEFAULT
	}
	return p.Success
}
func (p *DriverServiceGetPendingOrdersResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetPendingOrdersResp)
}

func (p *DriverServiceGetPendingOrdersResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *DriverServiceGetPendingOrdersResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DriverServiceGetPendingOrdersResult(%+v)", *p)
}

var fieldIDToName_DriverServiceGetPendingOrdersResult = map[int16]string{
	0: "success",
}

type DriverServiceAcceptOrderArgs struct {
	Req *AcceptOrderReq `thrift:"req,1" frugal:"1,default,AcceptOrderReq" json:"req"`
}

func NewDriverServiceAcceptOrderArgs() *DriverServiceAcceptOrderArgs {
	return &DriverServiceAcceptOrderArgs{}
}

func (p *DriverServiceAcceptOrderArgs) InitDefault() {
}

var DriverServiceAcceptOrderArgs_Req_DEFAULT *AcceptOrderReq

func (p *DriverServiceAcceptOrderArgs) GetReq() (v *AcceptOrderReq) {
	if !p.IsSetReq() {
		return DriverServiceAcceptOrderArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *DriverServiceAcceptOrderArgs) SetReq(val *AcceptOrderReq) {
	p.Req = val
}

func (p *DriverServiceAcceptOrderArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *DriverServiceAcceptOrderArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DriverServiceAcceptOrderArgs(%+v)", *p)
}

var fieldIDToName_DriverServiceAcceptOrderArgs = map[int16]string{
	1: "req",
}

type DriverServiceAcceptOrderResult struct {
	Success *AcceptOrderResp `thrift:"success,0,optional" frugal:"0,optional,AcceptOrderResp" json:"success,omitempty"`
}

func NewDriverServiceAcceptOrderResult() *DriverServiceAcceptOrderResult {
	return &DriverServiceAcceptOrderResult{}
}

func (p *DriverServiceAcceptOrderResult) InitDefault() {
}

var DriverServiceAcceptOrderResult_Success_DEFAULT *AcceptOrderResp

func (p *DriverServiceAcceptOrderResult) GetSuccess() (v *AcceptOrderResp) {
	if !p.IsSetSuccess() {
		return DriverServiceAcceptOrderResult_Success_DEFAULT
	}
	return p.Success
}
func (p *DriverServiceAcceptOrderResult) SetSuccess(x interface{}) {
	p.Success = x.(*AcceptOrderResp)
}

func (p *DriverServiceAcceptOrderResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *DriverServiceAcceptOrderResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DriverServiceAcceptOrderResult(%+v)", *p)
}

var fieldIDToName_DriverServiceAcceptOrderResult = map[int16]string{
	0: "success",
}

type DriverServiceStartTripArgs struct {
	Req *StartTripReq `thrift:"req,1" frugal:"1,default,StartTripReq" json:"req"`
}

func NewDriverServiceStartTripArgs() *DriverServiceStartTripArgs {
	return &DriverServiceStartTripArgs{}
}

func (p *DriverServiceStartTripArgs) InitDefault() {
}

var DriverServiceStartTripArgs_Req_DEFAULT *StartTripReq

func (p *DriverServiceStartTripArgs) GetReq() (v *StartTripReq) {
	if !p.IsSetReq() {
		return DriverServiceStartTripArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *DriverServiceStartTripArgs) SetReq(val *StartTripReq) {
	p.Req = val
}

func (p *DriverServiceStartTripArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *DriverServiceStartTripArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DriverServiceStartTripArgs(%+v)", *p)
}

var fieldIDToName_DriverServiceStartTripArgs = map[int16]string{
	1: "req",
}

type DriverServiceStartTripResult struct {
	Success *StartTripResp `thrift:"success,0,optional" frugal:"0,optional,StartTripResp" json:"success,omitempty"`
}

func NewDriverServiceStartTripResult() *DriverServiceStartTripResult {
	return &DriverServiceStartTripResult{}
}

func (p *DriverServiceStartTripResult) InitDefault() {
}

var DriverServiceStartTripResult_Success_DEFAULT *StartTripResp

func (p *DriverServiceStartTripResult) GetSuccess() (v *StartTripResp) {
	if !p.IsSetSuccess() {
		return DriverServiceStartTripResult_Success_DEFAULT
	}
	return p.Success
}
func (p *DriverServiceStartTripResult) SetSuccess(x interface{}) {
	p.Success = x.(*StartTripResp)
}

func (p *DriverServiceStartTripResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *DriverServiceStartTripResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DriverServiceStartTripResult(%+v)", *p)
}

var fieldIDToName_DriverServiceStartTripResult = map[int16]string{
	0: "success",
}

type DriverServiceCompleteOrderArgs struct {
	Req *CompleteOrderReq `thrift:"req,1" frugal:"1,default,CompleteOrderReq" json:"req"`
}

func NewDriverServiceCompleteOrderArgs() *DriverServiceCompleteOrderArgs {
	return &DriverServiceCompleteOrderArgs{}
}

func (p *DriverServiceCompleteOrderArgs) InitDefault() {
}

var DriverServiceCompleteOrderArgs_Req_DEFAULT *CompleteOrderReq

func (p *DriverServiceCompleteOrderArgs) GetReq() (v *CompleteOrderReq) {
	if !p.IsSetReq() {
		return DriverServiceCompleteOrderArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *DriverServiceCompleteOrderArgs) SetReq(val *CompleteOrderReq) {
	p.Req = val
}

func (p *DriverServiceCompleteOrderArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *DriverServiceCompleteOrderArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DriverServiceCompleteOrderArgs(%+v)", *p)
}

var fieldIDToName_DriverServiceCompleteOrderArgs = map[int16]string{
	1: "req",
}

type DriverServiceCompleteOrderResult struct {
	Success *CompleteOrderResp `thrift:"success,0,optional" frugal:"0,optional,CompleteOrderResp" json:"success,omitempty"`
}

func NewDriverServiceCompleteOrderResult() *DriverServiceCompleteOrderResult {
	return &DriverServiceCompleteOrderResult{}
}

func (p *DriverServiceCompleteOrderResult) InitDefault() {
}

var DriverServiceCompleteOrderResult_Success_DEFAULT *CompleteOrderResp

func (p *DriverServiceCompleteOrderResult) GetSuccess() (v *CompleteOrderResp) {
	if !p.IsSetSuccess() {
		return DriverServiceCompleteOrderResult_Success_DEFAULT
	}
	return p.Success
}
func (p *DriverServiceCompleteOrderResult) SetSuccess(x interface{}) {
	p.Success = x.(*CompleteOrderResp)
}

func (p *DriverServiceCompleteOrderResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *DriverServiceCompleteOrderResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DriverServiceCompleteOrderResult(%+v)", *p)
}

var fieldIDToName_DriverServiceCompleteOrderResult = map[int16]string{
	0: "success",
}

type DriverServiceCancelOrderArgs struct {
	Req *CancelOrderReq `thrift:"req,1" frugal:"1,default,CancelOrderReq" json:"req"`
}

func NewDriverServiceCancelOrderArgs() *DriverServiceCancelOrderArgs {
	return &DriverServiceCancelOrderArgs{}
}

func (p *DriverServiceCancelOrderArgs) InitDefault() {
}

var DriverServiceCancelOrderArgs_Req_DEFAULT *CancelOrderReq

func (p *DriverServiceCancelOrderArgs) GetReq() (v *CancelOrderReq) {
	if !p.IsSetReq() {
		return DriverServiceCancelOrderArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *DriverServiceCancelOrderArgs) SetReq(val *CancelOrderReq) {
	p.Req = val
}

func (p *DriverServiceCancelOrderArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *DriverServiceCancelOrderArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DriverServiceCancelOrderArgs(%+v)", *p)
}

var fieldIDToName_DriverServiceCancelOrderArgs = map[int16]string{
	1: "req",
}

type DriverServiceCancelOrderResult struct {
	Success *CancelOrderResp `thrift:"success,0,optional" frugal:"0,optional,CancelOrderResp" json:"success,omitempty"`
}

func NewDriverServiceCancelOrderResult() *DriverServiceCancelOrderResult {
	return &DriverServiceCancelOrderResult{}
}

func (p *DriverServiceCancelOrderResult) InitDefault() {
}

var DriverServiceCancelOrderResult_Success_DEFAULT *CancelOrderResp

func (p *DriverServiceCancelOrderResult) GetSuccess() (v *CancelOrderResp) {
	if !p.IsSetSuccess() {
		return DriverServiceCancelOrderResult_Success_DEFAULT
	}
	return p.Success
}
func (p *DriverServiceCancelOrderResult) SetSuccess(x interface{}) {
	p.Success = x.(*CancelOrderResp)
}

func (p *DriverServiceCancelOrderResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *DriverServiceCancelOrderResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DriverServiceCancelOrderResult(%+v)", *p)
}

var fieldIDToName_DriverServiceCancelOrderResult = map[int16]string{
	0: "success",
}

type DriverServiceGetIncomeArgs struct {
	Req *GetIncomeReq `thrift:"req,1" frugal:"1,default,GetIncomeReq" json:"req"`
}

func NewDriverServiceGetIncomeArgs() *DriverServiceGetIncomeArgs {
	return &DriverServiceGetIncomeArgs{}
}

func (p *DriverServiceGetIncomeArgs) InitDefault() {
}

var DriverServiceGetIncomeArgs_Req_DEFAULT *GetIncomeReq

func (p *DriverServiceGetIncomeArgs) GetReq() (v *GetIncomeReq) {
	if !p.IsSetReq() {
		return DriverServiceGetIncomeArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *DriverServiceGetIncomeArgs) SetReq(val *GetIncomeReq) {
	p.Req = val
}

func (p *DriverServiceGetIncomeArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *DriverServiceGetIncomeArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DriverServiceGetIncomeArgs(%+v)", *p)
}

var fieldIDToName_DriverServiceGetIncomeArgs = map[int16]string{
	1: "req",
}

type DriverServiceGetIncomeResult struct {
	Success *GetIncomeResp `thrift:"success,0,optional" frugal:"0,optional,GetIncomeResp" json:"success,omitempty"`
}

func NewDriverServiceGetIncomeResult() *DriverServiceGetIncomeResult {
	return &DriverServiceGetIncomeResult{}
}

func (p *DriverServiceGetIncomeResult) InitDefault() {
}

var DriverServiceGetIncomeResult_Success_DEFAULT *GetIncomeResp

func (p *DriverServiceGetIncomeResult) GetSuccess() (v *GetIncomeResp) {
	if !p.IsSetSuccess() {
		return DriverServiceGetIncomeResult_Success_DEFAULT
	}
	return p.Success
}
func (p *DriverServiceGetIncomeResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetIncomeResp)
}

func (p *DriverServiceGetIncomeResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *DriverServiceGetIncomeResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DriverServiceGetIncomeResult(%+v)", *p)
}

var fieldIDToName_DriverServiceGetIncomeResult = map[int16]string{
	0: "success",
}

type DriverServiceUpdateLocationArgs struct {
	Req *UpdateLocationReq `thrift:"req,1" frugal:"1,default,UpdateLocationReq" json:"req"`
}

func NewDriverServiceUpdateLocationArgs() *DriverServiceUpdateLocationArgs {
	return &DriverServiceUpdateLocationArgs{}
}

func (p *DriverServiceUpdateLocationArgs) InitDefault() {
}

var DriverServiceUpdateLocationArgs_Req_DEFAULT *UpdateLocationReq

func (p *DriverServiceUpdateLocationArgs) GetReq() (v *UpdateLocationReq) {
	if !p.IsSetReq() {
		return DriverServiceUpdateLocationArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *DriverServiceUpdateLocationArgs) SetReq(val *UpdateLocationReq) {
	p.Req = val
}

func (p *DriverServiceUpdateLocationArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *DriverServiceUpdateLocationArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DriverServiceUpdateLocationArgs(%+v)", *p)
}

var fieldIDToName_DriverServiceUpdateLocationArgs = map[int16]string{
	1: "req",
}

type DriverServiceUpdateLocationResult struct {
	Success *UpdateLocationResp `thrift:"success,0,optional" frugal:"0,optional,UpdateLocationResp" json:"success,omitempty"`
}

func NewDriverServiceUpdateLocationResult() *DriverServiceUpdateLocationResult {
	return &DriverServiceUpdateLocationResult{}
}

func (p *DriverServiceUpdateLocationResult) InitDefault() {
}

var DriverServiceUpdateLocationResult_Success_DEFAULT *UpdateLocationResp

func (p *DriverServiceUpdateLocationResult) GetSuccess() (v *UpdateLocationResp) {
	if !p.IsSetSuccess() {
		return DriverServiceUpdateLocationResult_Success_DEFAULT
	}
	return p.Success
}
func (p *DriverServiceUpdateLocationResult) SetSuccess(x interface{}) {
	p.Success = x.(*UpdateLocationResp)
}

func (p *DriverServiceUpdateLocationResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *DriverServiceUpdateLocationResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DriverServiceUpdateLocationResult(%+v)", *p)
}

var fieldIDToName_DriverServiceUpdateLocationResult = map[int16]string{
	0: "success",
}
